### ISSUE TITLE
设计了几款UI，希望有帮助

### ISSUE THREAD

**Issue by RebirthEgo** [WXRIW/Lyricify-App#10]
![歌词UI-02](https://user-images.githubusercontent.com/54738173/118390126-1592f400-b660-11eb-8542-d3b257367528.png)

![歌词UI-03](https://user-images.githubusercontent.com/54738173/118390128-17f54e00-b660-11eb-85b2-52fe6d0196cd.png)

![歌词UI-04](https://user-images.githubusercontent.com/54738173/118390129-188de480-b660-11eb-92d7-d5160d8abb11.png)

![歌词UI-05](https://user-images.githubusercontent.com/54738173/118390131-1a57a800-b660-11eb-8f8a-e06d3a11a419.png)

![歌词UI-06](https://user-images.githubusercontent.com/54738173/118390138-1d529880-b660-11eb-9a19-2e13c4051a0f.png)

![歌词UI-07](https://user-images.githubusercontent.com/54738173/118390145-22afe300-b660-11eb-91c0-717eb5d1c7bc.png)

**Comment by WXRIW** [comment]
暂时没有太大打算修改UI，因为下学期就高三了，这一年只能做到基本运行的维护，大修大改没有时间。
如果有好的UI设计，也欢迎放在这里，我以后会考虑的。
还有一点就是，上面的几幅图不满足Spotify官方的设计要求，做出来之后可能会遭到官方封杀。
![image](https://user-images.githubusercontent.com/62491584/118396199-f9537f00-b680-11eb-8383-700a697d4c44.png)

**Comment by WXRIW** [comment]
十分感谢您对Lyricify的支持和认可！

**Comment by RebirthEgo** [comment]
> 暂时没有太大打算修改UI，因为下学期就高三了，这一年只能做到基本运行的维护，大修大改没有时间。
> 如果有好的UI设计，也欢迎放在这里，我以后会考虑的。
> 还有一点就是，上面的几幅图不满足Spotify官方的设计要求，做出来之后可能会遭到官方封杀。
> ![image](https://user-images.githubusercontent.com/62491584/118396199-f9537f00-b680-11eb-8383-700a697d4c44.png)

没事，当做着玩呗，高二就能弄这个才子呀

**Comment by Delysid749** [comment]
请问歌词是从其他软件爬虫爬过来的吗

**Comment by Delysid749** [comment]
哈哈哈哈哈好的好的👌🏿


发自我的iPhone

**Comment by WXRIW** [comment]
4.0 UI重构，我觉得还是挺不错的，所以这个 Issue 就先关闭啦，感谢你的支持！！！模糊背景真的是很好看

**Comment by WXRIW** [comment]
@RebirthEgo 你好呀，4.0 主体开发基本完成，目前浅色主题的配色不是很好看，不知道您是否愿意加入 Lyricify 预览体验计划，帮忙设计出一套好看的浅色主题配色，提升 Lyricify 体验！感谢你一直以来对 Lyricify 的支持。

**Comment by TheMonitor007** [comment]
@WXRIW 我愿意
