### ISSUE TITLE
打开歌曲管理时崩溃

### ISSUE THREAD

**Issue by ddaodan** [WXRIW/Lyricify-App#100]
![image](https://user-images.githubusercontent.com/40017293/213920720-6533bb5d-3304-4b75-b97f-445d8c532115.png)
点击 是 并不会正常关闭，托盘图标依然存在，双击还可以打开一个空白的界面，右键无反应

**Comment by WXRIW** [comment]
@ddaodan 你是不是开启了关闭按钮隐藏到通知栏

**Comment by WXRIW** [comment]
@ddaodan 这个bug已经修复，等待明天推送。但是崩溃的问题，暂时无法修复，在使用指南里也写了

**Comment by ddaodan** [comment]
> @ddaodan 你是不是开启了关闭按钮隐藏到通知栏

是的

> @ddaodan 这个bug已经修复，等待明天推送。但是崩溃的问题，暂时无法修复，在使用指南里也写了

好的，大佬辛苦了，等明天更新试试看

**Comment by cocgy1108** [comment]
請問直接在城市中選歌會提示需要Premuim是只需要購買Spotify會員是嗎?
