### ISSUE TITLE
Local media -> file

### ISSUE THREAD

**Issue by maskalix** [WXRIW/Lyricify-App#102]
Hi!
Can you add lyrics scraping for local media?
I have plenty of music in my PC and want to just click and get lyrics. 
To .txt or so.

Please, that would be brilliant.
🙏🙏

**Comment by WXRIW** [comment]
@maskalix Sorry, but Lyricify cannot do this. It can only get lyrics for songs playing in Spotify. You can use Spotify to play your local music files.

**Comment by maskalix** [comment]
but what if instead of data from Spotify Now playing i input txt file full of song names? 
then it could work...
and also EXPORT the result...
🤷‍♂️🤷‍♂️

**Comment by WXRIW** [comment]
@maskalix I didn’t get your point. But it seems like something Lyricify cannot do
