### ISSUE TITLE
多次添加歌词会导致Lyricify内存溢出

### ISSUE THREAD

**Issue by SheepYhangCN** [WXRIW/Lyricify-App#103]
今天给pepoyo的曲子上传歌词
基本上都是同时导入了QQ音乐和网易云
每次上传了两三首之后再打开导入界面就会白屏
![H6PZJ_@A7 N9B U7P5E()~W](https://user-images.githubusercontent.com/44539204/214211770-9606b5ee-0a1f-43d2-b39e-498df4ec6c9b.png)
按下原本关闭所在的位置/右上角X本身所在的位置就能关掉
然后就会弹出一个窗口报错显示内存溢出
关掉之后软件仍然可以操作 但是画面不会动
![DL7QBITZ30`K4OFYUM}P 46](https://user-images.githubusercontent.com/44539204/214211777-e58e6351-2d16-4682-bd1e-5f4d3e606c0f.png)

**Comment by WXRIW** [comment]
## 程序渲染线程崩溃
整个界面假死或纯白，画面完全不动，但是实际上可以操作（比如调整窗口大小，鼠标点击有反应，鼠标指针在不同地方不一样之类的反馈）。  
日志中记录为 `System.Runtime.InteropServices.COMException: UCEERR_RENDERTHREADFAILURE` 或 `System.OutOfMemoryException: Insufficient memory to continue the execution of the program.`  
该问题发现于 `2022 年 12 月下旬`。
### 导致原因
未知。目前没有找到具体原因。可能是 WPF 本身的问题，也可能是 Media Session 导致的问题，还怀疑是 Windows 11 Mica 材质的问题。
### 解决方案
重新打开 Lyricify。

**Comment by SheepYhangCN** [comment]
okay我是盲人
