### ISSUE TITLE
Apple Music模式 歌词滚动时严重卡顿

### ISSUE THREAD

**Issue by AkkoYK** [WXRIW/Lyricify-App#104]
仅在歌词滚动时出现性能问题，严重掉帧，尝试开关卡拉OK模式无用
5700X + 3070，以1080p全屏运行

**Comment by WXRIW** [comment]
看使用说明最后的介绍

**Comment by AkkoYK** [comment]
抱歉，刚刚才看到，但似乎在我这里是第一首就会开始卡顿

**Comment by WXRIW** [comment]
## Apple Music 歌词界面卡顿问题
如果是打开该界面的第一首歌就很卡，那就是你电脑性能不够。可尝试 `已知问题` - `Apple Music 歌词界面卡顿问题` 中的 1, 2, 4, 5 条。不要全屏，因为全屏需要占用很多资源，硬件性能不够就不要去尝试！
### 首选解决方案
1. 关闭模糊
2. 不要全屏，建议调成竖屏模式，总之，窗口越小，越流畅

**Comment by WXRIW** [comment]
wpf无法完全利用你的显卡资源

**Comment by AkkoYK** [comment]
好吧，非常感谢解答，Lyricfy的全屏也非常不错

**Comment by cuteday** [comment]
@WXRIW 我的笔记本是集显+独显(3070)的配置，看了一下集显的占用率相当高（尤其是开AM歌词的时候），而独显占用率0。dalao有处理多显卡的情况么，还是说利用独显不好实现或基于能耗的考虑...

@AkkoYK 楼主也是集显+独显的配置么

**Comment by WXRIW** [comment]
手动去系统设置里把lyricify分配给独显

**Comment by cuteday** [comment]
> 手动去系统设置里把lyricify分配给独显

啊啊感谢，显卡驱动里是可以按应用分配gpu的。我被图形api允许程序员手动选择设备那一套毒害了...
