### ISSUE TITLE
Mobile：Google登录提醒“错误 403: disallowed_useragent”

### ISSUE THREAD

**Issue by cooaer** [WXRIW/Lyricify-App#105]
我也遇到过这个问题，原因是因为UserAgent有问题，带有webview的标示，修改为浏览器的UserAgent就没问题了！
![image](https://user-images.githubusercontent.com/4060489/214280445-8c302cb1-3ff9-4b20-8228-8b4a682207f6.png)

**Comment by WXRIW** [comment]
我去找了一下资料，目前 Xamarin.Forms 不支持 Customizing user-agent

**Comment by WXRIW** [comment]
目前还是用Spotify登录吧，去Spotify完善一下邮箱和密码就行了
