### ISSUE TITLE
切换移动端视图时，行间距不改变

### ISSUE THREAD

**Issue by clover-yan** [WXRIW/Lyricify-App#106]
## Bug 详情
在普通视图和移动端视图之间切换时，行间距不会随设定值改变。

## 复现方法
1. 为普通视图和移动端视图设置不同的行间距；
2. 打开歌词界面；
3. 改变窗口大小，以切换到移动端视图；
4. 改变窗口大小，以切换到普通视图。

### 预期的结果
行间距不会改变。

## 已有的解决方式
切换视图之后，再进入设置，调节相应的行间距。

### 预期的结果
行间距与设定值相符。

**Comment by clover-yan** [comment]
@clover-yan 此处是针对 Lyricify 歌词。
（Apple Music 歌词本身没有行间距功能。）

**Comment by WXRIW** [comment]
已修复，等待下个版本推送
