### ISSUE TITLE
feat: Lyricify如果可以支持一下关联启动就更好了 就是启动Lyricify时启动spotify

### ISSUE THREAD

**Issue by iosyyy** [WXRIW/Lyricify-App#108]
如题

**Comment by WXRIW** [comment]
@iosyyy 此功能在 Lyricify 4 中已被移除。
建议开启启动 Spotify，并最小化。需要听音乐的时候开启 Lyricify 即可。

**Comment by Potato009** [comment]
> 如题

在lyricify 3版的左上角扩展菜单里已经支持了这个功能
![图片](https://user-images.githubusercontent.com/37134725/214503859-738ead7f-198f-4c68-8bbd-ae7c1254bf3f.png)
