### ISSUE TITLE
桌面歌词里歌词对齐的建议

### ISSUE THREAD

**Issue by FY-SSGG** [WXRIW/Lyricify-App#109]
![image](https://user-images.githubusercontent.com/36985048/214508906-ffeae480-55a1-4b7d-9248-0aa6cac88e81.png)
用的4.01的版本，希望可以能在歌词对齐里增加设置，让歌词顶端对齐。现在歌词和顶端有一截距离怎么也不能往上移。

**Comment by Potato009** [comment]
你试试重置一下位置和大小看看？

**Comment by WXRIW** [comment]
暂时没有这个打算，这个是windows的限制

**Comment by WXRIW** [comment]
可以通过添加副屏，并且高度高于主屏幕，这样就可以移动上去了

**Comment by WXRIW** [comment]
（虽然不现实
