### ISSUE TITLE
播放bug

### ISSUE THREAD

**Issue by jlu511** [WXRIW/Lyricify-App#110]
先开启spotify，最小化，然后开启lyricify4，在lyricify4里面点播放，提示premium，或者429

![图片1](https://user-images.githubusercontent.com/64378673/214803794-d1316cb7-0d11-47c0-8fd9-02da837e0480.png)
![图片2](https://user-images.githubusercontent.com/64378673/214803822-010b0e4e-372b-40c2-80a0-5f12fae0446d.png)

**Comment by WXRIW** [comment]
麻烦阅读使用说明，谢谢

**Comment by Potato009** [comment]
> 先开启spotify，最小化，然后开启lyricify4，在lyricify4里面点播放，提示premium，或者429
> 
> ![图片1](https://user-images.githubusercontent.com/64378673/214803794-d1316cb7-0d11-47c0-8fd9-02da837e0480.png) ![图片2](https://user-images.githubusercontent.com/64378673/214803822-010b0e4e-372b-40c2-80a0-5f12fae0446d.png)

现在的版本（除非不是小白之类的）强烈建议先去认真阅读使用指南再去使用
