### ISSUE TITLE
岑宁儿《一个人走走》无歌词

### ISSUE THREAD

**Issue by Luciushy** [WXRIW/Lyricify-App#111]
<img width="525" alt="Lyricify_for_Spotify_AgL5WYcGRx" src="https://user-images.githubusercontent.com/9025035/215087671-25bc7644-bcbb-4685-ad0b-1b9c49d039a7.png">
spotify原生显示歌词，但是，lyricify反而无结果。
请问，从musixmatch抓取歌词的风险大吗？能实现吗？

**Comment by WXRIW** [comment]
没有歌词可以自行去导入，目前 Lyricify 官方不会支持 Musixmatch 歌词的自动导入
