### ISSUE TITLE
关于lyricify4中apple music版歌词字体大小问题

### ISSUE THREAD

**Issue by wubingcong** [WXRIW/Lyricify-App#112]
applemusic歌词字体大小不能调整，设置里只能调整界面字体，spotify歌词字体大小，没有看到applemusic版歌词字体大小

**Comment by WXRIW** [comment]
@wubingcong ctrl++或-

**Comment by wubingcong** [comment]
感谢回复，平时习惯了ctrl+滚轮，把这种方法给忘了
________________________________
发件人: XY Wang ***@***.***>
发送时间: 2023年1月28日 13:46
收件人: WXRIW/Lyricify-App ***@***.***>
抄送: wubingcong ***@***.***>; Mention ***@***.***>
主题: Re: [WXRIW/Lyricify-App] 关于lyricify4中apple music版歌词字体大小问题 (Issue #112)


@wubingcong<https://github.com/wubingcong> ctrl++或-

―

**Comment by WXRIW** [comment]
@wubingcong ctrl加滚轮也可以的

**Comment by wubingcong** [comment]
好吧确实可以，早上应该是我电脑出bug了，但是这样调整之后，重新打开applemusic歌词字体还是很大
________________________________
发件人: XY Wang ***@***.***>
发送时间: 2023年1月28日 14:13
收件人: WXRIW/Lyricify-App ***@***.***>
抄送: wubingcong ***@***.***>; Mention ***@***.***>
主题: Re: [WXRIW/Lyricify-App] 关于lyricify4中apple music版歌词字体大小问题 (Issue #112)


@wubingcong<https://github.com/wubingcong> ctrl加滚轮也可以的

―

**Comment by WXRIW** [comment]
@wubingcong 这个是固定的不能保存

**Comment by wubingcong** [comment]
好的
________________________________
发件人: XY Wang ***@***.***>
发送时间: 2023年1月28日 14:22
收件人: WXRIW/Lyricify-App ***@***.***>
抄送: wubingcong ***@***.***>; Mention ***@***.***>
主题: Re: [WXRIW/Lyricify-App] 关于lyricify4中apple music版歌词字体大小问题 (Issue #112)


@wubingcong<https://github.com/wubingcong> 这个是固定的不能保存

―

**Comment by WXRIW** [comment]
固定功能已完成，下个版本推送。好东西就要来了。
