### ISSUE TITLE
安装出现该提示 无法安装

### ISSUE THREAD

**Issue by zero617** [WXRIW/Lyricify-App#114]
![image](https://user-images.githubusercontent.com/67105838/215317856-79cbabb9-6bd9-4c14-bab1-f3441e8aa3a0.png)

**Comment by WXRIW** [comment]
请提供更完整的信息，比如你之前是否安装过Lyricify 4，等等，尽量详细一点

**Comment by zero617** [comment]
> 请提供更完整的信息，比如你之前是否安装过Lyricify 4，等等，尽量详细一点

未安装过Lyricify 4，之安装过老版本的Lyricify
再次安装后可以完成安装，但无法启动程序，没有任何提示，后台也没有运行
系统：Windows Feature Experience Pack 1000.22638.1000.0

**Comment by WXRIW** [comment]
有没有安装 .Net 6 运行环境 （32位）

**Comment by zero617** [comment]
> 有没有安装 .Net 6 运行环境 （32位）

![image](https://user-images.githubusercontent.com/67105838/215318170-7470e5be-9912-49dd-9bd5-15d23f71d98c.png)

**Comment by WXRIW** [comment]
你下载压缩版 (.7z) 看看能不能打开

**Comment by zero617** [comment]
> 你下载压缩版 (.7z) 看看能不能打开

同无法启动

**Comment by WXRIW** [comment]
会不会是杀软的问题，你看看 `%appdata%/Lyricify/Lyricify for Spotify` 里有没有 `Log.txt`

**Comment by zero617** [comment]
> 会不会是杀软的问题，你看看 `%appdata%/Lyricify/Lyricify for Spotify` 里有没有 `Log.txt`

额，根本还没生成这个文件夹

**Comment by WXRIW** [comment]
你换台设备试试看，如果其他设备可以用起来，那就说明你系统可能有问题
