### ISSUE TITLE
切换播放设备导致media session连接失败和无法不科学上网获得播放状态信息

### ISSUE THREAD

**Issue by liuzeji** [WXRIW/Lyricify-App#115]
【进行的操作】
1.未连接蓝牙设备前打开spotify和lyrycify
2.关闭tz，连接耳机，手动切换默认设备

【遇到的问题】
media session连接失败，无法获取到spotify的播放状态

【尝试过的解决方案】
科学上网环境下重启liricify，media session连接正常，播放状态识别正常，关闭梯子后仍无法获取spotify的最新播放状态，media session显示已连接。［疑似原因为请求API达限制］

【近期用过的一些东西】
使用过Windows的播放到设备向耳机（非默认播放设备）播放音乐

【希望达到的】
像liricify3那样不用科学上网本地获取播放信息，不用科学上网可登陆使用

不太清楚media session的原理，如果是Windows问题请大佬直接close issue

**Comment by Potato009** [comment]
lyricify 4版开始使用梯子和spotify premium（内置播放等需要）等才能达到最佳体验，建议不要想不用梯这种事情，而是全程挂梯

**Comment by Potato009** [comment]
同时建议仔细查看仓库的使用指南

**Comment by WXRIW** [comment]
Lyricify 3 支持不登录是继承了 Lyricify 2 的特性，Lyricify 3 开始支持 Spotify 登录。不登录获取不到播放进度，获取不到专辑图片，获取不到播放曲目的 ID，也就无法在 Lyricify 4 词库中获取歌词。
Media Session 在一通操作后失效是因为 Spotify 的 Media Session 太垃圾了，跟依托答辩一样，解决方案就是重启 Spotify。
只有登录必须科学上网，登录之后是可以不用科学上网的。
