### ISSUE TITLE
无法获取spotify的最新播放信息（premium，科学上网正常）

### ISSUE THREAD

**Issue by liuzeji** [WXRIW/Lyricify-App#116]
抱歉打扰 ，如题
![屏幕截图 2023-01-30 195345](https://user-images.githubusercontent.com/110678360/215470184-55e4afe4-e45c-4b89-be61-70ead86d96bd.jpg)
![屏幕截图 2023-01-30 195413](https://user-images.githubusercontent.com/110678360/215470203-01a2a1a2-e13e-4c26-b9f0-6a28ecd24aa9.jpg)

**Comment by WXRIW** [comment]
重启lyricify，看看是不是还是显示这首歌

**Comment by liuzeji** [comment]
重启后第一首没问题，切歌就识别不到了



***@***.***
 
发件人： XY Wang
发送时间： 2023-01-30 19:56
收件人： WXRIW/Lyricify-App
抄送： liuzeji; Author
主题： Re: [WXRIW/Lyricify-App] 无法获取spotify的最新播放信息（premium，科学上网正常） (Issue #116)
重启lyricify，看看是不是还是显示这首歌

**Comment by WXRIW** [comment]
尝试手动刷新，看看能不能刷新出来
![image](https://user-images.githubusercontent.com/62491584/215473251-5cc236b9-c6fd-4a50-9572-d986b78bbc89.png)

**Comment by liuzeji** [comment]
> 尝试手动刷新，看看能不能刷新出来 ![image](https://user-images.githubusercontent.com/62491584/215473251-5cc236b9-c6fd-4a50-9572-d986b78bbc89.png)

试过，没反应

刚刚又重启一遍，科学上网下识别到了切歌，延迟10s左右
断梯没法用
前两天还可以，很魔性

**Comment by WXRIW** [comment]
试试3和4一起打开，如果都不能正常反应切歌，那就是spotify客户端自己的问题了

**Comment by liuzeji** [comment]
> 试试3和4一起打开，如果都不能正常反应切歌，那就是spotify客户端自己的问题了

3我没有登录，一切正常，等我登下试试

**Comment by WXRIW** [comment]
一定要看登录后的结果

**Comment by liuzeji** [comment]
登陆了，断梯连梯3均正常，，4至今无反应



***@***.***
 
发件人： XY Wang
发送时间： 2023-01-30 20:16
收件人： WXRIW/Lyricify-App
抄送： liuzeji; Author
主题： Re: [WXRIW/Lyricify-App] 无法获取spotify的最新播放信息（premium，科学上网正常） (Issue #116)
一定要看登录后的结果

**Comment by WXRIW** [comment]
尝试关闭media session

**Comment by liuzeji** [comment]
无效



***@***.***
 
发件人： XY Wang
发送时间： 2023-01-30 20:21
收件人： WXRIW/Lyricify-App
抄送： liuzeji; Author
主题： Re: [WXRIW/Lyricify-App] 无法获取spotify的最新播放信息（premium，科学上网正常） (Issue #116)
尝试关闭media session

**Comment by WXRIW** [comment]
我感觉应该是你的网络问题，你换一个节点试试，或者换一家科学上网试试看。你目前这种情况我没有遇到过

**Comment by liuzeji** [comment]
> 我感觉应该是你的网络问题，你换一个节点试试，或者换一家科学上网试试看。你目前这种情况我没有遇到过

好吧，感谢

**Comment by liuzeji** [comment]
> 我感觉应该是你的网络问题，你换一个节点试试，或者换一家科学上网试试看。你目前这种情况我没有遇到过

 我重新安装了4.0.1.230123，没用科学上网，成功登录并且现在一切正常。似乎是230125有佛系bug

**Comment by WXRIW** [comment]
我感觉应该不是新版本的问题，因为这个更新并不大，并且没有修改有关播放状态获取的代码
