### ISSUE TITLE
重复出现429错误+AMD平台运行效率问题

### ISSUE THREAD

**Issue by Oats00** [WXRIW/Lyricify-App#117]
Hello，在B站评论区反映过只要用Lyricify播放就会出现429错误的问题，这段时间一直没有过好转，想请问一下可能是什么原因造成的。
运行库齐全，目前质疑是不是因为我人不在国内的问题，但是Spotify的API感觉应该不会出现这个问题，翻回国内也没有改善，而且用其他设备或者同电脑原版Spotify播放歌曲时，Lyricify也能正常显示歌曲的播放进度和歌词，就比较奇怪。
另一个问题是我在AMD平台使用的时候感觉有明显的卡顿，Apple Music风格的歌词动画有时候会直接卡死，但是另一台相对比较老的intel平台电脑就没有问题，双系统的Macbook也没有问题，目前出现卡顿的机器用的是R5 5600G+16G DDR4 RAM+1063，情况好一点的老电脑只有i7-6700HQ+8G DDR3+960M，MBP的配置也只有i5-8259U+8G LPDDR3+核显。

**Comment by Potato009** [comment]
429是因为请求太多了，服务器受不了，无法避免

**Comment by Oats00** [comment]
我最近一个星期一直有试，正常时间和大半夜都有，一直是这个报错，感觉有别的问题

**Comment by clover-yan** [comment]
@Oats00 是 Spotify 服务器的问题，Lyricify 没法让 Spotify 服务器响应。

**Comment by Potato009** [comment]
@Oats00 请认真看完使用指南，里面明确说了429就不是lyricify的锅😓

**Comment by WXRIW** [comment]
![image](https://user-images.githubusercontent.com/62491584/215646392-33a78ae4-f079-48b0-ab12-27d44b77c20c.png)![image](https://user-images.githubusercontent.com/62491584/215646482-4bf21815-535b-4971-95a2-af057df5e16e.png)

**Comment by WXRIW** [comment]
你是用的是lyricify内嵌播放吗，我个人建议是不使用这个功能，当时做这个功能就只是实验性的，实际使用的体验并不是很好。
我建议使用spotify客户端，这样lyricify可以通过media session与其建立连接，可以做到无延迟的播放控制。

关于amd平台卡顿的问题，目前我也没有解决办法。这个得看微软的优化，因为我使用的是微软的wpf，并没有针对任何平台进行特殊优化

**Comment by WXRIW** [comment]
429出现了，只有一个办法，就是等，我也无能为力，播放控制使用media session可以避免走spotify api，进而避免429

am卡顿，建议按照使用说明里的方法来调整，不要全屏，不要打开模糊效果，卡顿会缓解很多
