### ISSUE TITLE
[Feature Request][Mobile]适配状态栏歌词

### ISSUE THREAD

**Issue by 66Leo66** [WXRIW/Lyricify-App#118]
希望 Lyricify Android 端适配 [StatusBarLyric](https://github.com/Block-Network/StatusBarLyric) 项目。该项目提供了 [API](https://github.com/577fkj/StatusBarApiExample) 用于软件主动适配。

**Comment by WXRIW** [comment]
目前不考虑，Lyricify Mobile 仅开发 Android + iOS 均可用的功能

**Comment by Potato009** [comment]
> 希望 Lyricify Android 端适配 [StatusBarLyric](https://github.com/Block-Network/StatusBarLyric) 项目。该项目提供了 [API](https://github.com/577fkj/StatusBarApiExample) 用于软件主动适配。

这个事还是问lyricist吧。。
