### ISSUE TITLE
打开曲目管理显示 "服务器歌词信息加载失败"

### ISSUE THREAD

**Issue by ZZZZzzzzac** [WXRIW/Lyricify-App#119]
版本 Lyricify for Spotify Ver 4.0.2.230125-release

科不科学都是, 也没找到log之类的

**Comment by WXRIW** [comment]
你首次登录的时候有没有显示你的用户序号

**Comment by ZZZZzzzzac** [comment]
好像有, 但是不记得了. 
我尝试再次登录好像也不显示, 不过再次登录后可以打开曲目管理了

**Comment by WXRIW** [comment]
能打开就好，可能是因为你一开始登录的时候因为网络原因没有完成lyricify服务器注册
