### ISSUE TITLE
应用请求报错，无法正常使用。

### ISSUE THREAD

**Issue by yongdianxiin** [WXRIW/Lyricify-App#12]
![QQ图片20210530060110](https://user-images.githubusercontent.com/37495624/120085636-7b758600-c10c-11eb-90dd-471d67edcd6e.png)

**Comment by WXRIW** [comment]
Spotify有没有正在播放的歌曲

**Comment by yongdianxiin** [comment]
没有。刚打开spotify和歌词软件就会这样，持续了三天。刚刚我打开软件倒可以正常使用了。

**Comment by WXRIW** [comment]
好的，那我先关闭issue了
