### ISSUE TITLE
[Request] 移动 Apple Music 的竖版歌词的位置

### ISSUE THREAD

**Issue by Silent-wqh** [WXRIW/Lyricify-App#120]
可以将 Apple Music 的竖版歌词的正在播放位置朝下调一些吗？或者添加一个调整歌词位置的参数。
![image](https://user-images.githubusercontent.com/24985177/216573240-f43e4897-8d63-4e7f-9e05-a4ea79cc8e2d.png)
如上图所示。

**Comment by WXRIW** [comment]
@Silent-wqh 并且am是1:1复刻apple music的，如果改动，效果会变差，也会涉及到动画的调整
