### ISSUE TITLE
 [Lyricify4] 新版Apple Music 全屏界面 在AMD显卡设备上好像有bug

### ISSUE THREAD

**Issue by a757814283** [WXRIW/Lyricify-App#123]
冒昧的问一下 “更好的质量” 需要什么级别的显卡才能流畅...

在开启Apple Music歌词全屏后卡顿很严重，在切换歌词的时候可能只有个位数的帧数，但是旧版的Apple Music歌词没有出现问题，
Lyricify全屏也相当流畅，不确定是bug还是我驱动问题。

我的设备显卡是AMD的RX 6600XT，CPU是5800X。

如果是bug希望大佬可以修复，Lyricify是我体验到现在最棒的歌词软件！
已支持，感谢大佬的付出！

**Comment by Asukaaa648** [comment]
我也遇到相同的问题，看了一下显卡占用，Copy占用率在80%居高不下，重启电脑之后就能解决，感觉像是amd驱动的问题。
显卡是AMD的RX 6700XT，CPU是5800X。

**Comment by Asukaaa648** [comment]
找到解决办法了，在设置中关闭动态时间状态就好了

**Comment by Asukaaa648** [comment]
如果打开这个，有时候流畅有时候卡顿
