### ISSUE TITLE
提一些自己小小的想法

### ISSUE THREAD

**Issue by Fox-Yuan** [WXRIW/Lyricify-App#124]
我个人觉得现在的4.0版本其实有点不够精简。提一些自己的想法：
1. 界面其实并不用弄得和Spotify一模一样，音乐库、已点赞歌曲、固定项目栏其实都没必要，这些功能大部分时候仅仅是摆设，其实都不太会用到；固定项目栏其实可以直接把桌面歌词、灵动岛歌词这类操作放出来的。这样省去了点左上角选项栏的操作，操作更人性化。
2. 主页其实也不用关联Spotify上的推荐，每次进来都要加载半天其实观感不太好，其实只用显示大大的介绍信息就好了。毕竟这其实只是个歌词软件，没有会员其实不能直接放歌的。
3. 希望增加mini模式（类似QQ音乐和网易云），方便暂停切歌之类的，这个我觉得还挺实用的。
仅仅是我的一些个人看法哈，不代表别人。最后夸一句仿am歌词太好看啦！

**Comment by WXRIW** [comment]
1. 有会员的用户，这些地方都很有用的，也可以方便管理歌词，没有这些地方，想要管理不在播放的歌曲的歌词就很麻烦了。桌面歌词等都可以用快捷键来打开。已经预留了把功能固定在侧栏的功能，不过现在还没完全开发出来。  
你目前描述的这个界面一般来说，只看歌词的话是用不到的，所以应该是不影响使用的。
3. Lyricify 主页和 Spotify 主页内容并不一致，并且这个主页一般来说也不会打开，除非不在放歌。
4. 只有 桌面歌词 和 灵动词岛，其中桌面歌词有播放控制功能的。所以暂时没有计划去单独开发一个。

**Comment by WXRIW** [comment]
如果没有其他问题，此 Issue 暂时关闭。
