### ISSUE TITLE
建议调整一下中文翻译的字体亮度

### ISSUE THREAD

**Issue by Anyayay** [WXRIW/Lyricify-App#126]
建议调整一下中文翻译的字体亮度，可以与还未播放的歌词亮度一致。

因为当切换至下一句歌词时，中文翻译的亮度较大而原文亮度较小，反而错误地突现了中文翻译，造成了观感的不适

![image](https://user-images.githubusercontent.com/37764175/222915676-bd491df3-5db5-4c69-98c8-52fd3fd6cf9b.png)

**Comment by WXRIW** [comment]
不接受此建议。这里的中文是我经过多次调整找到的最合适的透明度。如果设置为未播放行的不透明度，则会产生更差的效果。
