### ISSUE TITLE
Media Session未连接

### ISSUE THREAD

**Issue by Love-in-idleness** [WXRIW/Lyricify-App#127]
退出重登也还是连不上，科学上网使用也是不行
还有这个api调用频繁……好痛苦，3的时候啥事都没有啊~

**Comment by WXRIW** [comment]
3 你没登录吧，不然 429 错误比 4 还多

**Comment by WXRIW** [comment]
Media Session 未连接已经在使用指南里写了，你阅读过了吗
https://github.com/WXRIW/Lyricify-App/blob/main/docs/Lyricify%204/README.md#media-session-%E6%9C%AA%E8%BF%9E%E6%8E%A5

**Comment by Love-in-idleness** [comment]
刚刚根据指南检查了一边……设置都没问题
然后我发现我没有试过把spotify客户端（uwp）退出重登（我刚刚只试了把lyricify退出重登）
spotify客户端退出重登后就没问题了
