### ISSUE TITLE
播放韩文歌曲时只显示中文部分

### ISSUE THREAD

**Issue by zackymony** [WXRIW/Lyricify-App#129]
歌词源为QQ音乐时,韩文歌曲只显示中文翻译.
QQ音乐本身有韩文原文

**Comment by WXRIW** [comment]
提供曲目分享链接，及截图

**Comment by zackymony** [comment]
曲目链接:https://open.spotify.com/track/3BPoSr2pO34Aan6alFfVto?si=99467cb30cdc4b01
![QQ截图202](https://user-images.githubusercontent.com/117845926/228721188-aa2f4f34-b6e9-4bb6-8e33-151d0f56829e.png)

**Comment by WXRIW** [comment]
自行导入q音歌词即可
