### ISSUE TITLE
BUG: 使用 YesPlayMusic 歌词延迟问题

### ISSUE THREAD

**Issue by SouLXH** [WXRIW/Lyricify-App#13]
部分歌词不同步，歌词是获取的网易服务器的吗？是歌词本身时间戳就是不同步导致的吗？

《宋冬野 - 郭源潮》中一开始就有延迟  可能我吹毛求疵了，不过第二次听得时候延迟问题就不明显了，第一次播放延迟大约几秒，第二次播放延迟小于一秒

**Comment by WXRIW** [comment]
歌词是从通过id从网易云直接获取的，Lyricify对与YesPlayMusic和iTunes会有时间轴优化，在延迟过大的情况下会自动纠正至同步。
可以提供下这首歌的id（或者网易云分享链接），我来看下。

**Comment by SouLXH** [comment]
![image](https://user-images.githubusercontent.com/44329481/121623128-be871000-caa1-11eb-96fb-58404efe1355.png)
延迟可以接受，就是与yesplaymusic自带歌词形成了对比，延迟半秒左右吧，

**Comment by WXRIW** [comment]
Lyricify针对YesPlayMusic进行了优化，会自动将歌词提前300ms显示（因为YesPlayMusic有bug，详见[YesPlayMusic Issue #652](https://github.com/qier222/YesPlayMusic/issues/652)），所以通常情况下YesPlayMusic里的歌词是会慢300ma左右的。
