### ISSUE TITLE
iOS能否提供ipa自签

### ISSUE THREAD

**Issue by alphavvv** [WXRIW/Lyricify-App#130]

**Comment by WXRIW** [comment]
@alphavvv 我没mac，编译不出来ipa

**Comment by firedevel** [comment]
可以装黑苹果啊，或者告诉我怎么配置环境有时间我帮你编译

**Comment by WXRIW** [comment]
@firedevel 1. 主力机不可能装，没时间没精力去弄
2. 首次编译和调试是非常麻烦的事，远程起来是非常麻烦的，但是感谢你的热心
我自己就是 iOS 设备，但是现在只能眼巴巴看着安卓用户用，自己却用不上

**Comment by WXRIW** [comment]
Lyricify Mobile iOS 短时间内将仅提供 IPA 安装包，此 Issue 关闭。
