### ISSUE TITLE
Portable

### ISSUE THREAD

**Issue by WXRIW** [WXRIW/Lyricify-App#132]
预计于 4.1 的某个版本开始支持

**Comment by kaokao221** [comment]
@WXRIW 支持什么，IPA自签吗

**Comment by WXRIW** [comment]
@kaokao221 在想啥呢，Lyricify 4 跟 iOS 有毛线关系

**Comment by WXRIW** [comment]
@WXRIW 标题写的很清楚了，Portable

**Comment by jokerwen1** [comment]
> 标题写的很清楚了，便携

大佬，必须要同时运行Lyricify 4和 Spotify才能显示歌词吗？

**Comment by WXRIW** [comment]
@jokerwen1 不要在无关 Issue 里提问，有问题在群里问，有 Bug 在 Issues 里提

**Comment by azhe403** [comment]
Store settings and any to current .exe directory instead of `AppData\Roaming\Lyricify\Lyricify for Spotify` will make this app more great!

**Comment by WXRIW** [comment]
此功能已完成，并随 4.1.11 发布。
This function is completed and has been released with 4.1.11.
