### ISSUE TITLE
桌面歌词的视觉效果

### ISSUE THREAD

**Issue by evilhentaro** [WXRIW/Lyricify-App#134]
![image](https://user-images.githubusercontent.com/17069107/234763874-663603a8-ea1e-44d0-a6ae-b7052b27109d.png)
上面是4.x桌面歌词的视觉效果
下面是3的，希望4.x的视效能柔和些。

**Comment by WXRIW** [comment]
下一版本对抗锯齿做了优化，可以体验体验。发光效果可能还要多等几个版本

**Comment by WXRIW** [comment]
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/4ccf5464-542a-422a-b502-8f0f7b1db273)
已添加阴影（发光）效果

**Comment by evilhentaro** [comment]
多谢大佬~
