### ISSUE TITLE
mobile端获取token异常，无法登陆

### ISSUE THREAD

**Issue by sf32d** [WXRIW/Lyricify-App#135]
最新版mobile.v1.2.2，可以正常登陆spotify账号，但卡在获取token步骤，获取token时总是闪出一个异常界面并立马返回至原界面。点击继续也是一样，会闪回。
系统:安卓13
操作过程全程开全局代理
spotify已开通premium

**Comment by WXRIW** [comment]
闪出的异常界面截个图看看，还有现在最新版是 1.2.3

**Comment by sf32d** [comment]
不好意思说错了，是1.2.3。刚刚叙述的就是图一界面，图二为闪出的异常。

XY Wang ***@***.***> 于 2023年4月30日周日 00:34写道：

**Comment by sf32d** [comment]
刚刚用手机（Android11）测试了下，也是同样的问题
![mmexport1682788799950](https://user-images.githubusercontent.com/121218135/235315770-dc5c5cb0-1f0c-4fb4-a7ee-7c596c6be551.jpg)
![mmexport1682788795307](https://user-images.githubusercontent.com/121218135/235315780-9d628ad4-1ace-4f5f-b9f4-3db84bb475ad.jpg)

**Comment by WXRIW** [comment]
梯子关掉试试看

**Comment by WXRIW** [comment]
长时间无回应，此 Issue 关闭
