### ISSUE TITLE
有些歌曲获取不到歌词

### ISSUE THREAD

**Issue by xiegoudan** [WXRIW/Lyricify-App#136]
![image](https://user-images.githubusercontent.com/67531128/236123402-ab6da5a9-4845-4f0a-8062-a2d20d52e2fb.png)
这首歌明明就是普通歌曲，给识别成纯音乐了。。

**Comment by WXRIW** [comment]
自己导入歌词

**Comment by xiegoudan** [comment]
> 
已找到使用文档，感谢
