### ISSUE TITLE
感觉歌词源好像用Musixmatch更加全一点

### ISSUE THREAD

**Issue by ZenoWang1999** [WXRIW/Lyricify-App#137]
而且在qq音乐匹配不上歌词的情况下好像并不会用网易云的代替

**Comment by WXRIW** [comment]
@ZenoWang1999 没使用网易云是因为网易云也没搜到。Musixmatch 不会支持自动搜索，因为其不支持翻译。这种情况自己去 QQ 音乐 或 网易云音乐 导入正确歌词就行了

**Comment by WXRIW** [comment]
@ZenoWang1999 另外，Musixmatch 逐字很少，并且质量极差
