### ISSUE TITLE
【建议】客户端窗口处于焦点状态下隐藏桌面歌词

### ISSUE THREAD

**Issue by WolfHero** [WXRIW/Lyricify-App#138]
如题，当用户从托盘或任务栏激活Lyricify窗口后，用户的动机应该是通过Lyricify窗口阅览歌词，此时桌面歌词并不在用户视觉焦点上。

私以为可以提供一个选项，以允许Lyricify窗口处于焦点时隐藏桌面歌词，相信会是一个有用的功能。

**Comment by WXRIW** [comment]
我询问了一些用户，他们都表示这个功能用处不大，所以本功能划入 `个人需求` 类。Lyricify 目前暂不考虑个人需求。
其次，本功能的实现逻辑会比较复杂，使用较简单的逻辑体验将不是很好。
