### ISSUE TITLE
YesPlayMusic 暂停后歌词失效

### ISSUE THREAD

**Issue by SouLXH** [WXRIW/Lyricify-App#14]
![image](https://user-images.githubusercontent.com/44329481/121622610-e75ad580-caa0-11eb-9893-994cd4f9bd37.png)
 暂停一段时间后  桌面歌词直接挂了，无法继续同步歌词，切歌也无效，感觉是Lyricify的bug

**Comment by WXRIW** [comment]
需要提供Lyricify主界面的截图

**Comment by WXRIW** [comment]
发现这个桌面歌词并不是Lyricify的，而是YesPlayMusic的，这个bug也与Lyricify无关。

**Comment by WXRIW** [comment]
建议更换使用Lyricify桌面歌词，不再使用YesPlayMusic内置的歌词。
