### ISSUE TITLE
希望对lyricify3增加对apple music的支持

### ISSUE THREAD

**Issue by rayslovewyn** [WXRIW/Lyricify-App#140]
希望对lyricify3增加对apple music的支持

**Comment by WXRIW** [comment]
@rayslovewyn 看使用说明

**Comment by WXRIW** [comment]
https://github.com/WXRIW/Lyricify-App/tree/main/docs/Lyricify%203#%E6%98%AF%E5%90%A6%E4%BC%9A%E6%94%AF%E6%8C%81-apple-music-preview

**Comment by WXRIW** [comment]
最新版 3.8.5 已添加支持
