### ISSUE TITLE
将主窗口和灵动词岛的中文翻译选项分开设置

### ISSUE THREAD

**Issue by sygiegiehs** [WXRIW/Lyricify-App#142]
能否将主窗口和灵动词岛的中文翻译选项分开设置？感觉灵动词岛显示两行内容不好看。

**Comment by WXRIW** [comment]
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/a51bc4a7-4f83-4a22-97b2-bcb7ffdbd748)
已添加，等待推送。
