### ISSUE TITLE
【画个大饼】Lyricify Lite

### ISSUE THREAD

**Issue by WXRIW** [WXRIW/Lyricify-App#144]
Lyricify Lite，轻量级 Lyricify。
保留极其简洁的功能，提供最具创新的体验。

**Comment by kengwang** [comment]
蹲, 出了踢我一下 (斜眼笑)

**Comment by wayner6** [comment]
如 可以不提供界面，只提供设置项，可以将灵动岛、Apple music歌词剥离出来，只作为显示一个桌面歌词的插件
期待一下，软件本身已经非常好用啦，再也不用担心spotify的歌词问题喽😍😍😍❤️

**Comment by WXRIW** [comment]
> 如 可以不提供界面，只提供设置项，可以将灵动岛、Apple music歌词剥离出来，只作为显示一个桌面歌词的插件 期待一下，软件本身已经非常好用啦，再也不用担心spotify的歌词问题喽😍😍😍❤️

只会把灵动词岛提出来，其他功能没有计划。

**Comment by cyo57** [comment]
for Android可以像类似于国产音乐软件那样支持悬浮窗歌词吗

**Comment by WXRIW** [comment]
@cyo57 1. 不要在不相关的 Issue 里提问
2. 这个问题我在 Lyricify Mobile 使用指南里写到了

**Comment by LINKlang** [comment]
询问一下lite的制作进度，真的太需要了

**Comment by WXRIW** [comment]
> 询问一下lite的制作进度，真的太需要了

目前快要新建文件夹了。最近在学校比较忙，所以没什么时间去计划开发 Lyricify Lite。

**Comment by 00CruelSummer** [comment]
已经等不及啦狠狠的期待

**Comment by zxjzxj0010** [comment]
已经等不及啦，狠狠的期待！！！

**Comment by chicken666** [comment]
蹲个macOS版的

**Comment by WXRIW** [comment]
@chicken666 Lite 不会支持 macOS。

**Comment by tsavpyn** [comment]
据说半年前就新建文件夹了，现在应该已经新建Repo了，好期待！😋

**Comment by WXRIW** [comment]
@tsavpyn 快了快了

**Comment by WXRIW** [comment]
Lyricify Lite 于 2024 年 7 月 27 日正式进入开发，敬请期待。

**Comment by 835231037** [comment]
移动端能不能跟进一下，落后太多

**Comment by 835231037** [comment]
大佬，移动端

**Comment by tsavpyn** [comment]
移动端建议老老实实先用Mobile）

在 2024年7月29日，01:59，夜班车乘务员 ***@***.***> 写道：

﻿

大佬，移动端

**Comment by 835231037** [comment]
移动太简单了

**Comment by PhantomPixel-0418** [comment]
前排支持！
(2024 年应用商店奖：在 Windows 上的 Microsoft 应用商店中提名您最喜欢的应用和游戏)[https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR_lzdMcHC_tMqWeRwoTd7TRUMlZZWk5ZUk1JU0Q4RU03S1BKU0xHRExNVi4u]
提了Lyricify

**Comment by G10100100010** [comment]
请问您有想过开发能在车机上使用spotify的计划吗？😊

**Comment by WXRIW** [comment]
@G10100100010 下一代 Lyricify Mobile 计划支持 Apple CarPlay。

**Comment by G10100100010** [comment]
> @G10100100010 下一代 Lyricify Mobile 计划支持 Apple CarPlay。

那真是太棒了🤣

**Comment by G10100100010** [comment]
> @G10100100010 下一代 Lyricify Mobile 计划支持 Apple CarPlay。

期待😍

**Comment by WXRIW** [comment]
Lyricify Lite 开发进度过半，欢迎加群 [665831280](https://qm.qq.com/q/mxIMJi43MQ) 抢先体验。

> Lyricify Lite 是 Lyricify 家族即将推出的新软件，它运行于 Windows 平台，仅保留了灵动词岛功能，支持所有接入了 SMTC 的音乐播放器，包括 HyPlayer、LyricEase、Apple Music、QQ 音乐、网易云音乐 UWP、Foobar 2000、Groove Music 等诸多音乐软件。
> 
> 由于仍然处于开发初期，软件 bug 较多，体验不好之处敬请谅解。最新版在群文件可找到，遇到任何问题可直接在群里提出！谢谢各位 Lyricify 用户的支持！

**Comment by ENCRE0520** [comment]
要是能支持Apple music就好了 ；）

**Comment by WXRIW** [comment]
@ENCRE0520 支持

**Comment by WXRIW** [comment]
Lyricify Lite 预计将于 12 月初正式发布，各位在使用中遇到任何问题或是有意见或建议，可随时在群里提出，争取在正式发布前完善！感谢各位的支持！

欢迎加群 [665831280](https://qm.qq.com/q/mxIMJi43MQ) 抢先体验。

**Comment by big-tooth** [comment]
> Lyricify Lite 预计将于 12 月初正式发布，各位在使用中遇到任何问题或是有意见或建议，可随时在群里提出，争取在正式发布前完善！感谢各位的支持！
> 
> 欢迎加群 [665831280](https://qm.qq.com/q/mxIMJi43MQ) 抢先体验。

期待 Lyricify Lite 正式版

**Comment by WXRIW** [comment]
Lyricify Lite 将于明日正式发布，本 issue 关闭。
