### ISSUE TITLE
程序启动时的登录似乎无法走手动代理

### ISSUE THREAD

**Issue by 1ooper** [WXRIW/Lyricify-App#147]
启动时必须开系统代理才能登录，否则登录不上，代理的设置如下：
`  
  "proxy": {
    "is_enabled": true,
    "host": "127.0.0.1",
    "port": 9999,
    "username": "",
    "password": "",
    "disable_proxy_for_lyricify_server": true 
  }
`

**Comment by WXRIW** [comment]
登录不上具体是什么原因导致的，请提供。（超时错误 还是 429 错误）
登录时是会使用设置的代理的，如果遇到登录不上，应该是网络问题。跟是否开启系统代理无关。

**Comment by 1ooper** [comment]
超时错误。使用clash verge进行代理。在保证其他设置不变的情况下，开启系统代理可以正常登录使用，关闭系统代理，出现超时错误。具体地，当关闭系统代理时，代理日志会有连接e.wxriw.cn的记录：`[TCP] connected lAddr=127.0.0.1:14327 rAddr=e.wxriw.cn:22608 mode=rule rule=DomainSuffix(cn) proxy=全球直连[DIRECT]` 但是无法找到连接spotify api的记录。当打开系统代理时，才有连接spotify api的记录。

**Comment by WXRIW** [comment]
已修复，等待新版推送。
