### ISSUE TITLE
Lyricify更新程序显示不全

### ISSUE THREAD

**Issue by sygiegiehs** [WXRIW/Lyricify-App#148]
在高分屏 (缩放比大于 100%)下，执行“替代高 DPI 缩放行为，并将 缩放执行 复选框选为 系统。”后，Lyricify有新版本可用时，更新窗口显示不全，无法自动更新。
![屏幕截图 2023-06-15 223001](https://github.com/WXRIW/Lyricify-App/assets/124494789/c22312ad-4c1e-4de0-8513-3e214b9e3cf2)

**Comment by WXRIW** [comment]
这个问题已经出现许久了，感觉是上游问题。
可以麻烦您帮忙确定一下吗，安装一下我的另一款软件的旧版本，它使用的是同款的原版自动更新，您安装好之后打开，发一下更新提示的截图，然后卸载即可。
这是安装包下载链接：https://github.com/WXRIW/Ink-Canvas/releases/download/v3.7.0/Ink.Canvas.Setup.Ver.3.7.0-release.exe

**Comment by sygiegiehs** [comment]
> 这个问题已经出现许久了，感觉是上游问题。 可以麻烦您帮忙确定一下吗，安装一下我的另一款软件的旧版本，它使用的是同款的原版自动更新，您安装好之后打开，发一下更新提示的截图，然后卸载即可。 这是安装包下载链接：https://github.com/WXRIW/Ink-Canvas/releases/download/v3.7.0/Ink.Canvas.Setup.Ver.3.7.0-release.exe

这个貌似没有问题。
![屏幕截图 2023-06-16 101522](https://github.com/WXRIW/Lyricify-App/assets/124494789/6d21c64d-b854-4a92-8f73-3f5b65898412)

**Comment by WXRIW** [comment]
好的，感谢测试。我抽空来检查一下。
目前可以提供以下几个临时解决方案：
1. 出现这个更新提示时，保证焦点在该弹窗上，直接按回车即可更新。
2. 使用 Microsoft Store 版，由微软负责自动更新。
3. 将系统语言改为英文。

**Comment by sygiegiehs** [comment]
> 好的，感谢测试。我抽空来检查一下。 目前可以提供以下几个临时解决方案：
> 
> 1. 出现这个更新提示时，保证焦点在该弹窗上，直接按回车即可更新。
> 2. 使用 Microsoft Store 版，由微软负责自动更新。
> 3. 将系统语言改为英文。

好的，感谢

**Comment by sygiegiehs** [comment]
> 

或者能否提供一个“检测到新版本时，不询问并直接更新”的选项？

**Comment by WXRIW** [comment]
这个一般是我来控制的，有些更新会采用强制更新的方式。后期可能会考虑做这个功能。
目前Microsoft Store版本可以做到自动更新，无需任何干涉。

**Comment by sygiegiehs** [comment]
Store版本执行“替代高 DPI 缩放行为，并将 缩放执行 复选框选为 系统”后，再次启动好像并不会降低清晰度，无法保证Apple Music歌词界面的流畅度，这也是我没有使用Store版本的原因。

**Comment by WXRIW** [comment]
确实是这样的，Store 版本被认为是适配了高 DPI 的应用，所以无法覆写。

**Comment by WXRIW** [comment]
下一版本将提供自动更新的选项，并自动开启。显示不全的问题需等待进一步修复。

**Comment by WXRIW** [comment]
考虑到目前主推 Microsoft Store 版本，且功能更全，加上本 Issue 的问题因系统语言问题，解决起来比较麻烦，故暂时不再做修复。Issue 做关闭处理，感谢理解和支持！
