### ISSUE TITLE
i7 12700h核显使用apple歌词时掉帧比较严重

### ISSUE THREAD

**Issue by Chengmao233** [WXRIW/Lyricify-App#150]
调用任务管理器看到核显被用到60左右
歌词模糊等级2级
关闭动态封面 2k分辨率
歌词滚动时掉帧严重，一动基本掉到20，这96eu的核显应该不至于这样吧     :(

**Comment by WXRIW** [comment]
@Chengmao233 模糊关掉，我就是这个核显。WPF 的模糊很吃显卡，Xe是带不动的

**Comment by Chengmao233** [comment]
行吧  等多会有预算换个锐龙核显或者rtx吧（或许什么时候优化更好点就不用换了）

**Comment by WXRIW** [comment]
@Chengmao233 优化希望不大，WPF是比较老的东西了，微软不会有什么大的优化了
