### ISSUE TITLE
Lyricify 4 parses Spotify lyrics timestamps incorrectly

### ISSUE THREAD

**Issue by wizpizz** [WXRIW/Lyricify-App#151]
As shown in the screenshot below, when importing lyrics from Spotify, the timestamp format does not match Lyricify's timestamp parsing format.

Spotify formats like this: `minutes:seconds.milliseconds`

Lyricify seems to parse `minutes:seconds` and ignores the period `.` between `seconds` and `milliseconds` which leads to parsing the milliseconds as seconds as well.

![image](https://github.com/WXRIW/Lyricify-App/assets/76851476/f965a47a-fe96-4a84-8745-0648f780a25e)

**Comment by WXRIW** [comment]
Nothing's wrong on my side.
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/b97ad63a-27e1-42c1-9eea-29578ce211ff)

**Comment by joew8** [comment]
Different region formats cause this problem. 
A quick solution is, change the decimal separator in your system. 
1. Open Control Panel. View by **Category**
2. Choose **Clock and Region**
3. Choose **Region**
4. In the Region dialogue box, choose **Additional settings**...
5. In the Customize Format dialogue box, change the **Digit grouping symbol** to a different symbol(such as ",").

**Comment by wizpizz** [comment]
> Different region formats cause this problem. A quick solution is, change the decimal separator in your system.
> 
> 1. Open Control Panel. View by **Category**
> 2. Choose **Clock and Region**
> 3. Choose **Region**
> 4. In the Region dialogue box, choose **Additional settings**...
> 5. In the Customize Format dialogue box, change the **Decimal Symbol** to ".".
> 6. Restart Lyricify 4.

Yep, that seems to fix it. Thanks.

Though, I think Lyricify should use a period `.` universally, so that people do not have to rely on this fix, as it messes with other programs as well that take advantage of regional formatting, like Office 365.

**Comment by WXRIW** [comment]
@wizpizz I’ll check this out in the coming months. Thanks for your information and patience.

**Comment by WXRIW** [comment]
May I know the default **Decimal Symbol** settings on your system that caused this issue? @wizpizz

**Comment by wizpizz** [comment]
> May I know the default **Decimal Symbol** settings on your system that caused this issue? @wizpizz

My PC is using the default German (Germany) formatting, so the default decimal symbol is set to a comma `,`

![image](https://github.com/WXRIW/Lyricify-App/assets/76851476/396a1ceb-1505-43cc-8959-22310492af68)

**Comment by WXRIW** [comment]
> > May I know the default **Decimal Symbol** settings on your system that caused this issue? @wizpizz
> 
> My PC is using the default German (Germany) formatting, so the default decimal symbol is set to a comma `,`

Okay, thanks for your information.

**Comment by WXRIW** [comment]
I have made some fixes on this issue, and it should be officially fixed with the release of Lyricify 4.2 (which), thanks for your patience.

**Comment by WXRIW** [comment]
This fix will be released today, so I'm closing this issue. If you have further concerns, be free to reopen it.
