### ISSUE TITLE
桌面歌词功能无置顶功能

### ISSUE THREAD

**Issue by Tack-d** [WXRIW/Lyricify-App#152]
一边全屏玩游戏，一边打开桌面歌词的时候，游戏画面会覆盖桌面歌词。歌词图层无置顶显示的按钮。因此是否可以增加一个歌词置顶的选项

**Comment by clover-yan** [comment]
@Tack-d 应该没有办法。歌词本身就是置顶的，如果在游戏里发现歌词没置顶，说明游戏的全屏窗口也是置顶的，那么 Lyricify 难以突破此限制。

建议查看游戏中有无窗口置顶的相关选项。

**Comment by WXRIW** [comment]
有些游戏是独占全屏，这时候是无法显示其他应用的。建议联系游戏开发商。
