### ISSUE TITLE
歌曲暂停时让动态专辑封面也同步暂停

### ISSUE THREAD

**Issue by St7530** [WXRIW/Lyricify-App#155]
希望 Apple Music 歌词界面，当歌曲暂停时，动态专辑封面（如果有）也能同步暂停播放。

**Comment by WXRIW** [comment]
@St7530 好主意，下个版本加上

**Comment by St7530** [comment]
另外，大佬能否让更多的歌曲支持动态专辑封面？许多 Apple Music 提供的动态专辑封面还是相当美观的。

**Comment by WXRIW** [comment]
@St7530 暂时没有这个打算

**Comment by WXRIW** [comment]
@St7530 视频比较占用服务器资源，并且不断增加更多视频的支持也需要很多人力。目前这个视频封面是作为一种彩蛋的形式的

**Comment by St7530** [comment]
> @St7530 视频比较占用服务器资源，并且不断增加更多视频的支持也需要很多人力。目前这个视频封面是作为一种彩蛋的形式的

OK明白，感谢你

**Comment by WXRIW** [comment]
已完成，将随下次更新发布。
