### ISSUE TITLE
希望能够支持AIMP和foobar 2000音乐播放器

### ISSUE THREAD

**Issue by swat00789** [WXRIW/Lyricify-App#156]
希望能够支持AIMP和foobar 2000音乐播放器

**Comment by WXRIW** [comment]
@swat00789 Lyricify 3 已经结束维护生命周期，不再提供新功能。
Lyricify 4 专为 Spotify 设计，无法提供其他软件支持。
未来将发布的 Lyricify Lite 和 Lyricify Next Generation 将为接入 GSMTC 的应用提供歌词支持。

**Comment by WXRIW** [comment]
长时间没有新的留言，此 Issue 关闭。
