### ISSUE TITLE
（可能是bug）无法识别到歌词部分

### ISSUE THREAD

**Issue by WINFMEMZ2020** [WXRIW/Lyricify-App#157]
描述：无法识别歌曲歌词部分，歌词源使用网易云音乐只能识别到前两行，歌词源使用QQ音乐提示找不到这首歌的歌词，手动导入歌词也只能识别到前两行
相关歌曲链接：https://music.163.com/song?id=2043149465
https://open.spotify.com/track/2zvIVS1rSOtmOPWggGeq7e?si=dce2fb31cac64e73
视频：
https://github.com/WXRIW/Lyricify-App/assets/64178216/40eecee2-9952-4812-94f7-08a042f4a9ec

**Comment by WXRIW** [comment]
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/1463e1de-0a59-44d8-8ea5-48c21bbb7bcf)
老问题，这首歌的网易云歌词本身不符合 LRC 歌词规范，只有前两行是符合的，后面所有行均不符合。
