### ISSUE TITLE
桌面歌词颜色自定义颜色操作逻辑&功能建议

### ISSUE THREAD

**Issue by Mouseiswolf** [WXRIW/Lyricify-App#159]
调整桌面颜色歌词时，如果原本是自定义颜色，这时想要修改自定义颜色，必须先修改为其他颜色，然后点击自定义方可修改。可否修改此处的逻辑，使得直接点击自定义便可修改颜色。此外，当修改自定义颜色时，此前设置的颜色会丢失，能否增加记忆上次颜色和之前自定义颜色功能？
除此之外，能否在桌面歌词增加更多自定义选项，如水平/垂直歌词，歌词与翻译行间距等？

**Comment by clover-yan** [comment]
@Mouseiswolf 我有同样的问题。

**Comment by WXRIW** [comment]
> 调整桌面颜色歌词时，如果原本是自定义颜色，这时想要修改自定义颜色，必须先修改为其他颜色，然后点击自定义方可修改。可否修改此处的逻辑，使得直接点击自定义便可修改颜色。
这个问题之前有用户提到过，但是我在尝试了几种方式后仍然无法修复，所以就没修了，没啥大影响。

> 此外，当修改自定义颜色时，此前设置的颜色会丢失，能否增加记忆上次颜色和之前自定义颜色功能？
ColorPicker 调用的是系统对话框，具体保存逻辑由系统负责。

> 水平/垂直歌词
制作极其复杂，不考虑。并且垂直歌词目前最多只能做成旋转 90° 的效果，看歌词会很别扭。

> 歌词与翻译行间距
目前框架下添加此功能代码改动成本较高，所以暂不考虑。

**Comment by clover-yan** [comment]
@WXRIW 我提供一个可能的解决方案，用于自定义颜色选择：

默认情况下，Combo Box 呈现为：

| 封面主题色 |
|:---------- |
| 封面主题色 |
| 白色 |
| 自定义颜色 |

选择自定义颜色之后，弹出 Color Picker，选取想要的颜色，例如我选择 #66CCFF，之后 Combo Box 变为：

| #66CCFF |
|:------- |
| 封面主题色 |
| 白色 |
| #66CCFF |
| 自定义颜色 |

此后，每次选择自定义颜色都能够自定义颜色，并可通过切换回之前的选项来保留之前的一次选择。

**Comment by WXRIW** [comment]
长时间没有新的留言，此 Issue 关闭。
