### ISSUE TITLE
[bug]桌面歌词    高分屏/副屏适配问题

### ISSUE THREAD

**Issue by SouLXH** [WXRIW/Lyricify-App#16]
![ly1](https://user-images.githubusercontent.com/44329481/122445984-ba448080-cfd4-11eb-8cf0-cf768f5562a0.jpg)
![ly2](https://user-images.githubusercontent.com/44329481/122445993-bc0e4400-cfd4-11eb-8712-cfdf32c66d32.jpg)
图一是  笔记本高分屏
图二是副屏 普通屏，，，
图一 鼠标在桌面歌词上可以正常调节但是移动到副屏上，hover 范围下移了（红色方框标出）

希望设计一下桌面歌词、、、、

**Comment by WXRIW** [comment]
没太听懂，可能是在高dpi和低dpi自动切换时的问题，最好有录屏（鼠标拖动桌面歌词移动从主屏到副屏的全过程）

**Comment by WXRIW** [comment]
由于很久没有提供更多信息，此issue关闭。
