### ISSUE TITLE
桌面歌词黑屏

### ISSUE THREAD

**Issue by windsky2021** [WXRIW/Lyricify-App#160]
<img width="1200" alt="{42859877-70FE-413c-8127-170AA94F9DFA}" src="https://github.com/WXRIW/Lyricify-App/assets/95155475/a80e71d7-bcf6-4d3f-a95d-89b8ce5a5d08">
点开桌面歌词后，歌词虽然可以正常显示，但是歌词背景部分却黑屏了，而且拖动桌面歌词也会使黑屏随之移动，望解答

**Comment by WXRIW** [comment]
这种情况一般是由于安装了一些非官方软件导致的，如 MicaForEveryone 等

**Comment by windsky2021** [comment]
> 这种情况一般是由于安装了一些非官方软件导致的，如 MicaForEveryone 等

好的，我去排查一下

**Comment by WXRIW** [comment]
请问此问题是否得到解决

**Comment by windsky2021** [comment]
> 请问此问题是否得到解决

非常感谢，卸载后已经得到解决

**Comment by WXRIW** [comment]
好的好的
