### ISSUE TITLE
[建议]记忆并自动设置对不同设备的设备延迟

### ISSUE THREAD

**Issue by Anyayay** [WXRIW/Lyricify-App#162]
场景：我有时候会直接听，有时候会带着耳机，而设备延迟的设置还要另外调整
需求：检测不同的播放设备，并进行记忆设置，下次再用该设备时自动设置设备延迟

**Comment by WXRIW** [comment]
这个我也想做，我甚至想做自动延迟。但是可惜的是很难做，由于 Lyricify 甚至支持你不在电脑上播放的时候看歌词，所以这一功能的实现变得非常复杂。
目前解决方案就是尽量使用同一设备，或者延迟相近的设备。

**Comment by Anyayay** [comment]
要不可以先考虑本地的播放，获取当前电脑的播放设备应该是一件相当容易的事

**Comment by WXRIW** [comment]
这仍然是复杂的工作，涉及到存储、应用等多方面协调，经过分析，目前无法实现这样的功能需求，也请继续等待后续进展。

**Comment by WXRIW** [comment]
此功能已完成，将随新版本更新，敬请期待！
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/168970ec-358e-4836-b92d-f309483d8a4f)

**Comment by Anyayay** [comment]
感谢！
