### ISSUE TITLE
桌面歌词在桌面不显示

### ISSUE THREAD

**Issue by ddaodan** [WXRIW/Lyricify-App#166]
在窗口前台显示的情况下是正常的，最小化后如果前台是桌面就会不显示，其他情况均正常
不显示的表现为鼠标放在桌面歌词的位置上，锁定状态下只有解锁按钮，解锁状态下什么都不显示
需要的话可以录视频

调了一下设置，关闭全屏隐藏后正常了，怪

**Comment by WXRIW** [comment]
https://github.com/WXRIW/Lyricify-App/blob/main/docs/Lyricify%204/README.md#%E6%A1%8C%E9%9D%A2%E6%AD%8C%E8%AF%8D-%E6%88%96-%E7%81%B5%E5%8A%A8%E8%AF%8D%E5%B2%9B-%E5%BC%82%E5%B8%B8%E6%B6%88%E5%A4%B1
在这里描述了原因和方案
