### ISSUE TITLE
lyrics fullscreen issue

### ISSUE THREAD

**Issue by v3bq** [WXRIW/Lyricify-App#167]
desktop lyrics hidden when there's a fullscreen application running even i turned auto hide off

**Comment by WXRIW** [comment]
@v3bq fullscreen hide is what you are looking for

**Comment by v3bq** [comment]
ah my bad, i meant fullscreen hide. i have it turned off

**Comment by WXRIW** [comment]
@v3bq Please make a screen recording to demonstrate this issue

**Comment by WXRIW** [comment]
I'm closing this issue since there's no updated comments. Be free to reopen this if you have any more questions.
