### ISSUE TITLE
字体设置窗口的列表没有适配触摸滑动上下手势

### ISSUE THREAD

**Issue by SyuueenN** [WXRIW/Lyricify-App#168]
RT

**Comment by WXRIW** [comment]
@SyuueenN wpf的问题，暂不考虑优化。目前可以通过右侧scrollbar来调节

**Comment by WXRIW** [comment]
@SyuueenN 并且本功能使用频率极低，设置好后大概率不会再打开，所以不会花过多精力在上面

**Comment by WXRIW** [comment]
试了一下，其实可以向下滑动来实现下滑，动画还挺好看（（

**Comment by WXRIW** [comment]
已修复，等待新版本更新。感谢反馈！
