### ISSUE TITLE
【Bug】Win 10 任务栏在上方时软件全屏显示异常

### ISSUE THREAD

**Issue by iamalexblue** [WXRIW/Lyricify-App#17]
# 【Bug】Win 10 任务栏在上方时软件全屏显示异常
## 问题描述
Win 10 在任务栏上方的情况下，将 Lyricify 全屏之后，软件显示会异常，具体表现是，上方和任务栏叠在一起，而下方会空出一个任务栏的位置，感觉显示方式还是任务栏在下方时的状态。

## 截图 
![bug-reporting-screenshot](https://user-images.githubusercontent.com/41639269/122510079-88183a80-d037-11eb-9575-b162d2aed55c.png)

**Comment by WXRIW** [comment]
这个 bug 先缓一缓，等有空再修吧。
因为 Windows 11 中限制了任务栏只能在底部。
![image](https://user-images.githubusercontent.com/62491584/123357552-4be75b80-d59c-11eb-8376-f832a8ce5068.png)

**Comment by WXRIW** [comment]
Windows 11 中已经不再支持顶部任务栏，并且 Lyricify 4.0 应该不会出现这种问题，所以此 Issue 关闭。
