### ISSUE TITLE
Apple Music背景占用gpu资源过高

### ISSUE THREAD

**Issue by DBeidachazi** [WXRIW/Lyricify-App#170]
![静态](https://github.com/WXRIW/Lyricify-App/assets/63102882/32d00816-1a50-460a-8953-07b85fc0549f)
![动态跳动](https://github.com/WXRIW/Lyricify-App/assets/63102882/4a50786d-bd8e-4b84-947d-dbc8f9597a75)

**Comment by WXRIW** [comment]
动态背景就是会有相当高的占用，既然你有能带得动的 GPU，为何不用呢
