### ISSUE TITLE
Unauthorized Distribution of Pirated Versions of Our Software

### ISSUE THREAD

**Issue by cryptofyre** [WXRIW/Lyricify-App#171]
I am writing to formally address a critical issue concerning the unauthorized distribution and sharing of cracked versions of our software (Cider) in your telegram channels. It has come to our attention that our proprietary software has been leaked and redistributed in violation of our terms of service and copyright laws. 

We appreciate a diverse array of opinions and perspectives concerning business practices; however, distributing pirated versions of our software is not an acceptable or legal method to express disagreement. Not only does this activity infringe on our intellectual property rights, but it also undermines the community of legitimate users and developers who invest time and resources into utilizing and advancing our products.

We hereby request the immediate removal of any cracked/pirated versions of our software from your telegram channels. Failure to comply with this request may escalate to legal actions to protect our intellectual property rights.

We hope that it does not reach that point and that you will cooperate to resolve this issue promptly. We encourage open discussions on business practices and are more than willing to engage in a dialogue concerning our policies. However, we must insist that these discussions occur within legal and respectful boundaries.

Thank you for your immediate attention to this serious matter.

**Comment by cryptofyre** [comment]
I wanted to take a moment to clarify that our intention is not to create any friction or disturb the peace between us. Our primary goal is to address the concerns surrounding the safety and legality of certain practices mentioned previously.

Having said that, we have noticed the promising aspects of your software and sincerely wish you the best of luck with its development. Innovation and progress in the tech sector are fueled by dedicated and passionate individuals like you, and we look forward to seeing the positive contributions your software may bring to the community.

**Comment by WXRIW** [comment]
I mentioned that a copy of Cider version 2.0.3 was uploaded months ago in Lyricify’s Telegram user group. I have now taken it down. Sorry for any inconvenience.
Looking forward to future updates of Cider 2. Thank you for your continuous support and contributions in the music field.
