### ISSUE TITLE
使灵动词岛在 Apple Music 歌词界面全屏时自动隐藏

### ISSUE THREAD

**Issue by St7530** [WXRIW/Lyricify-App#174]
不同于灵动词岛已有的`全屏隐藏`选项，希望可以再额外增加一个选项，使得灵动词岛仅在 Apple Music 歌词界面全屏时自动隐藏，而运行其他全屏程序时不隐藏。
因为当全屏 Apple Music 歌词时，再显示灵动词岛就会显得很多余。而我在全屏打游戏时又不希望将灵动词岛隐藏，所以希望可以再提供一个选项单独设置。

**Comment by WXRIW** [comment]
可通过临时关闭的方式实现，暂不考虑单独添加该功能。
