### ISSUE TITLE
能用tx的罗马音就不要用罗马音字典转罗马音

### ISSUE THREAD

**Issue by SaharaMiyoko** [WXRIW/Lyricify-App#175]
Lyricify使用版本（不过我下载了绿色版仍然是这样，排除试用版本特供功能）：
<img width="825" alt="屏幕截图 2023-09-22 115418" src="https://github.com/WXRIW/Lyricify-App/assets/104242390/6919aa65-1fa5-4f9a-9fb6-c6bfce135474">
问题描述：如图，lyricify的罗马音与lx的罗马音不一样，并且lyricify的罗马音是错误的，这里的“道標”的假名是"みちしるべ"，不是“どうひょう”然后我去qrcd_m下载了“恋をしたのは”的所有歌词，发现只有“恋をしたのは”专辑有罗马音，“aikoの詩”、“湿った夏の始まり”里的没有罗马音，然而Lyricify上标记的是“恋をしたのは”的歌词，所以可以推测Lyricify的罗马音是用转出来的（不过很早之前的Lyricify显示的罗马音好像是正常的），希望不要啥都强转罗马音（其他日文歌会不会这样我不知道，我主要听欧美和华语）
![图片](https://github.com/WXRIW/Lyricify-App/assets/104242390/9b1246ce-848d-4bd6-8519-5865a25f8094)
![图片](https://github.com/WXRIW/Lyricify-App/assets/104242390/611a29a6-b67d-49ca-a43e-5ae6c91a8fde)

PS:如果这个可以实现的话，给粤语歌加注音理论上也行，lx就支持给粤语歌注音

**Comment by WXRIW** [comment]
首先感谢反馈。就这个问题，给出下列解答：
Lyricify 歌词数据库存储仅保存了歌词及翻译信息，所以必须使用转换来实现罗马音。
虽然保存了歌曲信息，能够做到溯源对应的 QQ 音乐 和 网易云音乐 的歌曲，但是每次请求完歌词后，再次请求 QQ 或 网易云 的接口会造成歌词获取时间延长，大大降低用户体验。
而粤语的话，同理，因为不能通过获取 QQ 音乐 或 网易云音乐 现有的资源来提取罗马音，所以无法实现。

**Comment by SaharaMiyoko** [comment]
那有没有可能将罗马音一起跟歌词信息保存下来？并且之前用4.1.3（或者更早？）似乎没出现这个问题🤔并且在qrcd_m里可以下可以下同时包含歌词与罗马音的歌词，我很好奇歌词与罗马音的歌词是否是分开的，如果不是，那有没有可能直接一次性获取歌词、罗马音和翻译的内容呢？🤔

**Comment by WXRIW** [comment]
Lyricify 4 获取歌词的过程在这里有详细描述：
https://github.com/WXRIW/Lyricify-App/blob/main/docs/Lyricify%204/README.md#lyricify-4-%E8%8E%B7%E5%8F%96%E6%AD%8C%E8%AF%8D%E7%9A%84%E8%BF%87%E7%A8%8B%E8%BF%9B%E9%98%B6

**Comment by SaharaMiyoko** [comment]
所以说就是 not planned 了？🤔那么是否可以像hyplayer一样加一个罗马音获取的可选功能，错误的罗马音的确有点难受

**Comment by WXRIW** [comment]
是的，没有开发计划。
HyPlayer 可以提供选项是因为他的歌词来源很简单，就只有 网易云音乐，通过 ID 就能返回所需的所有数据。
但 Lyricify 的歌词源非常多，从我刚才提供的链接以及文档中的介绍可以知道，Lyricify 的歌词源包括但不限于 Lyricify 私有歌词库、QQ 音乐、网易云音乐、Apple Music、Spotify 歌词（含 Musicmatch）、酷狗音乐等，所以一套不统一的罗马音是很难实现的。其次 Lyricify 4 一开始并没有支持罗马音的计划，在即将发布前的几周，因 日语罗马音 被许多用户提及，所以才加入了支持。
FYI，粤语发音及韩语罗马音均不会提供支持。

**Comment by SaharaMiyoko** [comment]
可是实际上只有 wyy和 tx （我知道lyricify调用酷狗歌词是直接保存在歌词库的算没有罗马音）有罗马音，其他几个歌词源直接转化，然后如果是这两个音源可以根据用户选择决定是否转化还是直接调用（当然，如果真的不行那我就作罢🥲）

**Comment by WXRIW** [comment]
@SaharaMiyoko 在网络较差的环境中，Q音和网易云API的请求等待时间较长，并且实现起来需要较大代码改动，最重要的是我也不听日语，所以没有什么动力去做这个的支持。

**Comment by WXRIW** [comment]
@SaharaMiyoko 还有两个点，一是这种错误本身非常少见，只有极个别的歌词会出现问题，不影响大体体验。二是较长的请求等待时间会在一定程度上影响使用体验。

**Comment by SaharaMiyoko** [comment]
那好吧，可以close了
