### ISSUE TITLE
[歌曲封面不同步]播放B歌曲时候显示A歌曲的封面，C歌曲的时候显示A歌曲封面

### ISSUE THREAD

**Issue by zhou-hack** [WXRIW/Lyricify-App#179]

**Comment by WXRIW** [comment]
你的网不好，更换更好的网络环境即可

**Comment by zhou-hack** [comment]
挂了梯子还是一样，播放C显示的是B，就是歌曲的封面总是落后于当前歌曲一首

> 你的网不好，更换更好的网络环境即可

**Comment by WXRIW** [comment]
换节点，节点不够好也会导致这个问题。
另外你描述的是 Lyricify 4 还是 Lyricify Mobile。

**Comment by zhou-hack** [comment]
> 换节点，节点不够好也会导致这个问题。 另外你描述的是 Lyricify 4 还是 Lyricify Mobile。

Lyricify 4, Apple Music全屏

**Comment by WXRIW** [comment]
主界面封面是否正常切换

**Comment by zhou-hack** [comment]
否

> 主界面封面是否正常切换

**Comment by zhou-hack** [comment]
![image](https://github.com/WXRIW/Lyricify-App/assets/84661666/e63e3212-2916-4e6e-8377-4907c6fe4777)

**Comment by WXRIW** [comment]
那应该就是你的网络问题，尝试更换更好的网络环境。

**Comment by Paul95271** [comment]
必须开代理吗？

**Comment by WXRIW** [comment]
> 必须开代理吗？

https://github.com/WXRIW/Lyricify-App/blob/main/docs/Lyricify%204/README.md#%E6%97%A0%E6%B3%95%E5%8A%A0%E8%BD%BD%E4%B8%93%E8%BE%91%E5%9B%BE%E7%89%87

使用指南写的很清楚了

**Comment by Paul95271** [comment]
你是自动答复吗？好奇问问
________________________________
发件人: XY Wang ***@***.***>
发送时间: 2024年4月20日 11:58
收件人: WXRIW/Lyricify-App ***@***.***>
抄送: Paul95271 ***@***.***>; Comment ***@***.***>
主题: Re: [WXRIW/Lyricify-App] [歌曲封面不同步]播放B歌曲时候显示A歌曲的封面，C歌曲的时候显示A歌曲封面 (Issue #179)


必须开代理吗？

https://github.com/WXRIW/Lyricify-App/blob/main/docs/Lyricify%204/README.md#%E6%97%A0%E6%B3%95%E5%8A%A0%E8%BD%BD%E4%B8%93%E8%BE%91%E5%9B%BE%E7%89%87

使用指南写的很清楚了

―

**Comment by WXRIW** [comment]
> 你是自动答复吗？好奇问问

显然是开发者亲自回复

**Comment by Paul95271** [comment]
lyricify有iOS版本吗

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
