### ISSUE TITLE
**歌曲:** 夜的第七章 这首歌不是纯音乐

### ISSUE THREAD

**Issue by oldg00se** [WXRIW/Lyricify-App#18]
**歌曲:** 夜的第七章
**专辑:** Jay Chou
**曲目编号:** 1
**ID:** 705AesgTkD0JiW74iKb8qS
**ISRC:** TWK970601101
**专辑 ID:** 7satNc3jeX2xJ9tgqrUB9N
**详情:** 这首歌不是纯音乐

**Comment by WXRIW** [comment]
已作删除处理。
**请不要新开Issue，而是在 #4 里提交，谢谢配合！**
