### ISSUE TITLE
歌词翻译的字体粗细跳动问题

### ISSUE THREAD

**Issue by Anyayay** [WXRIW/Lyricify-App#180]
字体粗细（？）会发生跳动

https://github.com/WXRIW/Lyricify-App/assets/37764175/10f15fae-a2b3-41dc-af8d-c937e3f8036d

**Comment by WXRIW** [comment]
视频里不是很明显，请问这个问题是 4.2 才出现，还是一直都有。
可以尝试通过调整缩放解决。

**Comment by Anyayay** [comment]
> 视频里不是很明显，请问这个问题是 4.2 才出现，还是一直都有。 可以尝试通过调整缩放解决。

至少是最近一个月的版本都存在，之前没有注意。
我一般使用笔记本自带屏幕显示（125%缩放），也有跳动，但很不明显。今天用了外接显示屏（100%缩放），跳动很明显

**Comment by Anyayay** [comment]
就是当翻译的字幕跳到正在播放时，字体会突然变细（视频4.5s左右时跳动）

**Comment by Anyayay** [comment]
或者说是字体突然变小了一点

**Comment by WXRIW** [comment]
你的情况我大概了解了。Lyricify 能给出的解决方案是这样的。
在缩放的过程中，若分辨率过低，则会导致这样的渲染错觉出现，解决方案也很简单，使用高分辨率高 PPI 的屏幕，这样能让视觉效果最佳。

**Comment by Anyayay** [comment]
OK ，谢谢。（不过 这个办法可不算“简单”）

**Comment by WXRIW** [comment]
我自己在 100% 缩放的 1080P 屏幕上测试了一下，并没有明显的渲染错误。

**Comment by Anyayay** [comment]
我的环境是在 1080p 的 100%（明显）和 125%（有一点）的两台显示器，系统22H2 & 23H2 CPU：i5-1240p.用都是核显。
软件重装后问题依然存在

要不等几天看看有没有人再反馈

**Comment by Anyayay** [comment]
今天问题突然消失了？！
今天涉及的可能有关操作
1. 更新Microsoft Windows Desktop Runtime至6.0.23.32930
2. Windows11更新至Windows 11 Insider Preview 10.0.22635.2483

**Comment by WXRIW** [comment]
挺奇怪的，有时候就是这么玄学😂
你还记得你之前的 .NET 版本吗。

**Comment by Anyayay** [comment]
> 挺奇怪的，有时候就是这么玄学😂 你还记得你之前的 .NET 版本吗。

不记得了，但我一般都是每周周末集中更新一次，这样看来，之前的可能是6.0.22

**Comment by WXRIW** [comment]
可能是 .NET 的原因，按照你的描述，近一个月有这个情况，正好更新 .NET 后问题消失。
目前工作正常，此 Issue 关闭，后期遇到同样的问题可以接着在这里反馈。
