### ISSUE TITLE
更新 Lyricify 后歌词页面英文字体皆恢复为默认字体

### ISSUE THREAD

**Issue by Takagisannn** [WXRIW/Lyricify-App#181]
操作系统：Windows 11 21H2
Lyricify 版本：目前已更新至最新版本 4.2.0.231001-release ，经过不断尝试，发现回退至 4.1.10.230906-release 版本后字体正常，而在此之后版本的英文字体都不正常

具体表现为：除 Apple Music 歌词和主页显示的英文字体显示默认字体外，Lyricify 全屏、移动端 UI 全屏、桌面歌词、灵动岛字体皆正常。

![1.png](https://github.com/WXRIW/Lyricify-App/assets/143085729/6e55012b-c2d3-42c9-bde7-17d72cdf3adb)

![2.png](https://github.com/WXRIW/Lyricify-App/assets/143085729/1c21a06f-e61a-441a-9417-8643ed15d341)

**Comment by WXRIW** [comment]
主界面你是不是手动修改了字体

**Comment by Takagisannn** [comment]
> 主界面你是不是手动修改了字体

没有，设置里面的字体家族都为默认。不过我自己在系统里安装了苹方字体，应该不是这个导致的吧。

**Comment by WXRIW** [comment]
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/62784586-9e24-4b34-85f5-e20ed81df35a)
这个区域截个图看看。

**Comment by WXRIW** [comment]
你提供的 图2 中的问题是因为你在系统中安装了 SF Pro 字体，但没有安装所有自重。有两种解决方案：
1. 卸载系统中安装的 SF Pro 字体。
2. 补充安装没有安装的 SF Pro 字重，建议在 Apple Developer 官网下载完整字体。

**Comment by Takagisannn** [comment]
> ![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/62784586-9e24-4b34-85f5-e20ed81df35a)
> 这个区域截个图看看。

![3.png](https://github.com/WXRIW/Lyricify-App/assets/143085729/ee3d7bf2-eaf8-4565-8d9b-d4c371003de0)

**Comment by WXRIW** [comment]
这个情况比较奇怪，你可以尝试恢复默认设置。若仍未解决，我们将进一步排查。

**Comment by Takagisannn** [comment]
> 这个情况比较奇怪，你可以尝试恢复默认设置。若仍未解决，我们将进一步排查。

卸载了我自己安装的字体后，显示正常了，非常感谢。

**Comment by WXRIW** [comment]
可否提供一下你自己安装的字体文件，我来检查一下具体是什么原因导致的。

**Comment by Takagisannn** [comment]
> 可否提供一下你自己安装的字体文件，我来检查一下具体是什么原因导致的。

原字体已经删除，是在 https://ghproxy.com/https://github.com/prchann/fonts/archive/refs/heads/main.zip 里面下载的，单独安装了里面的 SF Pro Display Regular 字体，可能确实是因为字重没装全。

**Comment by WXRIW** [comment]
比较奇怪的是你提供的 图1，因为按道理来说，在没有自定义字体的情况下，它会调用内嵌的 Spotify Circular 字体 和 系统中的 微软雅黑 字体。不会受到 PingFang SC 的影响。

**Comment by Takagisannn** [comment]
> 比较奇怪的是你提供的 图1，因为按道理来说，在没有自定义字体的情况下，它会调用内嵌的 Spotify Circular 字体 和 系统中的 微软雅黑 字体。不会受到 PingFang SC 的影响。

确实，卸载了字体后都正常了。
