### ISSUE TITLE
添加一个删除已有歌词源的功能

### ISSUE THREAD

**Issue by Invis1ble5** [WXRIW/Lyricify-App#182]
例如Dan Salvato的Your reality在qq音乐上并无版权，但是有人上传了错误的qq音乐歌词源导致使用qq音乐歌词源优先的用户无法正确对应歌词，希望通过添加个删除歌词源的功能解决
![Snipaste_2023-10-02_12-37-54](https://github.com/WXRIW/Lyricify-App/assets/88815204/a058ed9e-1c91-4211-9c7e-6a63d19a2bf6)
![Snipaste_2023-10-02_12-38-03](https://github.com/WXRIW/Lyricify-App/assets/88815204/5606aef4-f5ed-46ee-865e-726d42ce469b)
![Snipaste_2023-10-02_12-38-15](https://github.com/WXRIW/Lyricify-App/assets/88815204/21eb1e1b-6e29-4f63-a916-af1919907875)
![Snipaste_2023-10-02_12-38-32](https://github.com/WXRIW/Lyricify-App/assets/88815204/0778ba05-2c99-4afe-9c70-5f2bceacc0b6)

**Comment by WXRIW** [comment]
删除功能是仅管理员可用的，这种情况可以联系管理员处理，或者直接在群里反馈。

**Comment by WXRIW** [comment]
关于问题已解释，且长时间无回复，故关闭此 Issue。有需要时可重新开启。
