### ISSUE TITLE
求【Apple Music本地听歌党】可不可以开发一个iOS支持Apple Music本地音乐的滚动歌词，如果可以的话，我万分支持🙏

### ISSUE THREAD

**Issue by succichang** [WXRIW/Lyricify-App#185]
如题，Apple Music上线歌词功能后，只有官方在线歌曲才支持滚动歌词，本地音乐只能内嵌文本歌词，不能滚动。这是使用Apple Music本地听歌的一个痛点，所以求大佬考虑一下可不可以实现这个功能

**Comment by WXRIW** [comment]
我也是 Apple Music 用户，对这个问题很是了解。但是目前无论是时间精力，还是个人能力，都无法满足本功能的开发，也与Lyricify 的开发初心不符（为 Spotify 提供歌词）。

主要难点：
1. 技术层面，单独为 iOS 开发会消耗大量精力，且实现起来非常困难。
2. 应用层面，开发成本高，而实际用户数不会很高，再加上上架困难，安装起来会很麻烦。

解决方案：
暂时改用 Spotify 收听本地音乐，Lyricify Mobile 支持 Spotify 本地音乐的歌词显示。

**Comment by succichang** [comment]
> 我也是 Apple Music 用户，对这个问题很是了解。但是目前无论是时间精力，还是个人能力，都无法满足本功能的开发，也与Lyricify 的开发初心不符（为 Spotify 提供歌词）。
> 
> 主要难点：
> 
> 1. 技术层面，单独为 iOS 开发会消耗大量精力，且实现起来非常困难。
> 2. 应用层面，开发成本高，而实际用户数不会很高，再加上上架困难，安装起来会很麻烦。
> 
> 解决方案： 暂时改用 Spotify 收听本地音乐，Lyricify Mobile 支持 Spotify 本地音乐的歌词显示。

明白了，感谢回复
