### ISSUE TITLE
Apple Music 歌词提供默认右对齐选项

### ISSUE THREAD

**Issue by COMEA-DIVO** [WXRIW/Lyricify-App#187]
建议添加：Apple Music右侧歌词
始终将歌词对齐右侧，对唱时第二位歌手歌词对齐左侧

**Comment by WXRIW** [comment]
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/984d93b8-ca92-44e5-b0e8-185e33081f70)
已完成，将随新版本发布。
设置中可选开启。
