### ISSUE TITLE
灵动词岛建议

### ISSUE THREAD

**Issue by YQCNM** [WXRIW/Lyricify-App#188]
在使用灵动词岛时，在一些歌曲中由于一段时间内可能出现两句不同歌词（如下图），会让灵动词岛出现“忙不过来”导致鬼畜的情况（或者歌词走一半被另一句打断），有些影响观感
![图片](https://github.com/WXRIW/Lyricify-App/assets/75867440/30dc8986-b964-4d68-9d42-23c268cc442a)

**Comment by WXRIW** [comment]
但是目前，打断是唯一的解决方案了。
并且有想法去做一个 子歌词行 的功能，不过由于动画很复杂，所以没有实现。

**Comment by YQCNM** [comment]
好吧 也不是不能用 辛苦了
