### ISSUE TITLE
【建议】添加灵动词岛快捷移动到另一个显示器功能

### ISSUE THREAD

**Issue by PINEAPPLE-2020** [WXRIW/Lyricify-App#189]
如题，用双屏时移动灵动词岛有些麻烦

**Comment by WXRIW** [comment]
@PINEAPPLE-2020 后期会加入

**Comment by WXRIW** [comment]
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/c495c165-f236-4117-82ec-22a5c883e168)
将在近期推出。

**Comment by WXRIW** [comment]
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/dd8c7e5e-16d5-4e22-a7f5-65dfb3056c77)
此功能已完成，将于下一版本推出。
