### ISSUE TITLE
d

### ISSUE THREAD

**Issue by MNLyj** [WXRIW/Lyricify-App#19]
**歌曲:** 蘭亭序
**专辑:** Jay Chou
**曲目编号:** 7
**ID:** 2k3NAOhrpY4DJJlt5XjDKF
**ISRC:** TWK970801507
**专辑 ID:** 6pmapc89HjY4f16ARzrmBB
**详情:** 这首歌不是纯音乐

**Comment by WXRIW** [comment]
已作删除处理。
**请不要新开Issue，而是在 #4 里提交，谢谢配合！**
**请不要新开Issue，而是在 #4 里提交，谢谢配合！**
**请不要新开Issue，而是在 #4 里提交，谢谢配合！**
