### ISSUE TITLE
无法双击播放歌曲，双击后无任何反应

### ISSUE THREAD

**Issue by BlackWoods124** [WXRIW/Lyricify-App#190]
Microsoft Store下载的版本，双击歌曲无反应，只能通过Spotify客户端选歌。
API登录与直接账号登录均无反应，系统Windows 10

**Comment by WXRIW** [comment]
你双击的是哪里的歌，截个图看看。

**Comment by BlackWoods124** [comment]
很奇怪。。正准备截图的时候，双击又可以播放歌曲了，这个会被网络等原因影响吗？

**Comment by WXRIW** [comment]
会有一定影响。

**Comment by WXRIW** [comment]
长时间没有进一步反馈，认为问题已解决，此 Issue 做关闭处理。
