### ISSUE TITLE
Lyricify Mobile for Linux 相关问题

### ISSUE THREAD

**Issue by yeslsl** [WXRIW/Lyricify-App#192]

**Comment by WXRIW** [comment]
@yeslsl 预计于今年或明年初推出 Lyricify Mobile for Linux，提供与Lyricify Mobile 一致的功能。

**Comment by WXRIW** [comment]
经过研究，Lyricify Mobile for Linux 暂时无法实现。原因如下：
1. Lyricify Mobile 基于 Xamarin.Forms 构建。
2. Xamarin.Forms 可通过 Xamarin.GTK 提供 Linux 原生支持。
3. Xamarin.GTK 需要 .NET Framework。
4. Lyricify Mobile、Lyricify Lyrics Helper、Spotify API 使用的是 .NET Standard 2.1。
5. .NET Framework 支持 .NET Standard 2.0，不支持 .NET Standard 2.1。
6. 由 4 和 5 可得，Xamarin.GTK 不支持 Lyricify Mobile 等。
7. 可将 Lyricify Mobile、Lyricify Lyrics Helper、Spotify API 降级至 .NET Standard 2.0。
8. 将多个项目同时降级的成本很高。
9. 由 7 和 8 可得，无法降级。
10. 由 9 可得，Xamarin.GTK 无法支持 Lyricify Mobile。
11. 由 10 可得，Lyricify Mobile for Linux 无法实现构建。

**Comment by WXRIW** [comment]
由于 Xamarin.GTK 的一些问题（详见上方解释），Lyricify Mobile for Linux 短期内无法推出。在迁移至 MAUI 后，可能会重启 Lyricify Mobile for Linux 的开发，敬请期待。

**Comment by WXRIW** [comment]
由于技术原因，短期内无法推出 Lyricify Mobile for Linux，本 Issue 与 #195 合并。
