### ISSUE TITLE
【建议】在其他应用商店发布

### ISSUE THREAD

**Issue by 80927187** [WXRIW/Lyricify-App#193]
购买后由于微软商店的诸多bug和网络原因无法下载软件。多次尝试无果后，只能来这里下载。

**Comment by WXRIW** [comment]
感谢您选择和购买 Lyricify 4。
由于您所遇到的问题此前没有用户反馈过，且 Microsoft Store 一般来说都是可以流畅访问的，如果遇到无法下载的问题，可以尝试联系 Microsoft 支持以获取帮助。  
  
关于您所提到的在其他应用商店发布，目前并没有相关计划，主要有以下一些原因造成。
1. 发布成本更高，每次更新需要在更多商店上传新版本。
2. 维护成本更高，更多应用商店的支持，涉及到更复杂的维护，且第三方应用商店的诸多功能支持起来并不方便。
3. 目前没有发现其他应用商店的选择，只有 Microsoft Store 是所有 Windows 10 或更高版本中预装的商店，其他商店均非 Microsoft 官方。

目前您可以选择在以下多个地址获取新版 Lyricify 4：
1. Microsoft Store (若遇到无法下载的问题，请一定与 Microsoft 支持取得联系)
2. GitHub Releases
3. Telegram 频道
5. QQ 群文件
6. 蓝奏云

再次感谢您的支持和理解。

**Comment by WXRIW** [comment]
已做出回应且长时间没有收到新的回复，此 Issue 做关闭处理。如有进一步疑问，欢迎 Reopen 本 Issue。
