### ISSUE TITLE
曲目管理无法清除已上传的歌词信息

### ISSUE THREAD

**Issue by FlysoftBeta** [WXRIW/Lyricify-App#194]
![图片](https://github.com/WXRIW/Lyricify-App/assets/49718840/61540b4b-d08d-458a-86e4-8676669e201f)
点击搜索并上传后，就无法清除QQ音乐的歌词信息了

**Comment by WXRIW** [comment]
是的，所以一定要确保搜索到的歌词是正确的才上传。这也是在 `Lyricify 4 使用指南` 中强调的。
删除歌词功能，仅管理员可用。这是为了避免用户乱删歌词而设置的。
您可以在群里联系 `歌词管理` 来处理。

**Comment by WXRIW** [comment]
或者，您也可以在 QQ 音乐查找正确的对应歌曲，然后导入并上传即可。

**Comment by FlysoftBeta** [comment]
QQ音乐平台无此曲目，但网易云上有。能否增加一个选项选择使用网易云歌词还是QQ音乐歌词？

**Comment by WXRIW** [comment]
在设置里可以选择优先使用的歌词源。

**Comment by FlysoftBeta** [comment]
可以单独为每个曲目设置吗？

**Comment by WXRIW** [comment]
曲目管理中的所有内容都是面向所有用户的，所以无法进行个性化设置。
这种情况您可以联系 歌词管理 来对错误上传的歌词进行删除处理。

**Comment by FlysoftBeta** [comment]
好的，了解了。

**Comment by FlysoftBeta** [comment]
加群后未找到歌词管理，请问如何联系歌词管理？

**Comment by WXRIW** [comment]
@FlysoftBeta QQ 群头衔为 歌词管理 的群成员是歌词管理。

**Comment by FlysoftBeta** [comment]
> @FlysoftBeta QQ 群头衔为 歌词管理 的群成员是歌词管理。

抱歉，QQNT Windows看不到头衔，我用手机看看
