### ISSUE TITLE
Does Lyricify still work on Linux through Wine?

### ISSUE THREAD

**Issue by IdkWhatToCallMe123** [WXRIW/Lyricify-App#195]
There are multiple (closed) issues with comment stating that this app does work on Linux when using wine.

However when I try the app crashes upon start.

Error log from running the app in the terminal:
[Error log from terminal.txt](https://github.com/WXRIW/Lyricify-App/files/13196017/Error.log.from.terminal.txt)
Error log from the Wine error window:
[Error log from Wine error.txt](https://github.com/WXRIW/Lyricify-App/files/13196018/Error.log.from.Wine.error.txt)

I've tried both the 32bit version and the 64bit version

Wine version: Soda-7.0-9

Other system info:
![Screenshot from 2023-10-28 16-27-10](https://github.com/WXRIW/Lyricify-App/assets/74187631/3f7ed538-e8b1-4f8d-ac7b-fe7d0c10f7a8)

**Comment by clover-yan** [comment]
I hope someone who runs Lyricify in Wine correctly can write a tutorial, which might be helpful.

**Comment by WXRIW** [comment]
Thank you for trying out Lyricify on Wine. Running Lyricify 3 on Wine is pretty simple. But getting Lyricify 4 running on Wine is kind of tough. One of the users have reported Lyricify 4 running on Wine successfully. Here are some screenshots.
![79395e3ca63739933bf7e2b90b39fac7](https://github.com/WXRIW/Lyricify-App/assets/62491584/0339771d-4f58-4be7-ba9f-aa83fe50ffcb)
![e03158b84a33b00a408ca1f60417a4c5](https://github.com/WXRIW/Lyricify-App/assets/62491584/edc0062b-b1b3-431b-b4f9-37caac131866)
I'm not a Linux user so I don't know much about Linux or Wine. Thanks for your understanding. I'll try to contact that user who have succeed. He might reply on this issue later.
Make sure you have installed .NET Desktop Runtime 6.0 or using self-contained version of Lyricify 4.

**Comment by IdkWhatToCallMe123** [comment]
Both the self-contained version of Lyricify 4 or Lyricify 3 does not work, with both throwing up the same error as in my attached logs :/

Btw 
if the person who got Lyricify running successfully on Linux used the [Bottles](https://usebottles.com/) app, it would be greatly apprecieated if that person could export the configuration as a .YML file and publish it.

**Comment by fred913** [comment]
Sorry for getting back to you late. I've been under the weather with the flu and feeling pretty drained. On the bright side, I managed to get Lyricify 4 up and running on my Kubuntu 22.04 setup. Big thanks for introducing me to Bottles. It looks like a solid way to keep my Wine environment consistent. I'm gonna go ahead and try installing a new version of Lyricify using Bottles.

**Comment by fred913** [comment]
Sorry for getting back to you late. I've been under the weather with the flu and feeling pretty drained. On the bright side, I managed to get Lyricify 4 up and running on my Kubuntu 22.04 setup. Big thanks for introducing Bottles. It looks like a solid way to reproduce Wine environment same as mine. I'm gonna go ahead and try installing a new version of Lyricify using Bottles.

**Comment by scgm0** [comment]
> Sorry for getting back to you late. I've been under the weather with the flu and feeling pretty drained. On the bright side, I managed to get Lyricify 4 up and running on my Kubuntu 22.04 setup. Big thanks for introducing Bottles. It looks like a solid way to reproduce Wine environment same as mine. I'm gonna go ahead and try installing a new version of Lyricify using Bottles.

How's it going?

**Comment by fred913** [comment]
Hey guys,

I'm glad to announce that after months of testing, Lyricify now **unofficially** supports Linux (through Wine). 

It's now available on Spark Store (which mainly targets Chinese users), whose official website is located in [spark-app.store](https://spark-app.store).

Considering of the inconvenience for foreigners to download & use, we're discussing about ways to publish those packages. It won't take too long. 
Thanks for your support. 

Sincerely,
Sheng Fan

**Comment by clover-yan** [comment]
It is perfect! Here are some screenshots.

![图片](https://github.com/WXRIW/Lyricify-App/assets/56215525/2141f393-a40d-4ee3-bc1b-d4a9e6ca0743)
![图片](https://github.com/WXRIW/Lyricify-App/assets/56215525/98dcf36c-a623-4df7-98d0-3a2b49e9b1f4)

Installation is easy. Install Spark Store, search and install Lyricify then run, everything will be working as it should be. The whole app and `deepin-wine` runtime takes up about 4 GB space on disk.

**Comment by fred913** [comment]
*NOTE*: According to shenmo, the main developer of the Spark Store, the searching feature appears to be unstable. If it shows empty please give it other shots.

**Comment by WXRIW** [comment]
Later, new Linux compatible releases will be [here](https://github.com/Lyricify/Lyricify-on-Wine). This issue is now being closed. Thanks to @fred913 for Linux packaging.
