### ISSUE TITLE
自定义api的问题

### ISSUE THREAD

**Issue by Huuuula** [WXRIW/Lyricify-App#196]
自定义api client之后点击继续
网页提示INVALID_CLIENT: Invalid redirect URI

**Comment by WXRIW** [comment]
检查你输入的 URI。这种情况是你填写的 URI 错了导致的。
仔细看看教程中的 Redirect URI。

**Comment by WXRIW** [comment]
长时间没有回复，认为问题解决，本 Issue 做关闭处理。
