### ISSUE TITLE
关于灵动词岛掉帧的问题

### ISSUE THREAD

**Issue by ZekromLi** [WXRIW/Lyricify-App#197]
如题，每次感觉掉帧的地方在切换歌词时灵动岛缩短然后拉长的过程时候会有卡顿，我现在用的是微软商店的最新版本。希望能解决一下，谢

**Comment by WXRIW** [comment]
感谢您对 Lyricify 4 的支持。
请提供一下这些信息，以供进一步分析使用。
- 播放的歌词语种
- 系统版本
- 设备配置，包括 CPU，内存，GPU；如果是独显，是否将独显分配给了 Lyricify
- 屏幕缩放比及屏幕分辨率

**Comment by ZekromLi** [comment]
语种：英语（带有翻译的那种）
系统版本：Windows 11 家庭版 23H2
设备配置：i7-12700H RTX 3060（laptop），但是我不知道怎么将独显分给lyricify
屏幕缩放：150% 屏幕分辨率：2560x1600
话说如果让lyricify用独显的话是不是会流畅很多

**Comment by ZekromLi** [comment]
我后面把lyricify给独显跑了，效果好了很多，但是每次切换歌词的时候，灵动岛从缩短到拉长的中途还是有一点卡顿

**Comment by WXRIW** [comment]
试试把翻译关掉，看会不会掉帧。

**Comment by ZekromLi** [comment]
关闭翻译后效果好多了，也更灵动了，问题已解决

**Comment by WXRIW** [comment]
可以执行以下这个优化，这样开启翻译也不会卡顿。
https://github.com/WXRIW/Lyricify-App/blob/main/docs/Lyricify%204/README.md#apple-music-%E6%AD%8C%E8%AF%8D%E6%B5%81%E7%95%85%E5%BA%A6%E4%BC%98%E5%8C%96
