### ISSUE TITLE
歌词翻译错位

### ISSUE THREAD

**Issue by Ayx03** [WXRIW/Lyricify-App#198]
spotify:track:6UnOxNp0jZfFXyKcAtJwUj
https://open.spotify.com/track/6UnOxNp0jZfFXyKcAtJwUj
歌词来自网易云音乐 https://music.163.com/#/song?id=1911414664
![](https://github.com/WXRIW/Lyricify-App/assets/75155322/51c7263e-07ec-4d53-a604-8d3b250d6a95)

**Comment by WXRIW** [comment]
经检查，确实是网易云提供的歌词本身有问题。您可以与网易云音乐反馈（在网易云音乐客户端里有反馈入口），在网易云音乐纠正后，Lyricify 也会恢复正常。在修复之前，请不要将本歌词在 Lyricify 上标记。
