### ISSUE TITLE
灵动词岛字体大小可以自定义吗

### ISSUE THREAD

**Issue by silora** [WXRIW/Lyricify-App#199]
如题，感觉灵动词岛占的区域有点大了，有没有调整字体大小或者词岛大小的办法呢~~🐱

**Comment by WXRIW** [comment]
@silora 目前没有，但是后期在发布 Lyricify Lite 后，大概率会加入自定义大小功能。尽情期待！

**Comment by silora** [comment]
> @silora 目前没有，但是后期在发布 Lyricify Lite 后，大概率会加入自定义大小功能。尽情期待！

🙌感谢！！期待一波

**Comment by wanyun-yang-2002** [comment]
> @silora 目前没有，但是后期在发布 Lyricify Lite 后，大概率会加入自定义大小功能。尽情期待！

请问 Lyricify Lite 会支持apple music吗

**Comment by WXRIW** [comment]
> > @silora 目前没有，但是后期在发布 Lyricify Lite 后，大概率会加入自定义大小功能。尽情期待！
> 
> 
> 
> 请问 Lyricify Lite 会支持apple music吗

会支持 Apple Music Windows，但因为其提供的时间轴有问题，所以体验会较一般。

**Comment by wanyun-yang-2002** [comment]
> > > @silora 目前没有，但是后期在发布 Lyricify Lite 后，大概率会加入自定义大小功能。尽情期待！
> > 
> > 
> > 请问 Lyricify Lite 会支持apple music吗
> 
> 会支持 Apple Music Windows，但因为其提供的时间轴有问题，所以体验会较一般。

好的谢谢！

**Comment by lovelylion-jojo** [comment]
希望每处显示歌词的地方都能调整字体，目前修改了配置文件中的3处字体设置，但是只有桌面歌词的字体发生了变化

**Comment by WXRIW** [comment]
> 希望每处显示歌词的地方都能调整字体，目前修改了配置文件中的3处字体设置，但是只有桌面歌词的字体发生了变化

只有歌词界面，桌面歌词，Lyricify全屏这三个模式支持自定义字体。其他界面目前没有计划。

**Comment by lovelylion-jojo** [comment]
> > 希望每处显示歌词的地方都能调整字体，目前修改了配置文件中的3处字体设置，但是只有桌面歌词的字体发生了变化
> 
> 只有歌词界面，桌面歌词，Lyricify全屏这三个模式支持自定义字体。其他界面目前没有计划。

那请问是否可以通过修改系统默认字体达到修改其他歌词字体的效果呢？

**Comment by WXRIW** [comment]
> > > 希望每处显示歌词的地方都能调整字体，目前修改了配置文件中的3处字体设置，但是只有桌面歌词的字体发生了变化
> 
> > 
> 
> > 只有歌词界面，桌面歌词，Lyricify全屏这三个模式支持自定义字体。其他界面目前没有计划。
> 
> 
> 
> 那请问是否可以通过修改系统默认字体达到修改其他歌词字体的效果呢？

不支持，其他歌词界面的字体都是预设写好的。

**Comment by Ruikoto** [comment]
同需要调整大小，上班的时候灵动词岛太大了，隔老远都能看到

**Comment by WXRIW** [comment]
已添加本功能，将随新版更新，敬请期待！
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/0c2bc957-dd45-4a89-9454-f8eb22d14c68)
