### ISSUE TITLE
使用 Ctrl - 缩小界面之后，头像菜单会跑到关闭／最大／最小化按钮下面

### ISSUE THREAD

**Issue by clover-yan** [WXRIW/Lyricify-App#201]

**Comment by WXRIW** [comment]
复现了该问题，但是短期内不提供修复或另类解决方案。这种情况非常极端，正常缩放下是不会出现的。

**Comment by WXRIW** [comment]
想了很长时间，发现这个问题在目前的架构下解决起来非常困难，所以暂不提供修复，此 Issue 暂时关闭，后期会考虑修复。
