### ISSUE TITLE
在linux下的支持

### ISSUE THREAD

**Issue by KRBUG-Lee** [WXRIW/Lyricify-App#203]
请问是否有计划开发linux的桌面版本？
或者
是否已经确认在wine的proton环境下是否可用？

感谢您的尽快回复

**Comment by KRBUG-Lee** [comment]
当前存在的问题是wine安装进度条在100%卡顿，
![image](https://github.com/WXRIW/Lyricify-App/assets/62648255/7e2a99fd-04c8-478e-bc98-adcfed53f782)

**Comment by WXRIW** [comment]
中短期内是没有专门开发 Linux 版本 (Lyricify for Linux) 的计划，主要原因如下：
1. 用户过少
2. 开发成本高
3. 暂无开发环境

曾经有计划开发 Lyricify Mobile for Linux，但因为 Xamarin.GTK 的一些问题无法实现，详见 #192。
Lyricify 4 是能在 Wine 上运行的，有用户成功尝试过，这里有一些[运行截图](https://github.com/WXRIW/Lyricify-App/issues/195#issuecomment-1783841553)。
我不是 Linux 用户，对 Linux 不是很了解，所以无法协助解决有关通过 Wine 实现 Lyricify 运行的问题，敬请谅解。

**Comment by WXRIW** [comment]
#192 #195 均为 Linux 相关问题，本 Issue 关闭。
