### ISSUE TITLE
在 matebook e go 上歌词动画掉帧

### ISSUE THREAD

**Issue by awarson2233** [WXRIW/Lyricify-App#204]
已更新至高通官网最新驱动，插电使用
使用apple music歌词界面时，歌词切换至下一句时出现掉帧

**Comment by WXRIW** [comment]
Matebook E Go 是否插电不影响性能发挥，主要原因是 ARM 处理器性能并不强。
可以根据这些教程进行优化：https://github.com/WXRIW/Lyricify-App/blob/main/docs/Lyricify%204/README.md#apple-music-%E6%AD%8C%E8%AF%8D%E7%95%8C%E9%9D%A2%E5%8D%A1%E9%A1%BF%E9%97%AE%E9%A2%98

**Comment by WXRIW** [comment]
你的设备具体是哪款 E Go，E Go 一共有三个版本。

**Comment by WXRIW** [comment]
长时间没有回应，此 Issue 关闭。如有问题可重新开启。
