### ISSUE TITLE
The SSL connection could not be established, see inner exception

### ISSUE THREAD

**Issue by SCPf-166** [WXRIW/Lyricify-App#206]
不知道是我个人问题还是什么的，最近打开软件，显示更新的时候就会跳出来 “The SSL connection could not be established, see inner exception” 报错，但是软件本身在报错弹窗之下还在正常加载，不清楚是什么原因
![image](https://github.com/WXRIW/Lyricify-App/assets/97646865/6b5fc499-5e46-4716-a4cc-260736d2e818)

**Comment by WXRIW** [comment]
这个是 Lyricify 更新模块在尝试更新的过程中失败的报错提示。这种情况基本是因为网络不通畅或有问题导致的。简体中文默认使用的更新源是 GitHub 代理，如果您的网络可以流畅访问 GitHub，则可以尝试在设置中将 更新-更新来源 更改为 GitHub；如果您没有使用科学上网工具，可尝试开启。
另外一个解决方案是使用微软商店版，更新由微软负责，就不会出现这种报错提示了。

**Comment by WXRIW** [comment]
长时间没有回复，且已给出解决方案，认为已经解决，此 Issue 关闭。
