### ISSUE TITLE
这个自定义api太抽象了

### ISSUE THREAD

**Issue by SaharaMiyoko** [WXRIW/Lyricify-App#207]
如图，无言以对
![屏幕截图 2023-11-25 081755](https://github.com/WXRIW/Lyricify-App/assets/104242390/59c80d12-d126-438c-af2d-5a101170eadd)

**Comment by WXRIW** [comment]
不懂

**Comment by WXRIW** [comment]
这有任何问题吗

**Comment by WXRIW** [comment]
文档里没写吗
