### ISSUE TITLE
软件显示无正在播放歌曲

### ISSUE THREAD

**Issue by zzyc** [WXRIW/Lyricify-App#21]
我用的播放器是YesPlay 
[](url)
![Snipaste_2021-07-22_15-34-23](https://user-images.githubusercontent.com/32919368/126605029-6ca547de-cfb7-432f-a7f3-fd6402ffc145.png)

**Comment by WXRIW** [comment]
两个问题：
1. 打开的时候有没有提示无法连接到服务器？
2. 是否用Spotify登录了Lyricify？

**Comment by zzyc** [comment]
第一个问题：没有提示
第二个问题：登陆了









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WXRIW/Lyricify-App"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月22日(星期四) 下午3:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WXRIW/Lyricify-App] 软件显示无正在播放歌曲 (#21)





 
两个问题：
  
打开的时候有没有提示无法连接到服务器？
 
是否用Spotify登录了Lyricify？

**Comment by WXRIW** [comment]
有两个方案：
1. 退出登录，然后在菜单-->获取-->网易云音乐。
2. 不用退出登录，但是需要带参数启动 `-g 2` ，如果不知道带参数启动是什么意思可以在网上找到。
感谢对 Lyricify 的支持！

**Comment by zzyc** [comment]
好的 解决了 感谢您&nbsp;
另外 想请问一下 有没有粉丝群




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WXRIW/Lyricify-App"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月22日(星期四) 下午3:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WXRIW/Lyricify-App] 软件显示无正在播放歌曲 (#21)





 
有两个方案：
  
退出登录，然后在菜单--&gt;获取--&gt;网易云音乐。
 
不用退出登录，但是需要带参数启动 -g 2 ，如果不知道带参数启动是什么意思可以在网上找到。
 感谢对 Lyricify 的支持！

**Comment by WXRIW** [comment]
Readme里写了的呢 :)  
**Telegram Group / Telegram 群:**  
https://t.me/lyricify
