### ISSUE TITLE
不允许开启多个应用程序实例

### ISSUE THREAD

**Issue by sygiegiehs** [WXRIW/Lyricify-App#210]
如果在短时间内多次点击软件图标，会打开多个 Lyricify 实例，由此会造成过多的无用 API 请求。希望可以做一步优化，不允许开启多个实例，或者自动结束多余的实例进程。

**Comment by sygiegiehs** [comment]
大多数软件（如 Spotify）在多次点击后都不会开启多个应用程序实例，所以我认为应该是有更好的解决方案的。
因为设备是触摸大屏，在 Windows 上点击图标常常不能准确命中，所以会习惯多点几次。

**Comment by WXRIW** [comment]
Lyricify 与他们大概率采用的是一样的方案，即 Mutex。但为了避免部分情况下无法启动 Lyricify 的情况（如 Lyricify 已运行但因异常没有正常打开窗口），我加上了窗口判断模块，也就是说必须检测到有窗口才认为有实例，这就造成了在性能较低的设备上启动时有概率出现你所描述的问题。
后期我将进一步优化本问题，预计于 4.3.0 前解决，敬请期待。

**Comment by WXRIW** [comment]
已修复，等待新版本更新。
