### ISSUE TITLE
[仅针对部分歌曲出现的bug]移动进度条后Lyricify播放位置不更新

### ISSUE THREAD

**Issue by mistries** [WXRIW/Lyricify-App#211]
和[#116 ](https://github.com/WXRIW/Lyricify-App/issues/116)比较相似，但只有部分歌曲出现此bug。
重现步骤：
1. 在Spotify或Lyricify 4拖动进度条或者在歌词界面点击单句歌词
2. 在Lyricify进行如上操作后Spotify所播放的歌曲能跳转到正确的位置，但Lyricify的歌词位置和进度条不会更新，如图所示：
![image](https://github.com/WXRIW/Lyricify-App/assets/44749121/9933c9a5-c0d2-4d37-bf25-4af4da98d85c)
3. 尝试多次重启电脑、Spotify以及Lyricify，依旧出现了同样的问题
4. 在Lyricify点击刷新Spotify播放信息也不能更新歌词的位置
5. 只对单首歌曲进行操作时会出现这样的问题，跳转上/下一首时歌词能被正确地更新

我的环境：
* Spotify Premium
* Lyricify for Spotify Ver 4.2.4.231201-release
* 已设置自定义API
* Media Session已连接
* 与Lyricify服务器的连接正常
* 能够访问外网

**Comment by WXRIW** [comment]
我最近也有遇到这种情况，经过我的排除发现是 Spotify 的 SMTC 出了问题，Spotify 的 SMTC 本来就接的烂，现在越改越烂，只能等 Spotify 自己去修复了。

**Comment by WXRIW** [comment]
https://github.com/DubyaDude/WindowsMediaController/releases/download/2.52/Sample.CMD.zip
可以下载这个看一下你那儿是不是也是 GSMTC 出了问题。
下载后运行 Sample.CMD.exe，然后你调整进度后，如果没有立即显示出新的信息，就说明是 Spotify 没有及时更新和通知（也就是我刚描述的情况）。

**Comment by mistries** [comment]
拖动进度条后通知是即时的
[15:15:14.474] SpotifyAB.SpotifyMusic_zpdnekdrzrea0!Spotify timeline is now 00:01:58.1770000/00:05:21.0800000
[15:15:15.717] SpotifyAB.SpotifyMusic_zpdnekdrzrea0!Spotify timeline is now 00:00:03.6520000/00:05:21.0800000

**Comment by WXRIW** [comment]
刚才仔细看了一下你的截图，我怀疑跟你的 Spotify 语言也有关，你可以把你的 Spotify 语言和 Lyricify 语言调成一致再试试看，确保 Spotify 显示的 曲目名 和 艺人名 与 Lyricify 完全一致。

**Comment by WXRIW** [comment]
我刚才特意注册了一个日区账号进行测试，发现区域并不会影响语言，如下图所示：
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/4d443172-f26f-4bc7-b31a-e682542d3356)
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/71f79858-4417-46ae-84fc-b556ec1878db)
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/38942771-d0ec-4639-a2c3-3f75b792e4fa)
你可以尝试重新安装 Spotify 或清除全部 Spotify 缓存，这样应该就会加载正确设置的语言了。
