### ISSUE TITLE
建议增加spotify歌词作为默认的选项

### ISSUE THREAD

**Issue by shangji666** [WXRIW/Lyricify-App#212]
很多情况下spotify中的歌在网易和QQ音乐中只有歌名和作者，但这种情况会被本软件识别为存在歌词。在这种情况下使用者需要手动进入软件切换到spotify源。
Spotify中有完整的带时间轴的歌词，只是没有翻译。因此我建议增加一个选项，当spotify中有歌词时使用spotify的，只有当QQ音乐或网易云有翻译时才切换到它们的歌词。这样能很好地规避“虚假歌词”的情况。

**Comment by WXRIW** [comment]
我也一直有将 Spotify 加入歌词来源的想法，但是这个想法目前来看无法实现。虽然 Lyricify 有能力获取 Spotify 的歌词，但是这是通过 Lyricify 服务器上提前准备的 Spotify 账号来获取的，一旦开放自动使用 Spotify 歌词选项，请求的频繁将导致此方法失效，故无法提供。
与此同时，你反馈了有关部分歌曲的 QQ 音乐和网易云音乐提供的歌词只有曲目名和艺人名，能否提供几对这样的案例以供 Lyricify 后期优化使用？

**Comment by WXRIW** [comment]
长时间没有反馈，本 Issue 关闭，问题已解决。
