### ISSUE TITLE
[已解决]无法登录到 Spotify，443 错误

### ISSUE THREAD

**Issue by morninghut** [WXRIW/Lyricify-App#218]
**UPDATE：是 accounts.spotify.com 挂掉了**

* 在使用最新版本的 exe 文件配置 Lyricify 时遇到关于 Spotify 网页的 443 错误。
* 在这之前 Lyricify 的自动更新时也遇到了 ghproxy 的 443 错误。
* 使用最新版本的 self-contained 安装时发生了闪退问题。[可能的崩溃文件](https://gist.github.com/morninghut/b418d7050c532281576b68dbc26c82e7)

<img width="337" alt="spotify-net-err" src="https://github.com/WXRIW/Lyricify-App/assets/87119882/b9d02eba-e4fd-402a-994a-ef680372fe2f">

## 环境

* Windows 11
* 最新版本 Lyricify (v4.2.6)
* Firefox 122.0a1 (2023-12-15) (64-bit)
* 有系统设置中配置的 http 代理

## 我做了哪些尝试

* 在自动更新失败（报错 ghproxy 443 错误）后，我卸载了旧的 self-contained 版本，删除了配置文件。重新下载了最新的 self-contained 版本安装。但在 spotify 授权时，浏览器已经显示授权成功的界面，并得到了 callback url，但 Lyricify 依旧等待 callback。
* 我尝试手动输入 callback url，等待一分钟后得到了 spotify 443 错误（如上图）
* 我卸载掉 self-contained 版本，重新通过 exe 安装。得到了一样的报错（spotify 443）
* 尝试关掉系统代理，但连浏览器的 spotify 网页都打不开了QAQ

我不确定该做什么。但似乎这是我的网络问题？感激并期待您的任何建议。

~~祝四六级顺利❤~~

**Comment by morninghut** [comment]
UPDATE：似乎是 Spotify 的登录出现了问题，与 Lyricify 无关
src：https://downforeveryoneorjustme.com/spotify

为方便其他人查找到这个问题，暂时保持这个 issue 开放，待问题修复后会 close

**Comment by WXRIW** [comment]
虽然已经解决了，但我还是来回复一下，这个 Issue 写的非常好👍
也感谢你对 Lyricify 的支持！

**Comment by Cool-Xiaolulu** [comment]
问一下是怎么解决的
和贴主使用的相同方法但是没解决

**Comment by WXRIW** [comment]
@Cool-Xiaolulu 参考 #247 #248
