### ISSUE TITLE
希望出个基于此的本地播放器（完全离线）

### ISSUE THREAD

**Issue by luckylemonade24** [WXRIW/Lyricify-App#219]
如果能做个本地音乐播放器就好了，歌词界面动画效果其他的根本没法比，musicplayer2或许界面也不差，但是渲染效率太低，只有几帧，用这个必须用流媒体，可是有时流媒体并不能满足我的需求，我相信除了我还有很多人都有这个想法，

**Comment by WXRIW** [comment]
这是一个很好的提议，之前也有用户提出过，但是这是一个无法实现的功能，无论是在功能层面（本地音频的歌词获取与存储会比较麻烦）还是理论层面（与 Lyricify 精神和初衷不符合）都无法实现，所以本 Issue 做关闭处理，感谢支持！
