### ISSUE TITLE
建议增加Linux支持

### ISSUE THREAD

**Issue by FunnyAWM** [WXRIW/Lyricify-App#22]
我感觉应该不难（目测GTK写个GUI+Windows的一部分代码？）

**Comment by WXRIW** [comment]
这个实现起来很难，Lyricify 是用 C# + Xaml 开发的，我也曾经找过 WPF 应用在 Linux 上运行的相关资料，也进行过尝试，但都以失败告终。如果您有能力的话可以帮助我完成 Lyricify 对于 Linux 的支持！

**Comment by WXRIW** [comment]
很多优美的动画效果在 WPF 上实现已经有难度了，在 GTK 上实现就更困难了。还有一些 Blur 和 Transparency 是不太好实现的。
