### ISSUE TITLE
Is there a possibility to add Musixmatch lyrics on the app?

### ISSUE THREAD

**Issue by notNSANE** [WXRIW/Lyricify-App#220]
So, I like somewhat obscure artists that might not release their music + lyrics on China, I'm not sure how that works.

But for example, I have lyrics support for this artist (Einar Solberg) on official Spotify: https://open.spotify.com/album/25jWll9IwvwbKSChqKmMdG?si=A1_eHOHsSe2EWHPbx6DK-A

For reference, the entire album has lyrics but two tracks aren't synced. 

But there are no lyrics on Lyricify, I guess because the music needs to be on QQ Music and the other service.

Can something be done about this?

**Comment by WXRIW** [comment]
Yes, I was working on adding Musixmatch as additional source. It should be out in coming months, please be patient and thank you for your support on Lyricify!

**Comment by notNSANE** [comment]
awww, thank you so much!
