### ISSUE TITLE
弹出错误弹窗

### ISSUE THREAD

**Issue by RetroFuturism7** [WXRIW/Lyricify-App#223]
![image](https://github.com/WXRIW/Lyricify-App/assets/127582048/59fc146c-b5e2-4ffe-b194-f4a29e262139)
不知道怎么解决

**Comment by RetroFuturism7** [comment]
就是这么多了呀 
一开始打开软件好像是正常的， 歌词也可以显示 ， 然后好像是想更新，  过了几秒就弹这个了
![image](https://github.com/WXRIW/Lyricify-App/assets/127582048/055abaa8-d211-431d-9eca-c357056906f0)
![image](https://github.com/WXRIW/Lyricify-App/assets/127582048/3a25cd7a-bad6-4696-adaa-3f6b8f4933da)

**Comment by WXRIW** [comment]
你最后这张截图才是完整的，不然我怎么猜是什么情况弹出来的呢。并且要有文字说明，我不会猜谜。

**Comment by WXRIW** [comment]
这个问题是因为网络不好，导致无法自动更新，建议在设置里调整自动更新源，或者直接使用[微软商店](https://apps.microsoft.com/store/detail/9P4WB75RHWCH?launch=true&mode=full)版本（推荐）

**Comment by RetroFuturism7** [comment]
我的我的哈哈

**Comment by RetroFuturism7** [comment]
ok了，之前是github代理的话挂梯子也不行的嘛

**Comment by WXRIW** [comment]
有时候梯子对 GitHub 代理的支持不好，改成 GitHub 直连反而更好，但还是更建议微软商店，它是由微软负责更新，不会出现这种情况。
