### ISSUE TITLE
Lyricify 3.8.6 报毒：BestaFera

### ISSUE THREAD

**Issue by M-10777** [WXRIW/Lyricify-App#224]
卡巴斯基报毒如下：
> 组件: 文件反病毒
> 结果说明: 未处理
> 类型: 木马
> 名称: HEUR:Trojan-Banker.Win32.BestaFera.gen
> 精确度: 启发式分析
> 威胁级别: 高
> 对象类型: 文件
> 对象名称: Lyricify.Setup.Ver.3.8.6-release.exe
> MD5: 48745A8FB366D6643FDC80DBC3F231FD

VirusTotal:
> 5 security vendors and no sandboxes flagged this file as malicious
![image](https://github.com/WXRIW/Lyricify-App/assets/98745617/0cf491ab-8530-495e-be27-9bcfa0bfb139)

能否说明报毒的可能原因？

**Comment by WXRIW** [comment]
卡巴斯基太喜欢误报了，但是用户不是最多的，所以我没有去上报。Microsoft Defender 对于 Lyricify 3 也会报毒，故每个版本我会向微软上报，以避免误报。
你这个情况解决方案有两个：
1. 添加信任。
2. 向卡巴斯基上报误报信息，以纠正错误。

**Comment by M-10777** [comment]
已在opentip.kaspersky.com上报，谢谢！
