### ISSUE TITLE
Lyricify Mobile显示逐音节歌词

### ISSUE THREAD

**Issue by St7530** [WXRIW/Lyricify-App#225]
从 Lyricify Mobile 发布至今，一直都没有加入逐音节歌词功能。是否有其他的考量？希望能够在 Mobile 版本也看到逐音节歌词。

**Comment by WXRIW** [comment]
不考虑此功能，Spotify API 提供的时间轴精度不够逐音节歌词使用，只会让观感更差。
目前只能提供以下解决方案: https://github.com/WXRIW/Lyricify-App/blob/main/docs/Lyricify%20Mobile/README.md#%E6%B2%A1%E6%9C%89%E9%80%90%E5%AD%97%E6%AD%8C%E8%AF%8D
