### ISSUE TITLE
本地文件管理器能否导入本地音乐文件的元数据

### ISSUE THREAD

**Issue by Seayay** [WXRIW/Lyricify-App#226]
rt，希望可以直接导入有封面的音频文件的图片
![image](https://github.com/WXRIW/Lyricify-App/assets/92374733/6d4006b9-6e36-4dc4-9004-881e2e77af3b)

**Comment by WXRIW** [comment]
很好的提议，我会去研究研究。

**Comment by WXRIW** [comment]
已添加本功能，将随新版本发布。
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/a5f5220d-c238-4ba1-9b9a-f34194e75b41)
将支持自动从音频文件的 Tag 中提取图片。
