### ISSUE TITLE
加入一个AM歌词渲染精度的功能 提高4k高dpi全屏AM歌词环境下的FPS

### ISSUE THREAD

**Issue by Redappleyyds** [WXRIW/Lyricify-App#227]
就比如加入1x 0.75x 0.5x 0.25x之类的分辨率倍数
就比如各种游戏的渲染精度
让显卡的负担降低一些

**Comment by WXRIW** [comment]
@Redappleyyds WPF 做不到，这跟游戏的渲染是不一样的。

**Comment by WXRIW** [comment]
2. 如果您使用的是高分屏 (缩放比大于 100%)，则可以尝试通过下方设置来改善：
   1. 右击 Lyricify 程序快捷方式，点击属性。
   2. 转到 `兼容性` 标签页。
   3. 如果您是 Windows 8.1 或更早版本的系统，请选中 `高 DPI 设置时禁用显示缩放`。
   4. 如果您是 Windows 10 或更新版本的系统，请点击 `更改高 DPI 设置` 按钮，在弹出的窗口中选中 `替代高 DPI 缩放行为`，并将 `缩放执行` 复选框选为 `系统`。
   
   该方法会降低清晰度，但是可以提高性能。（提升效果明显）

你可以按照使用说明里的提示操作

**Comment by WXRIW** [comment]
https://github.com/Blinue/Magpie
这个 App 可以近似做到你所需要的效果，可以看一下，这是一个不错的解决方案。

因为标题中提到的功能无法加入，所以 Issue 关闭。
