### ISSUE TITLE
允许非管理员用户在曲目管理中「加载所有歌词」

### ISSUE THREAD

**Issue by clover-yan** [WXRIW/Lyricify-App#228]
## 需求场景
有时仍然需要查阅所有歌词，以便于确认对唱视图的状态或进行查看时间轴等操作。

**Comment by WXRIW** [comment]
此功能经过慎重考虑，实现起来较麻烦。
后期会通过在 搜索 - 歌词 页面中添加查看歌词支持来解决本问题。
