### ISSUE TITLE
灵动词岛显示版权所有未经许可

### ISSUE THREAD

**Issue by ironyhex** [WXRIW/Lyricify-App#231]
![image](https://github.com/WXRIW/Lyricify-App/assets/39857711/a3044d64-bcba-4910-b9a7-e9003ffd8c16)

**Comment by WXRIW** [comment]
提供曲目链接方便排查

**Comment by ironyhex** [comment]
> 提供曲目链接方便排查
现已无法复现，可能为偶发性故障。曲目链接 https://open.spotify.com/track/7pZYb3XtZ0wMtORwnVY9SE

**Comment by WXRIW** [comment]
那应该只是卡了，看着也像是出了小问题，后期会优化，本 Issue 做关闭处理。
