### ISSUE TITLE
Lyricify seems to be making my PC unable to auto go sleep?

### ISSUE THREAD

**Issue by aronaoi** [WXRIW/Lyricify-App#232]
With Lyricify opened 24/7, my PC's auto sleep is set to 20 min but it never happens. It also doesn't trigger the screensaver after 3 min.
Everything worked after i have Lyricify closed, is there a way to make Lyricify not being "that app" that prevents ur PC from sleeping when I'm away from my pc?

**Comment by WXRIW** [comment]
Which lyrics display mode are you using in Lyricify?

**Comment by aronaoi** [comment]
Apple Music display. I assume that’s the issue? Is there a way to make pc auto sleep with Apple music mode?

**Comment by WXRIW** [comment]
Are you using it at fullscreen size?

**Comment by aronaoi** [comment]
Nope, it’s in a window size

**Comment by WXRIW** [comment]
Okay I see, please wait for further investigations.

**Comment by WXRIW** [comment]
Issue will be fixed in 4.2.10.

After this update, just set `Prevent sleep` in `Apple Music Lyrics` section to Fullscreen only (default value is Always).
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/6319f7a1-6ff4-44e9-80a8-e992d4dba954)
