### ISSUE TITLE
Lyricify3 Apple Music歌詞確定無法接入封面?

### ISSUE THREAD

**Issue by aunight** [WXRIW/Lyricify-App#233]
https://github.com/PKBeam/AMWin-RP/tree/v1.2.6.3
![image](https://github.com/WXRIW/Lyricify-App/assets/52199445/1adcb25c-5a09-484b-9d75-0997e17d9357)

https://github.com/NextFire/apple-music-discord-rpc
![image](https://github.com/WXRIW/Lyricify-App/assets/52199445/86845101-9c7f-4ea9-9e19-721ef7efb4fd)

以上這兩個app都可以透過Apple Music Preview去接入封面並顯示於discord(通訊軟件)的動態中
不知道Lyricify3是否有機會也能達到?

**Comment by WXRIW** [comment]
@aunight Lyricify 3 的开发已经进入 End of Life 阶段，不再进行任何功能开发。

**Comment by aunight** [comment]
好吧 期待未來版本有機會接入

**Comment by WXRIW** [comment]
Lyricify Lite 将提供 Apple Music 支持。敬请期待。
