### ISSUE TITLE
是否可加入在歌曲歌词中（而非从歌词开头开始）标记标题行的功能

### ISSUE THREAD

**Issue by Wesley10032** [WXRIW/Lyricify-App#235]
**举例：**
![Snipaste_2024-01-06_03-09-52](https://github.com/WXRIW/Lyricify-App/assets/98805299/c46b72d6-ec89-4bca-8ef9-2600826df40b)
Spotify URL: spotify:track:0QAydv9GsaYBGmiweoymjo
在某些歌的歌词中，会出现标题行不在开头，而在开头后一段的情况。
如果从此标题行选起，会出现如图情况：
![Snipaste_2024-01-06_03-10-24](https://github.com/WXRIW/Lyricify-App/assets/98805299/5bd92883-dcdd-499b-8ce2-02e1c7ace757)
将歌词开头至选中行的所有歌词全部标记为歌词行。
能否可加入某些措施来解决此类问题？感谢回答！

**Comment by WXRIW** [comment]
因为这个涉及到服务器存储的问题，而一开始的设计是只支持头尾的标题行，不支持中间的。
这种情况只能由歌词管理员手动修改歌词原文来解决。

**Comment by Wesley10032** [comment]
好的，感谢解答。
