### ISSUE TITLE
[Feature Request]能否实现点击歌词来切换进度条

### ISSUE THREAD

**Issue by chuwza** [WXRIW/Lyricify-App#236]
如图，就是大多数音乐软件都有的那种。毕竟现在拖进度条要去Spotify，看歌词又得回Lyricify，太麻烦了😂
![Screenshot_20240106-083131_网易云音乐](https://github.com/WXRIW/Lyricify-App/assets/30049891/c08b765a-c693-4f7e-a91e-143034e7a080)

**Comment by Seayay** [comment]
Lyricify Mobile 可以点击歌词行跳转
**需要 Spotify Premium**

**Comment by chuwza** [comment]
> Lyricify Mobile 可以点击歌词行跳转 **需要 Spotify Premium**

原来如此，感谢
