### ISSUE TITLE
无法正确获取本地音乐文件的封面，歌词

### ISSUE THREAD

**Issue by ShuFengYingt** [WXRIW/Lyricify-App#239]
RT，若使用Spotify播放本地音乐文件，Lyricify无法读取对应的歌曲的封面，且经常无法匹配到歌词。

测试音频文件来自于自购CD抓轨，在Spotify中可以正确获取信息：
![image](https://github.com/WXRIW/Lyricify-App/assets/110240114/6a18f877-86f6-4d4e-b385-008d87eb0143)

在Lyricify中无法获取封面和歌词
![image](https://github.com/WXRIW/Lyricify-App/assets/110240114/19fc60df-3380-40b8-b279-760b51202887)
（Apple Music 模式）

其它流媒体下载的歌曲也是相同情况

**Comment by WXRIW** [comment]
对于封面问题，请仔细阅读 Lyricify 使用指南。
对于歌词问题，如果主界面也没有歌词，自行上传即可。

**Comment by WXRIW** [comment]
鉴于已经提供了解决方案，认为问题已解决，Issue 关闭处理。
