### ISSUE TITLE
希望为mac的客户端也出一个插件

### ISSUE THREAD

**Issue by 1478976213** [WXRIW/Lyricify-App#24]
请问有这样的考虑嘛？

**Comment by WXRIW** [comment]
没有。
Mac可以用LyricX，听说很好用的

**Comment by QuantumRoseinAmethystVase** [comment]
> 没有。 Mac可以用LyricX，听说很好用的

是LyricsX吧？

**Comment by WXRIW** [comment]
> > 没有。 Mac可以用LyricX，听说很好用的
> 
> 
> 
> 是LyricsX吧？

是的
