### ISSUE TITLE
直连登陆不了

### ISSUE THREAD

**Issue by E1ev2n** [WXRIW/Lyricify-App#240]
rt登录不上超时错误

**Comment by WXRIW** [comment]
这不是 Lyricify 的问题，请自行解决。
确保 api.spotify.com 可以连接即可。

**Comment by E1ev2n** [comment]
我spotify正常使用啊就是Lyricify登录不上

**Comment by WXRIW** [comment]
Lyricify 是没有问题的。请自行检查你的网络是否能连接到 api.spotify.com

**Comment by E1ev2n** [comment]
可以连接到的正常使用 Lyricify开着梯登陆的登完关上了就不好使了

**Comment by E1ev2n** [comment]
我很头疼啊都没人遇到过这个问题开发者都说不会有问题但我就是用不了啊

**Comment by WXRIW** [comment]
不要在 Lyricify 运行时关闭系统代理。如关闭，则需重新启动 Lyricify。

**Comment by E1ev2n** [comment]
哥你信我我这边很正常的，我关了代理重开了应用10多次都不好使就是连接超时我还重装了都

**Comment by WXRIW** [comment]
关闭代理提示连接超时，就说明你需要代理才能使用。
为什么需要代理呢
因为 GFW 抽风了，这段时间使用 IPv4 访问 Spotify 会有一定问题。把代理开着就行了。
这个问题与 Lyricify 完全无关。超时指的是无法连接到 Spotify 服务器。

**Comment by E1ev2n** [comment]
抱歉忘记说清楚了前一段时间spotify ipv4出问题我就改成ipv6了然后使用一直没问题所以这回Lyricify用不了我才会费解，感谢你的耐心回答
