### ISSUE TITLE
深色专辑背景下歌词显示可读性差

### ISSUE THREAD

**Issue by valid256** [WXRIW/Lyricify-App#241]
如图
![image](https://github.com/WXRIW/Lyricify-App/assets/132802690/7289e062-3b51-47ee-a379-bcdb7d67e31e)
z
在深色背景下黑色的字体有一点易读性差的问题，虽然调成浅色主题就没问题了，但是深色的更契合spotify的主题，希望能在UI上做一点改进，谢谢！

**Comment by valid256** [comment]
附上一张浅色主题对比
![image](https://github.com/WXRIW/Lyricify-App/assets/132802690/7ed8b8c3-5360-49ee-b8a2-2d4638adcdd8)

**Comment by WXRIW** [comment]
这个问题之前有好几位用户都提过，但是我一直都没有找到一个能够让我满意的解决方案。
所以我目前的建议就是，要么就现凑合着这样看，要么就把背景改成纯色，纯色背景是经过算法优化的，不会出现过黑和过白的问题。
