### ISSUE TITLE
How can i hide this?

### ISSUE THREAD

**Issue by hoshi-hitomi** [WXRIW/Lyricify-App#243]
<img width="643" alt="image" src="https://github.com/WXRIW/Lyricify-App/assets/125431448/0f8974da-6513-43d0-bdc1-84d078a6c1e0">

without clicking the 'follow' button😇

**Comment by WXRIW** [comment]
You have to follow the developer to hide this.

**Comment by sygiegiehs** [comment]
Probably there is a need of providing a customized choice in the Lyricify config file `Settings.json`. I've been following our developer and Lyricify family for a long period of time, but still I think this feature is a bit of "agressive" to some extend. 
Only in my opinion, haha.
