### ISSUE TITLE
能不能加入日语歌词假名注音功能？

### ISSUE THREAD

**Issue by Meonthb** [WXRIW/Lyricify-App#245]
目前Lyricify有罗马音注音功能，但对于大部分日语初学者来说，假名注音功能是个更好的选择，可惜目前只知道QQ音乐PC端有这个功能，其他平台和app都是没有的，如果Lyricify能加入这个功能就好了！

**Comment by WXRIW** [comment]
我不会日语，在与部分懂日语的开发者和用户沟通后，发现这个功能如果使用自动转换来实现，会很不精确。不准确的展示还不如不展示，所以目前不打算提供此功能的支持。

下方用于记录部分参考，以便未来重启本 Issue 时使用：
https://chrome.google.com/webstore/detail/mirigana/hbekfodhcnfpkmoeaijgbamedofonjib
