### ISSUE TITLE
Lyricify 4 非要使用代理才能使用

### ISSUE THREAD

**Issue by Whitekabi** [WXRIW/Lyricify-App#246]
不开代理就进不去了，开了代理就进去了，之前第一次用这个软件的时候是不用开代理的，现在必须使用代理了怎么回事？

不开代理会显示 超时错误，请稍后再试（Place1） Lyricify 将被关闭

开了代理就直接进入了

重新启动Lyricify 4还是出现 超时错误，请稍后再试（Place1） Lyricify 将被关闭
![image](https://github.com/WXRIW/Lyricify-App/assets/132870128/f5776634-e903-40a8-b805-00cf03537c89)

尝试重新安装Lyricify 4 还是会出现这个错误，重装电脑也是

版本号：v4.2.9

**Comment by WXRIW** [comment]
这是 Spotify 的问题，与 Lyricify 无关。
请确保你的网络可以流畅访问一下两个 Spotify 域名：
accounts.spotify.com
api.spotify.com

Lyricify 服务器在上海，所以不存在无法访问的情况。超时错误是无法访问 Spotify 导致的。

更多信息可以参考近期的其他几个相关 Issue。

**Comment by WXRIW** [comment]
#240

**Comment by Whitekabi** [comment]
> api.spotify.com

明白了，谢谢
