### ISSUE TITLE
登录提示The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by DedsecLaoFsL4j** [WXRIW/Lyricify-App#247]
登录使用Chrome120.0.6099.63，自带edge浏览器均无法自动返回数据到Lyricify4，手动输入回调链接后出现以下提示。
重装.NET 可以在下次电脑重启前暂时解决问题。
<img width="338" alt="Snipaste_2024-01-24_12-52-20" src="https://github.com/WXRIW/Lyricify-App/assets/122006031/8347619d-29c9-403a-8582-ef062b35f14b">

**Comment by WXRIW** [comment]
网络问题，与 Lyricify 无关。

与上一个 Issue 类似的，你需要确保你能够流畅访问：
api.spotify.com
accounts.spotify.com

**Comment by DedsecLaoFsL4j** [comment]
可以流畅访问

**Comment by WXRIW** [comment]
麻烦提供一下日志，在 `%AppData%/Lyricify/Lyricify for Spotify` 下可以找到 `Log.txt`。

**Comment by WXRIW** [comment]
建议尝试更换节点，开启或关闭代理等

**Comment by WXRIW** [comment]
参考 #247 #246
