### ISSUE TITLE
卡在授权页，进不去

### ISSUE THREAD

**Issue by yidasanqian** [WXRIW/Lyricify-App#248]
![image](https://github.com/WXRIW/Lyricify-App/assets/10655188/1366809d-8c06-45c3-a675-c3fe37f4ace6)

![image](https://github.com/WXRIW/Lyricify-App/assets/10655188/357550a6-7fc1-4196-bd31-41b2ecde0a0e)

浏览器是edge

**Comment by WXRIW** [comment]
参考 #247 #246

**Comment by WXRIW** [comment]
鉴于非 Lyricify 问题，且已提供解决方案，本 Issue 做关闭处理。
