### ISSUE TITLE
灵动岛和桌面台词全屏模式无法正确开启

### ISSUE THREAD

**Issue by Loong111** [WXRIW/Lyricify-App#249]
开启全屏模式后，软件全屏或窗口化时歌词显示，但是仅桌面显示时歌词隐藏。

窗口化：
![20240126205055](https://github.com/WXRIW/Lyricify-App/assets/120077501/e8677de5-4abc-4246-abf7-5c81dd363b5b)
全屏：
![O@AE_78{DORJN285FD ZH4J](https://github.com/WXRIW/Lyricify-App/assets/120077501/c354e224-4485-4a9a-adf9-01e4216c6bea)
桌面：
![T92PYT_ZP%NK }A4 $JJ}~E](https://github.com/WXRIW/Lyricify-App/assets/120077501/81e56266-29dd-492b-a844-b999254d84ab)

**Comment by WXRIW** [comment]
@Loong111 请仔细阅读使用指南里的说明。

另外，你提供的第二张图并不是全屏，这是最大化。

**Comment by Loong111** [comment]
> @Loong111 请仔细阅读使用指南里的说明。
> 
> 另外，你提供的第二张图并不是全屏，这是最大化。

请问可以设置只有仅桌面时显示歌词嘛？

**Comment by WXRIW** [comment]
@Loong111 无法提供这个选项。

**Comment by WXRIW** [comment]
鉴于问题已解决，Issue 做关闭处理。
