### ISSUE TITLE
对spotify测试中的播客跟读文本功能提供支持

### ISSUE THREAD

**Issue by nerine0** [WXRIW/Lyricify-App#250]
如图，现在Spotify添加了一个测试中的跟读文本功能（即提供播客主持人的对话文本），想问问Lyricfy以后是否有可能支持播客的文本。
![image](https://github.com/WXRIW/Lyricify-App/assets/141686660/40e478a2-db85-494e-b894-bb6f4761da3a)

**Comment by WXRIW** [comment]
由于获取这个文本需要用到的 API 是 Spotify 私有的，Web API 中不包含此接口，所以目前无法提供进一步支持。

**Comment by WXRIW** [comment]
今天特意对本功能进行了测试，但是遗憾的是可行性很低。

能够实现的是：获取到文本，并加载进 Lyricify。
不好的是：由于 Podcast 长度普遍很长，歌词行数一般在 1000 行以上，这对一个普通的歌词软件来说压力过大，属于非正常情况，加载速度很慢。

下图为我加载 Podcast 文本进入 Lyricify 测试的截图（忽略曲目）
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/859b9854-2cda-42f0-8661-1214c34082da)

故综合考虑，本 Issue 作关闭处理。
