### ISSUE TITLE
【建议】添加桌面歌词的外观预设存储功能

### ISSUE THREAD

**Issue by nerine0** [WXRIW/Lyricify-App#251]
如题，即添加用户预先调试好的成套桌面歌词外观存档（字体大小，配色，轮廓粗细等），需要用的时候就可以一键切换。

**Comment by WXRIW** [comment]
这是一个不错的提议，后期会考虑加入。

但字体大小无法提供支持，这是由窗口大小决定的。

**Comment by WXRIW** [comment]
经过几个月的考虑，这个功能暂时不再考虑。主要有以下原因：
1. 这个功能需求很小众，大部分用户并不会经常调整样式。
2. 实现逻辑较麻烦，切换逻辑不方便设计。
