### ISSUE TITLE
关于QQ音乐歌词上传不了

### ISSUE THREAD

**Issue by 0107fast** [WXRIW/Lyricify-App#253]
某次我在听深海少女发现lyricfy把歌词搜索错了然后我找到分享网址，点击确定之后导入按钮变灰了，Mid也是一样（啊啊啊啊我初音未来
歌曲：深海少女
艺人：ゆうゆ，Hatsune Miku
专辑：四季彩の星

**Comment by WXRIW** [comment]
提供 QQ 音乐的曲目链接或 Mid
以及 Spotify 的曲目链接

**Comment by 0107fast** [comment]
> 提供 QQ 音乐的曲目链接或 Mid 以及 Spotify 的曲目链接

Spotify：https://open.spotify.com/track/5ymnEcBJonBJMSRRXIWM25?si=afd47a5a29b948e6
QQ音乐：https://y.qq.com/n/ryqq/songDetail/4822338
Mid：00peSl21DqcAb

**Comment by 0107fast** [comment]
> 关闭 Issue 是已经成功导入了吗？

对不起手残点错了原谅一下·

**Comment by WXRIW** [comment]
使用你提供的 QQ 音乐链接可以完成导入。
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/f9705086-1e7f-458c-a3f1-5770db97c302)
你提供的 Mid 与链接不符，不是有效的 QQ 音乐曲目 Mid。你提供的链接对应的 Mid 是 001aTDok32S3qU。
