### ISSUE TITLE
导入歌词的一个bug

### ISSUE THREAD

**Issue by Wesley10032** [WXRIW/Lyricify-App#255]
### **问题：在窗口置顶功能开启时，若主窗口未最大化，当打开Lyricify曲目管理窗口并点击QQ音乐或网易云“导入”按钮后，弹出的导入窗口与Lyricify曲目管理窗口将一同被主窗口覆盖在下方。**
问题复现过程：
1.打开Lyricify，出现如图界面。
![image](https://github.com/WXRIW/Lyricify-App/assets/98805299/4934b440-f5b4-4010-84a9-d680d0cc900a)
2.右击左下角专辑封面，点击“打开曲目管理”，出现如图界面。
![image](https://github.com/WXRIW/Lyricify-App/assets/98805299/496ebe9f-fd99-4af2-ac2d-672c2dc7f84d)
3.左击QQ音乐栏内的“导入”按钮。
![image](https://github.com/WXRIW/Lyricify-App/assets/98805299/0273560c-1b2a-4c97-b3a3-53b98a966766)
会变成下图。
![image](https://github.com/WXRIW/Lyricify-App/assets/98805299/41e5b8e0-38be-4c24-80f3-c3f28ec9efb6)
此时曲目管理窗口与弹出的导入窗口一同被主窗口所遮盖。
![image](https://github.com/WXRIW/Lyricify-App/assets/98805299/1e1cf0cf-902d-4a92-8ab9-9eb83cbfbec3)
此时Lyricify主窗口无法操作，只能在任务栏里将这两个窗口关闭。
_经测试，在主窗口最大化的情况下，在第3步点击“导入”后弹出窗口可以正常显示。_

**Comment by WXRIW** [comment]
导入使用的 InputBox 是 Microsoft.VisualBasic 中的，此问题已存在很长一段时间，因为需要重新造一个输入框才能修复，所以一直没有动它。
目前的解决方案：点击导入后，直接通过 Ctrl + V 粘贴要导入的内容，然后按 Enter 确认即可。

**Comment by Wesley10032** [comment]
了解，感谢解答。

**Comment by WXRIW** [comment]
已修复，等待新版更新！
