### ISSUE TITLE
支持显示闽南语、粤语等方言注音

### ISSUE THREAD

**Issue by Seayay** [WXRIW/Lyricify-App#256]
![image](https://github.com/WXRIW/Lyricify-App/assets/92374733/f4b53e82-2842-4143-98c3-7bfe5e64d14a)
目前已经可以显示日语的罗马音了，希望可以添加显示方言注音的功能

**Comment by WXRIW** [comment]
日语罗马音是通过转换实现的，其他语言无法实现。
