### ISSUE TITLE
支持 iTunes 暂停

### ISSUE THREAD

**Issue by yjc007** [WXRIW/Lyricify-App#26]
在iTunes播放音乐，希望音乐暂停时歌词也能停止滚动，体验就完美了！

**Comment by WXRIW** [comment]
@yjc007 这确实是个 bug ，但是当时 Lyricify 对 iTunes 的支持是基于其他几款软件（不支持时间轴同步）开发的，所以没有针对暂停进行任何优化，一开始连时间轴都不能同步，后来加入的时间轴同步。
这个 bug 暂时不修复，因为我最近一年没有计划发布新版，但是这个bug会在明年7月的 4.0 大更新中修复，此 issue 不关闭。

**Comment by yjc007** [comment]
👍

**Comment by Zero-ck** [comment]
无法连接服务器请关闭科学上网工具后重试是啥问题

**Comment by WXRIW** [comment]
@Zero-ck 为什么要在这个 Issue 里问？

**Comment by WXRIW** [comment]
@Zero-ck 是什么时候出现的，刚打开时吗？

**Comment by Zero-ck** [comment]
嗯嗯，就是刚刚打开的时候提示的

**Comment by WXRIW** [comment]
@Zero-ck 到群里来，https://t.me/lyricify

**Comment by Zero-ck** [comment]
是我网速的问题啊，还是没开科学工具 为什么你的链接我打不开

**Comment by WXRIW** [comment]
@Zero-ck 这个问题请自行检查网络是否畅通，是否可以正常访问 e.wxriw.cn

**Comment by WXRIW** [comment]
@Zero-ck 这个链接需要打开科学上网工具才可以访问

**Comment by Zero-ck** [comment]
可以 我下个 telegram

**Comment by Zero-ck** [comment]
因为没看到有相关的issue 所以就在你最近回复的issue里面发布了 抱歉

**Comment by WXRIW** [comment]
@Zero-ck 没事，以后注意

**Comment by WXRIW** [comment]
4.0 仅支持 Spotify，此 Issue 关闭。
