### ISSUE TITLE
【建议】支持本地的媒体播放器？

### ISSUE THREAD

**Issue by GuihongWang** [WXRIW/Lyricify-App#260]
rt

**Comment by WXRIW** [comment]
Lyricify Lite 会支持所有接入 SMTC 的播放器。

Lyricify 4 不考虑支持除 Spotify 外的任何软件。

**Comment by GuihongWang** [comment]
> Lyricify Lite 会支持所有接入 SMTC 的播放器。


所以lite版包括在Lyricify 4 里面吗 我找不到lite版

**Comment by WXRIW** [comment]
#144
还没发布 项目还没建文件夹

**Comment by GuihongWang** [comment]
> #144 还没发布 项目还没建文件夹

okey cy一下
