### ISSUE TITLE
不挂vpn  lyricify 无法正常启动

### ISSUE THREAD

**Issue by U-Smiles** [WXRIW/Lyricify-App#264]
问题是这样的,我在不使用vpn(大陆运营商网络)时可以正常使用Spotify, 但是自从更新了4.1.1版本的lyricify 在Spotify登录的情况下, 不使用vpn lyricify 无法正常启动. 希望作者能把更新作为一个可勾选选项, 因为我不喜欢使用不太稳定的新版本,希望能够得到解决谢谢
Thanks♪(･ω･)ﾉ

**Comment by WXRIW** [comment]
与版本无关，就算使用 4.0.0 版本照样需要使用代理。这是网络问题。参考 #246

此外，新版本比旧版本稳定很多，希望你不要对 Lyricify 的新版本产生误解。

**Comment by WXRIW** [comment]
Lyricify 4 是没有强制更新的，可以在设置中关闭自动安装更新。
除非版本过旧，目前 4.1.6 及更早版本是强制更新到新版的。

**Comment by U-Smiles** [comment]
好的get了,但还是更喜欢旧版本,不太喜欢更新..这可能是一种习惯吧

**Comment by WXRIW** [comment]
尽量保持最新，后期旧版本会因接口过期而无法正常工作。

**Comment by Antooooooc** [comment]
除了不开VPN无法登录，而且在听歌中途如果退出VPN，lyricify也不能继续运行到下一首（只有我是这样吗）

**Comment by WXRIW** [comment]
> 除了不开VPN无法登录，而且在听歌中途如果退出VPN，lyricify也不能继续运行到下一首（只有我是这样吗）

运行过程中不要修改代理配置。
