### ISSUE TITLE
Lyricify无法很好的调用我的独显

### ISSUE THREAD

**Issue by MoguJunn** [WXRIW/Lyricify-App#265]
版本：4.2.14.240209（微软商店版）
已在设置中将lyricify设置为高性能（即调用独显）
![图片](https://github.com/WXRIW/Lyricify-App/assets/89789332/1f33b19c-f3e1-4743-9202-197e5a8cbc82)
在使用apple music视图的过程中 若开为全屏 核显占用暴增 独显占用不变
![图片](https://github.com/WXRIW/Lyricify-App/assets/89789332/dad48057-f404-489f-8f5b-25cf62ba9e2c)

**Comment by WXRIW** [comment]
这个我不是很清楚，我没有独显设备，同时也没有其他用户反馈本问题。
目前我从其他用户那里得到的反馈是，正确分配独显是有显著效果的。你这个情况应该是没有正确分配独显。
