### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by bsktbooo** [WXRIW/Lyricify-App#266]
如图，手动输入回调链接也没用
![屏幕截图 2024-02-17 204049](https://github.com/WXRIW/Lyricify-App/assets/106794300/2adfa6bb-1838-49a7-9f5f-d3ff76f60e2a)
![屏幕截图 2024-02-17 204132](https://github.com/WXRIW/Lyricify-App/assets/106794300/f700da50-5101-417b-949c-5969ec04d39d)

**Comment by WXRIW** [comment]
参考 #247 #248
不是 Lyricify 的问题。
