### ISSUE TITLE
[BUG] 配置了代理但连接失败时，会导致下次无法启动软件

### ISSUE THREAD

**Issue by cyo57** [WXRIW/Lyricify-App#267]
遇到这个问题的话似乎只能手动编辑settings.json，无法通过GUI关闭

**Comment by WXRIW** [comment]
@cyo57 这个情况比较少见，短时间内我没有想到一个很好的解决方案。你可以帮助我想到一个解决方案。

**Comment by BnqDzj** [comment]
> @cyo57 这个情况比较少见，短时间内我没有想到一个很好的解决方案。你可以帮助我想到一个解决方案。

在应用代理之前测试代理连通性和在启动时代理连接失败之后跳出设置代理的界面

**Comment by WXRIW** [comment]
@BnqDzj 怎么测试连通性呢

**Comment by WXRIW** [comment]
@BnqDzj 并没有一个可靠的地址可以用来测试连通

**Comment by BnqDzj** [comment]
> @BnqDzj 并没有一个可靠的地址可以用来测试连通

https://i.scdn.co/generate_204

**Comment by WXRIW** [comment]
@BnqDzj 并不能保证 Spotify 的连通性。
我可以尝试在 设置界面 加入代理的连通性测试，而不再启动界面中加入，因为这不够优雅。

**Comment by cyo57** [comment]
> @BnqDzj 并不能保证 Spotify 的连通性。 我可以尝试在 设置界面 加入代理的连通性测试，而不再启动界面中加入，因为这不够优雅。

启动时连不上代理的话，能否自动关闭代理然后尝试重连？否则用户就必须手动settings.json才能恢复了

**Comment by WXRIW** [comment]
@cyo57 Lyricify 在检测到使用代理的情况下，如果连接失败，会自动不使用代理。

**Comment by WXRIW** [comment]
由于 Lyricify 具有自动识别代理状态，并在失效时自动关闭代理，本 Issue 认为解决。

仍然无法打开大概率是由于目前无法直连导致的。

后期可能会尝试优化，感谢反馈。

**Comment by WXRIW** [comment]
已添加连通性测试，将随新版把发布。
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/348cc991-efdb-4596-9d3c-386be83a0610)
