### ISSUE TITLE
【建议】增加机器翻译源

### ISSUE THREAD

**Issue by john-walks-slow** [WXRIW/Lyricify-App#268]
- 希望提供微信翻译之外的机器翻译源。
- 希望增加 “优先使用机器翻译” 的选项。
- 希望在播放界面，可以在不同翻译源之间（或在机器翻译与人工翻译之间）切换。

动机：人工翻译存在过度解读的情况，希望与不同的机器翻译对比

p.s. 感谢作者这么好的软件，很大地增强了听音乐的体验

**Comment by WXRIW** [comment]
微信翻译为 QQ 音乐歌词提供，并不是所谓的机器翻译源。
不考虑任何机器翻译，因为机器翻译的质量很差劲，还很耗时，用户配置起来也很麻烦，此外，有这个需求的用户也少之又少。
