### ISSUE TITLE
为 Lyricify Syllable 添加翻译行属性支持

### ISSUE THREAD

**Issue by sygiegiehs** [WXRIW/Lyricify-App#269]
如果 Lyricify Syllable 有翻译行属性，那么可以直接将歌词翻译写在 LYS 文件中，导入歌词时无需手动点击`添加翻译`再逐行输入，在导入和个人离线存储歌词时更加方便。

另外，个人感觉歌词行属性`1` `2` `3` `6`没有什么作用，它们可以分别被`4` `5` `7` `8`完全替代，不知道设计这些属性时是您是出于什么考虑？谢谢

**Comment by WXRIW** [comment]
Lyricify Syllable 的功能只包含歌词存储，不支持翻译。翻译仍需要使用 LRC 来存储，并进行时间轴匹配。
目前正在研究脱离 LRC 的翻译存储，但仍然需要独立于 Lyricify Syllable。

歌词行属性如下表所示：
| 属性 | 背景人声 | 对唱视图 |
| :-: | :-: | :-: |
| 0 | 未设置 | 未设置 |
| 1 | 未设置 | 左 |
| 2 | 未设置 | 右 |
| 3 | 否 | 未设置 |
| 4 | 否 | 左 |
| 5 | 否 | 右 |
| 6 | 是 | 未设置 |
| 7 | 是 | 左 |
| 8 | 是 | 右 |

就以 1 和 4 举例，如果设置为 1，即背景人声未设置，这时就会通过 QRC (Lyricify 标准) 的背景人声条件来进行判断，在[这里](https://github.com/WXRIW/Lyricify-App/blob/main/docs/Lyricify%204/Lyrics.md#%E8%83%8C%E6%99%AF%E4%BA%BA%E5%A3%B0%E7%9A%84%E5%88%B6%E4%BD%9C)有详细说明。如果设置为 4，则直接认为是非背景人声，就算符合QRC (Lyricify 标准) 的背景人声条件，也不会作为背景人声。

**Comment by sygiegiehs** [comment]
@WXRIW 感谢您的耐心解答！那就等到新的翻译存储方式出现后，由您来关闭本 Issue 吧。

**Comment by WXRIW** [comment]
有关你提到的导入歌词翻译较为繁琐的问题，我可以提供一个更简洁和智能的方案。

导入 Lyricify Syllable 后，如果需要添加翻译，则可以将翻译以以下格式复制到剪切板中，再点击添加翻译按钮，这时 Lyricify 会自动匹配翻译行。
如，歌词原文为：
```
Lately, I've been, I've been losing sleep
Dreaming about the things that we could be
Oh
But baby, I've been, I've been praying hard
Said no more counting dollars
```
翻译为
```
最近我总是辗转反侧 难以入眠
对我们可能的未来 浮想联翩

但亲爱的 我一直在努力祈祷
不再财迷心窍
```
这时，可以将以下内容复制到剪切板：
```
Lately, I've been, I've been losing sleep
最近我总是辗转反侧 难以入眠
Dreaming about the things that we could be
对我们可能的未来 浮想联翩
Oh

But baby, I've been, I've been praying hard
但亲爱的 我一直在努力祈祷
Said no more counting dollars
不再财迷心窍
```
也可以只包含翻译：
```
最近我总是辗转反侧 难以入眠
对我们可能的未来 浮想联翩

但亲爱的 我一直在努力祈祷
不再财迷心窍
```
注意，第三行歌词的翻译为空，此时一定要保留空行，不然会导致翻译与歌词错位。
此外，还需要注意翻译行数与 Lyricify Syllable 的歌词行数一致。

**Comment by WXRIW** [comment]
> @WXRIW 感谢您的耐心解答！那就等到新的翻译存储方式出现后，由您来关闭本 Issue 吧。

新增翻译存储方式与 Lyricify Syllable 没有直接关联，而是适用于所有格式，故本 Issue 做关闭处理。

**Comment by sygiegiehs** [comment]
还有一个问题，如果`对唱视图`信息未设置， Lyricify 会如何显示呢？

如果是一律靠左，是否可以认为属性`3` `6`分别等同于`4` `7`？

**Comment by WXRIW** [comment]
Lyricify 有一套算法，来自动判断和决定对唱视图。

**Comment by sygiegiehs** [comment]
> 有关你提到的导入歌词翻译较为繁琐的问题，我可以提供一个更简洁和智能的方案。
> 
> 导入 Lyricify Syllable 后，如果需要添加翻译，则可以将翻译以以下格式复制到剪切板中，再点击添加翻译按钮，这时 Lyricify 会自动匹配翻译行。 如，歌词原文为：
> 
> ```
> Lately, I've been, I've been losing sleep
> Dreaming about the things that we could be
> Oh
> But baby, I've been, I've been praying hard
> Said no more counting dollars
> ```
> 
> 翻译为
> 
> ```
> 最近我总是辗转反侧 难以入眠
> 对我们可能的未来 浮想联翩
> 
> 但亲爱的 我一直在努力祈祷
> 不再财迷心窍
> ```
> 
> 这时，可以将以下内容复制到剪切板：
> 
> ```
> Lately, I've been, I've been losing sleep
> 最近我总是辗转反侧 难以入眠
> Dreaming about the things that we could be
> 对我们可能的未来 浮想联翩
> Oh
> 
> But baby, I've been, I've been praying hard
> 但亲爱的 我一直在努力祈祷
> Said no more counting dollars
> 不再财迷心窍
> ```
> 
> 也可以只包含翻译：
> 
> ```
> 最近我总是辗转反侧 难以入眠
> 对我们可能的未来 浮想联翩
> 
> 但亲爱的 我一直在努力祈祷
> 不再财迷心窍
> ```
> 
> 注意，第三行歌词的翻译为空，此时一定要保留空行，不然会导致翻译与歌词错位。 此外，还需要注意翻译行数与 Lyricify Syllable 的歌词行数一致。

建议将此方案添加到 Lyricify Wiki 中 😃

**Comment by WXRIW** [comment]
> 建议将此方案添加到 Lyricify Wiki 中 😃

已将此部分教程并入 Lyricify 4 使用指南。
https://github.com/WXRIW/Lyricify-App/blob/main/docs/Lyricify%204/README.md#%E6%B7%BB%E5%8A%A0%E7%BF%BB%E8%AF%91

感谢支持！
