### ISSUE TITLE
点击关闭窗口[X]默认最小化到通知栏，而非直接退出应用

### ISSUE THREAD

**Issue by Arckzzzzz** [WXRIW/Lyricify-App#27]
当前要使用快捷键CTRL + H或者手动点击菜单栏的‘最小化到通知栏’才能实现，然而大多数可后台应用的操作习惯都是点击关闭窗口按钮时默认最小化，或者让用户选择默认最小化还是退出应用，希望将来可以改善一下~
![image](https://user-images.githubusercontent.com/32861605/130320921-0b896b1d-0dd7-476b-8559-8636aae1616e.png)

**Comment by WXRIW** [comment]
这个提议很早就有用户提出来了。由于比较麻烦就没去弄。
最小化到通知栏功能是后来加的，有些用户觉得麻烦，所以加了个快捷键。
这个功能最终会在 4.0 里实现，敬请期待。

**Comment by WXRIW** [comment]
Lyricify 4.0 中已完成此功能，此 Issue 关闭。
