### ISSUE TITLE
移动端无法登陆，报错未在播放

### ISSUE THREAD

**Issue by onichan0923** [WXRIW/Lyricify-App#270]
如图，API 均正确填写，点 GO 一直提示「Playback is null, you need to play songs in Spotify」，无法正常使用软件。
实质后台 Spotify 正在播放歌曲，设置中的装置广播状态也已打开。
![Screenshot_20240219-232220](https://github.com/WXRIW/Lyricify-App/assets/68043613/efdd016e-8449-4a8a-949d-d678f3ee55f8)

**Comment by WXRIW** [comment]
## Lyricify 无法获取当前播放信息
Lyricify 没有显示当前正在播放的歌曲。
### 导致原因
Spotify 没有上传当前的播放信息。这是网络原因，也可能是 Spotify 客户端的问题。
### 解决方案
1. 校园网用户，可以尝试使用热点。
2. 科学上网工具改为全局。
3. 重装 Spotify 最新版。
4. 使用 Spotify 移动版或网页版。
5. 反正不是 Lyricify 的锅，自己想办法解决。

https://github.com/WXRIW/Lyricify-App/blob/main/docs/Lyricify%204/README.md#lyricify-%E6%97%A0%E6%B3%95%E8%8E%B7%E5%8F%96%E5%BD%93%E5%89%8D%E6%92%AD%E6%94%BE%E4%BF%A1%E6%81%AF

**Comment by WXRIW** [comment]
问题已提供解决方案，Issue 做关闭处理。
