### ISSUE TITLE
【建议】配置艺术家的别名

### ISSUE THREAD

**Issue by john-walks-slow** [WXRIW/Lyricify-App#271]
遇到过几次“搜不到歌词”的情况，原因是 Spotify 与 网易云/QQ 使用的艺术家名字不匹配。
例如：有形ランペイジ 这支乐队的英语名为 UK Rampage。网易云/QQ 使用了日语名，Spotify 使用了英语名，导致无法自动匹配歌词。

希望添加的功能：在曲目管理中配置不同平台上艺术家的别名，在不同平台上使用不同别名来匹配歌词。

**Comment by WXRIW** [comment]
针对本艺人，将 Spotify 和 Lyricify 语言改为日语即可。
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/fbe83f1c-d1f5-4f3e-a730-e2bf25293b4a)

**Comment by WXRIW** [comment]
大部分日本艺人在中文环境下的 Spotify 都会显示为日语名，极少部分艺人是例外，就比如你举例的这个艺人。
Lyricify 对中英不同名的情况已经做了适配，但这种例外无法避免。

**Comment by WXRIW** [comment]
https://github.com/WXRIW/Lyricify-Lyrics-Helper/blob/master/Lyricify.Lyrics.Helper/Searchers/Helpers/ArtistHelper.cs

在这个文件里有 Lyricify 使用的完整 **中(含日)<-->英** 对照列表。

**Comment by john-walks-slow** [comment]
> 针对本艺人，将 Spotify 和 Lyricify 语言改为日语即可。

👌
