### ISSUE TITLE
lyricify无法接受授权成功信号

### ISSUE THREAD

**Issue by Luovr** [WXRIW/Lyricify-App#273]
在Microsoft官方商店购买下载后，网页授权成功，但是软件接收不到授权成功信号
<img width="1235" alt="屏幕截图 2024-02-20 205352" src="https://github.com/WXRIW/Lyricify-App/assets/62422083/e0ac90aa-7cf6-41e6-8d0d-9fd0e0815af5">
并且在我按照提示尝试手动输入授权回调连接，也不能识别
<img width="692" alt="屏幕截图 2024-02-20 205537" src="https://github.com/WXRIW/Lyricify-App/assets/62422083/4d0ff1d7-4d06-4b07-9f76-64bdbd788c55">
我本人没有相关的电脑知识，我一直打开的VPN，用的是美国的线路，因为电脑版的Spotify不用VPN开不了，我发现好像和开不开没关系，不开VPN，连授权回调连接都打不开。
抱歉占用您的时间，我会在这个期间自己试试，希望能得到您的答复。

**Comment by WXRIW** [comment]
这个提示指的是无法建立 SSL 连接，即网络有问题，可以参考 #247 #248 #266

建议尝试更换节点，更换梯子，开关全局代理等方法。

**Comment by Luovr** [comment]
谢谢大佬，那么快回我，谢谢谢谢

**Comment by WXRIW** [comment]
方便提供一下日志吗，我想借助日志进一步研究一下这个问题。

在成功完成登录，能进入主界面后。打开设置，翻到最下面，点 `日志` `打开文件夹`，然后把 `Log.txt` 发一下即可。感谢支持！

**Comment by Luovr** [comment]
其实很惭愧哈。我昨天晚上在结束聊天后，一直试到11：30，都没成功。。。。。。我切换了全局模式，结果还是不行，尝试关闭lyricify自己的代理设置再次尝试也不成功，我想着，到学校里去再试试吧
这个是我用的代理软件，昨天晚上我试了好几个几点，冰岛的都试了，全局不全局都试过，后来折腾得不行了，就干脆睡了。。
<img width="392" alt="屏幕截图 2024-02-21 081459" src="https://github.com/WXRIW/Lyricify-App/assets/62422083/fb5edf47-4d7b-4671-acb2-5bcce40bad3f">
我把我的log.txt发过来您看一下吧，我也不求解决问题了，给您做个参考吧。可能对您解决这类问题也没啥帮助，抱歉占用您的时间了。
[Log.txt](https://github.com/WXRIW/Lyricify-App/files/14352486/Log.txt)

**Comment by WXRIW** [comment]
经过我的检查，是网络有问题，您可以尝试更换科学上网工具，很多用户跟我反馈，更换一家梯子就能用了。
感谢支持！

**Comment by yinhongyang** [comment]
我没有用梯子，但也遇到了同样的问题。请问是必须用梯子才可以吗？

**Comment by WXRIW** [comment]
> 我没有用梯子，但也遇到了同样的问题。请问是必须用梯子才可以吗？

建议开启科学上网工具。

**Comment by playdougher** [comment]
我开了代理工具没有效果，后面我启用代理工具的“允许局域网连接”，然后在windows系统设置里手动编辑和启用代理后，lyricify可以授权了
![微信截图_20240309131020](https://github.com/WXRIW/Lyricify-App/assets/26463515/47e1fdd4-965f-4570-8536-2e3c6ebcb438)

**Comment by Maopigui** [comment]
换成手机热点就行了
我也是跟你一样死活登不上，来github看有谁解决了问题，发现没人解决或是方法没用，捣鼓半天换个手机热点就行了
