### ISSUE TITLE
如何在启动时指定Lyricify的请求走代理？

### ISSUE THREAD

**Issue by morninghut** [WXRIW/Lyricify-App#277]
又遇到了 #218 的问题。

我明白这是网络问题，测试发现当前网络下，`accounts.spotify.com`,`api.spotify.com`和`mirror.ghproxy.com`均无法ping通。

但如果我指定`http_proxy://x:10809`代理后，curl的结果是正常的。

似乎 Lyricify 启动时没有配置代理的选项，只有第一次登陆成功后才能进入设置？有什么方法可以配置为启动时启用代理吗？谢谢

**Comment by WXRIW** [comment]
@morninghut 现在的 Lyricify 在未登录时是有代理设置的。在欢迎界面右下角。

**Comment by morninghut** [comment]
@WXRIW 谢谢！

~~设置了代理后还是卡在callback，最后还是切换网络解决问题，怪~~
