### ISSUE TITLE
windows版本的字体能自定义吗

### ISSUE THREAD

**Issue by SYuan03** [WXRIW/Lyricify-App#278]
windows版本的字体能自定义吗，有点想换换，但看了手动设置的json里面好像也么得地方改？

**Comment by WXRIW** [comment]
歌词的字体可以自定义，在设置里就能改

**Comment by SYuan03** [comment]
![image](https://github.com/WXRIW/Lyricify-App/assets/91423966/92f22f55-146b-472e-bdaa-d4215de87284)
emm好像没看到？我之前也找过，我是3.8.6版本

**Comment by WXRIW** [comment]
Lyricify 3 不能任意自定义字体，Lyricify 4 支持。

**Comment by SYuan03** [comment]
好的，了解了，感谢
