### ISSUE TITLE
[ 功能请求 ] 批量检测歌单在不同地方的可用性

### ISSUE THREAD

**Issue by LINKlang** [WXRIW/Lyricify-App#279]
如题，现在一个个地区的看歌单可用性太慢了，希望可以进入页面后直接请求所有地方的数据，生成一张表格或者在选择国家那里边上给每个国家都加上可用性的提示（图一这样）或者直接更改国家的文字样式（图2）
![image](https://github.com/WXRIW/Lyricify-App/assets/116951234/aa9f58f6-b602-482f-8d4c-b463301750af)
![image](https://github.com/WXRIW/Lyricify-App/assets/116951234/e1b7a58d-0a6c-4641-af53-2f3857ea903f)

**Comment by WXRIW** [comment]
这个想法是好的，但是实现起来不现实，每个地区都要请求一次，这只会让 Spotify API 负载过度。

如果你想查询某首歌所有地区的可用性，可直接讲曲目或专辑链接粘贴进文本框。

**Comment by LINKlang** [comment]
> 这个想法是好的，但是实现起来不现实，每个地区都要请求一次，这只会让 Spotify API 负载过度。
> 
> 如果你想查询某首歌所有地区的可用性，可直接讲曲目或专辑链接粘贴进文本框。

我现在想查的一个歌单，我当前地区这个歌曲不可用，我就拿不到它的链接

**Comment by WXRIW** [comment]
@LINKlang 曲目不可用也是可以获取其链接的

**Comment by LINKlang** [comment]
> @LINKlang 曲目不可用也是可以获取其链接的

是否可以详细讲讲？
我没有在spotify官方网页中找到获取歌曲链接的按钮
lyricify中，甚至不能右键获取歌曲链接
![image](https://github.com/WXRIW/Lyricify-App/assets/116951234/d27cb2d3-908f-49b5-ac7f-b6847331ff74)

**Comment by WXRIW** [comment]
你截图里的曲目是本地歌曲，不是 Spotify 的歌曲。自然是没有链接的，也是无法查询可用性的。

**Comment by LINKlang** [comment]
> 你截图里的曲目是本地歌曲，不是 Spotify 的歌曲。自然是没有链接的，也是无法查询可用性的。

原来不是spotify的歌曲吗！🤡

好的没事了感谢答复
