### ISSUE TITLE
希望能够增加更改搜索默认源的选项

### ISSUE THREAD

**Issue by kilesduli** [WXRIW/Lyricify-App#28]
对于一些略微小众的歌曲，歌词可能qq音乐没有，网易云有这时得自己复制链接来更换歌词源。
或者一些歌词，用户觉得网易翻译的更有味什么的。
能否给用户一个选择，例如歌词源优先级排序，搜不到再换下一个歌词源。
像foobar的lyric一样
![image](https://user-images.githubusercontent.com/43215593/130344500-b4128f5a-84a2-4c36-90f8-f4538dbdf6dd.png)
虽然服务器标记的方法比较简便，但不是很小众的音乐都能直接搜到正确的歌词，而有些小众音乐qq翻译感觉没网易云做的好（
只是个提议（

**Comment by WXRIW** [comment]
@kilesduli 这个问题我之前在群里解释过了，在 4.0 的时候提供两个选项：一个是仅 QQ ，另一个是先 QQ 再 网易云，但是不会提供先网易云再 QQ 的选项。QQ 的歌词质量和翻译质量比网易云要整齐很多，因为要保留歌词标记功能，所以不会把歌词质量参差不齐的网易云作为首选词源。
您所提到的小众歌曲，QQ 音乐没有歌词这种情况，可以使用上文中提到的“先 QQ 再网易云”，在 4.0 正式更新前，只能通过手动导入来解决，毕竟只有少数歌是这样的，只要导入一次再标记就可以了。

**Comment by WXRIW** [comment]
@kilesduli 服务器标记是针对所有用户的方案，所以为了保护歌词质量，Lyricify 只能选择 QQ 优先的方案。当然，4.0 的时候也会相对应的做出一些优化，争取一次性正确。
当前版本，如有不便，敬请谅解😘

**Comment by ALAZKAblessedme** [comment]
小众歌单用户真的吐了  qq音乐的歌词全死了  网易云的歌词还活了大半   我还一直找怎么网易云优先级呢
