### ISSUE TITLE
Your Lyricify account has been restricted

### ISSUE THREAD

**Issue by Marmur2020** [WXRIW/Lyricify-App#280]
Did I do something wrong? (I'm writing here because I don't know Chinese and i don't use other cellular networks).

![o](https://github.com/WXRIW/Lyricify-App/assets/109208530/86bd1590-9441-4784-9417-e11741564cd0)

**Comment by WXRIW** [comment]
Please provide your Spotify account link, so I can investigate for details.

You can get your Spotify account link here:
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/8bfa9dd0-69dd-46c8-9cd1-005a5ac31ab5)

**Comment by Marmur2020** [comment]
https://open.spotify.com/user/kdmfm4wj9g5ftyyveq8x6uz2h?si=b2da384770244dc7

**Comment by WXRIW** [comment]
The reason why your Lyricify account has been restricted is that you had violated Lyricify Lyrics Vault's rules.

You have uploaded lyrics from Kugou into Lyricify Lyrics Vault while QQ Music and Netease Cloud Music having correct and corresponding lyrics.
Before your importation, Lyricify has noticed you about the rules:

_**Attention:** 
Do not manually import lyrics if QQ Music or Netease Cloud Music has the lyrics! 
If the corresponding lyrics are not found through the search button on Lyricify, it does not mean that there are none. You need to manually search in the apps of QQ Music and NetEase Cloud Music to ensure that there are no corresponding lyrics before it can be considered as "no lyrics". 
Your account might be limited if you violated this rule. 
Continue to import?_

The track is [Whatever - Kygo & Ava Max](https://open.spotify.com/track/0LMwmV37RCmBO2so0szAFs).

**I have removed your importation to this track and removed your account restriction.**

Here is the full version of [Lyricify Lyrics Vault's rules](https://github.com/WXRIW/Lyricify-App/blob/main/docs/Lyricify%204/README.md#lyricify-%E6%AD%8C%E8%AF%8D%E5%BA%93), the documents are in Simplified Chinese, use a translator if needed. 

**Please pay attention to our rules** so we can create a better lyrics environment together. Thank you for your support!

**Comment by Marmur2020** [comment]
> **Please pay attention to our rules** so we can create a better lyrics environment together. Thank you for your support!
Thank you for your reply, now I will know how to import music properly.
