### ISSUE TITLE
希望可以出一个能在任务栏显示歌词的功能

### ISSUE THREAD

**Issue by MirrorDraw** [WXRIW/Lyricify-App#285]
如题，因为我的笔记本经常需要连接不同的屏幕，导致每次显示歌词都得重新调整位置，所以希望能把歌词显示到任务栏，这样歌词既不会乱跑，也不会遮挡屏幕的其他显示。 类似下面这种效果（这个只是摆放到了任务栏）
![image](https://github.com/WXRIW/Lyricify-App/assets/54784165/9bc0ee78-de94-4343-a561-29c65b2f13d0)

**Comment by WXRIW** [comment]
将桌面歌词移动到任务栏就是任务栏歌词了。

**Comment by WXRIW** [comment]
修改屏幕配制后，桌面歌词的位置会被重置，这时必须手动将其重新移动至合适位置。

任何在 Windows 11 或更新版本中实现任务栏歌词都是通过桌面歌词的这种方式实现的，所以不再做更多额外支持。

**Comment by WXRIW** [comment]
目前已能实现描述的功能，只是不适合经常修改显示配置的特定用户。故认为问题已解决，Issue 关闭。
