### ISSUE TITLE
请问微软商店用户如何设置开机启动

### ISSUE THREAD

**Issue by jsdfhasuh** [WXRIW/Lyricify-App#286]
找不到快捷方式

**Comment by jsdfhasuh** [comment]
找到了，有点麻烦，需要在cmd cd到目录里面找，请问作者每一次更新这个路径会发生改变吗

**Comment by WXRIW** [comment]
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/40f6f1d9-6f84-46ea-bc97-2859fdb150ed)
在开始菜单里直接将 Lyricify 4 拖出来即可建立快捷方式。

**Comment by WXRIW** [comment]
问题已解决，故 Issue 关闭。
