### ISSUE TITLE
建议添加自动检测

### ISSUE THREAD

**Issue by LMFuture-Me** [WXRIW/Lyricify-App#29]
省的要创建快捷方式,直接检测就行

`#include <windows.h>
#include <tlhelp32.h>
#include <stdio.h>

BOOL FindProcess(const char* ProcessName)
{
    int i = 0;
    PROCESSENTRY32 pe32;
    pe32.dwSize = sizeof(pe32);
    HANDLE hProcessSnap = ::CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
    if (hProcessSnap == INVALID_HANDLE_VALUE)
    {
        i += 0;
    }
    BOOL bMore = ::Process32First(hProcessSnap, &pe32);
    char toCMP[256];
    while (bMore)
    {
        sprintf(toCMP, "%ws", pe32.szExeFile);
        if (stricmp(ProcessName, toCMP) == 0)
        {
            i += 1;
        }
        bMore = ::Process32Next(hProcessSnap, &pe32);
    }
    if (i > 1) {
        return true;
    }
    else {
        return false;
    }
}

int MusicAppDetector() {
    if (FindProcess("itunes.exe"))
        return 1;
    //后面的也一样
}`

我写得很烂，但是差不多就这个意思

**Comment by LMFuture-Me** [comment]
（还有一半是网上抄的，就是改了改让MSVC能编了而已）

**Comment by WXRIW** [comment]
@LMFuture-Me 4.0 会尽量实现自动检测，已经在 To-Do 里了。不过 3.x 无法实现这个功能，尤其是 iTunes 和 Spotify （登录状态），目前获取 iTunes 播放信息时会自动打开 iTunes， Spotify 登录和未登录状态的切换也在启动时切换，其他时候都无法切换（有点麻烦），所以目前版本还是需要手动切换，4.0 会进行优化（但是估计 Spotify 登录状态 和 其他软件（包括 Spotify 未登录状态）是不可以自动切换的，到时候我尽量实现吧）。
此 Issue 不关闭。
P.S. Lyricify 是 C# 写的，抄不了 VC++ 的代码，不过还是感谢你对本项目的支持和贡献！谢谢！😘😘😘

**Comment by WXRIW** [comment]
@LMFuture-Me 4.0 的时候主框架全部重构，应该差不多

**Comment by WXRIW** [comment]
Lyricify 4.0 仅支持 Spotify，此 Issue 关闭。
