### ISSUE TITLE
歌词标记

### ISSUE THREAD

**Issue by noif-max** [WXRIW/Lyricify-App#290]
标记可以取消吗？第一次用不太会用，点了一个与歌曲不对应的歌词标记，导致每次放这首歌曲就要手动本地导一遍，即使通过网易云搜索到歌词但还是不显示，只显示被标记的qq音乐歌词，但qq歌词与歌曲不一致，网易云搜索出来虽然是对的，但是无法显示，也不能标记，每次打开都是与歌曲不同的qq歌词。

**Comment by WXRIW** [comment]
上传正确的 QQ 音乐歌词即可覆盖之前的标记，如果没有正确的 QQ 音乐歌词，则需要由歌词管理手动处理，请提供曲目的 Spotify 链接。

**Comment by noif-max** [comment]
spotify:local:%E6%A2%A8%E5%86%BB%E7%B4%A7%E3%80%81Wiz_H%E5%BC%A0%E5%AD%90%E8%B1%AA:%E7%BD%97%E7%94%9F%E9%97%A8%EF%BC%88Follow%EF%BC%89:%E7%BD%97%E7%94%9F%E9%97%A8%EF%BC%88Follow%EF%BC%89:243
；有qq歌词，但是是qq版本的，和网易云版本的不一样，这首歌有两个版本，我现在是想换成网易云歌词，曲目管理也有，但是就是换不了，主界面只能显示qq。自己手动导入自己的歌词虽然可以显示，但是每次都要换。其实我的意思是为什么曲目管理有网易云歌词但是换不了只能用QQ的。

**Comment by noif-max** [comment]
刚刚更新19版本好像可以手动导入来上传服务器保存解决了这个，18版本保存不了，但是假如QQ音乐和网易云音乐都有歌词如何来选择啊，不然它只显示被标记的歌词，如果自己没有歌词的话，而曲目管理有但因为标记了qq却无法更换网易云。

**Comment by WXRIW** [comment]
都有歌词的时候会根据你的选择来显示，在设置里可以选择歌词默认来源。

**Comment by WXRIW** [comment]
上传不了是因为你是新用户，在使用指南中有说明，新用户是无法上传的。

**Comment by WXRIW** [comment]
长期无回复，认为问题已解决，Issue 关闭。

**Comment by DMZZZZZZZ** [comment]
我觉得这个功能还是有点必要的 有时候网易云的歌词时间轴比较准确 但是已经标记了qq音乐 只能在设置里面改默认来源有点难受

**Comment by DMZZZZZZZ** [comment]
有个办法了 切成qq音乐或者网易云优先再保存 就行了
