### ISSUE TITLE
灵动岛能否关闭图标显示

### ISSUE THREAD

**Issue by rgtzd35** [WXRIW/Lyricify-App#293]
我想把自带的绿色图标关掉，只显示歌词，请问是否可以加入这个功能

**Comment by WXRIW** [comment]
1. Lyricify 似乎没有灵动岛，只有灵动词岛。
2. Lyricify Logo 是必须显示的。如果真的需要，后期可以考虑增加关闭右侧专辑图片的选项。

**Comment by WXRIW** [comment]
问题已解决，Issue 做关闭处理。
