### ISSUE TITLE
播放时自定义封面

### ISSUE THREAD

**Issue by Seayay** [WXRIW/Lyricify-App#294]
Spotify 上的歌曲封面与国内流媒体平台封面不同，是否可以自定义某首歌在 Lyricify 中显示的封面？
![image](https://github.com/WXRIW/Lyricify-App/assets/92374733/f40e4166-d99a-4b21-a363-a8272e9d1db1)

**Comment by WXRIW** [comment]
可以手动修改。

修改方式如下：
1. 打开 `%AppData%/Lyricify/Lyricify for Spotify/Cache/Images`。
2. 找到对应专辑的图片（可能存在多张，尺寸不同）。
3. 将其替换为其他图片。
4. 重新打开 Lyricify 即可生效。

**Comment by WXRIW** [comment]
已提供解决方案，故 Issue 做关闭处理。
