### ISSUE TITLE
关于deepin系统的支持情况

### ISSUE THREAD

**Issue by enKl03B** [WXRIW/Lyricify-App#295]
系统信息如图
![截图_dde-control-center_20240317135259](https://github.com/WXRIW/Lyricify-App/assets/163709829/032bd9c2-46aa-4876-bbd2-30e8d79e25d7)
在系统自带的uengine（安卓模拟器，Android 7.1.2）中可正常运行mobile版本
但使用wine9.1无法运行lyricify 4
![截图_geek64 exe_20240317135222](https://github.com/WXRIW/Lyricify-App/assets/163709829/97d64a8f-f22b-4a19-b488-55b6002384bb)
![截图_conhost exe_20240317135810](https://github.com/WXRIW/Lyricify-App/assets/163709829/144cd8f2-067e-49c1-8502-d3a98fa2bb1e)
![截图_winver exe_20240317135529](https://github.com/WXRIW/Lyricify-App/assets/163709829/0a7c7e8a-6245-477a-8afe-816076f56cc6)
错误信息如下
[backtrace.txt](https://github.com/WXRIW/Lyricify-App/files/14626315/backtrace.txt)

**Comment by WXRIW** [comment]
我不是 Linux 用户，对 Linux 不是很了解，所以无法协助解决有关通过 Wine 实现 Lyricify 运行的问题，敬请谅解。
https://github.com/WXRIW/Lyricify-App/issues/203#issuecomment-1817454324

可以参考 #192 #195 #203。

**Comment by enKl03B** [comment]
嗯，目前mobile版本运行正常，我用mobile就行

**Comment by WXRIW** [comment]
存在多个同类 Issue，故合并，此 Issue 关闭。
