### ISSUE TITLE
【建议】降低 Lyricify 歌词库的使用优先级

### ISSUE THREAD

**Issue by john-walks-slow** [WXRIW/Lyricify-App#296]
虽然作者提示了不要将其他平台已有的歌词上传至 Lyricify 歌词库，还是会遇到 Lyricify 歌词库覆盖其他平台歌词的情况。Lyricify 歌词库上的版本往往缺少翻译，导致无法优先使用包含翻译的歌词来源。

例：https://open.spotify.com/track/5h3ynZiK27wTtQt0uXId75 ，会显示歌词库中无翻译的版本，但其实可以在QQ音乐中搜索到包含翻译的歌词。

希望可以把 Lyricify 歌词库的使用优先级降低，遵从来源设置中的“翻译优先”。

**Comment by WXRIW** [comment]
这种情况需要手动反馈，管理员会做删除处理，并对上传者账号做封禁限制处理。

**Comment by john-walks-slow** [comment]
> 这种情况需要手动反馈，管理员会做删除处理，并对上传者账号做封禁限制处理。

不考虑自动遵从“翻译优先”吗？

**Comment by WXRIW** [comment]
Lyricify 歌词库的优先级是最高的，不受任何设置影响。如果完全遵守翻译优先，则在未标记 QQ 音乐和网易云音乐的曲库中耗时过长，不利于体验。

目前最推荐的方案是将问题曲目报告给歌词管理员管理员会对违规歌词和用户做相应处理。

**Comment by john-walks-slow** [comment]
> Lyricify 歌词库的优先级是最高的，不受任何设置影响。如果完全遵守翻译优先，则在未标记 QQ 音乐和网易云音乐的曲库中耗时过长，不利于体验。
> 
> 目前最推荐的方案是将问题曲目报告给歌词管理员管理员会对违规歌词和用户做相应处理。

好的，感谢回复！
