### ISSUE TITLE
请问如何按原名搜索？

### ISSUE THREAD

**Issue by sxinxins** [WXRIW/Lyricify-App#297]
spotify设置的语言是韩语，lyricify设置的语言是中文，获取的spotify的信息是英文版的。

在q音里手动搜韩语能搜到歌。请问有办法让lyricify搜按原名搜吗？

图顶端是灵动词岛显示的名字，左侧是手动搜的q音，右侧是spotify的名字。![image](https://github.com/WXRIW/Lyricify-App/assets/30524883/eabe9279-cbb2-4347-9699-3bda2a9ebc5f)

**Comment by WXRIW** [comment]
目前没有办法实现你想要的功能。Lyricify 请求调用的语言是与 Lyricify 设置语言一致的。你设置的语言是中文，所以返回的值就是中文（无中文时会回落到其他语言，如英语） 。
由于目前 Lyricify 没有提供韩语界面，所以就不会请求韩语，所以 Spotify 返回的结果就是中文（并回落至英文）。

**Comment by WXRIW** [comment]
建议保持 Spotify 语言与 Lyricify 语言一致，语言不一致时，体验会下降。

针对你提出的问题，目前可以提供以下几个解决方案：
1. 手动导入没有自动搜索到曲目的对应歌词，并上传。
2. 协助 Lyricify 添加韩语本地化支持。

后期 Lyricify 有可能会提供手动选择 Spotify 请求地区的选项，但没有具体计划，不一定会做这个功能。

**Comment by sxinxins** [comment]
> 建议保持 Spotify 语言与 Lyricify 语言一致，语言不一致时，体验会下降。
> 
> 针对你提出的问题，目前可以提供以下几个解决方案：
> 
> 1. 手动导入没有自动搜索到曲目的对应歌词，并上传。
> 2. 协助 Lyricify 添加韩语本地化支持。
> 
> 后期 Lyricify 有可能会提供手动选择 Spotify 请求地区的选项，但没有具体计划，不一定会做这个功能。

好的，多谢建议。准备两个软件都用回中文。
回头研究研究怎么手动导入。
很乐意协助添加语言支持，但最近比较忙，或许七月份之后有时间的话会联系大大（能力有限，可能也不能帮到忙）
