### ISSUE TITLE
[功能请求]添加新的调色板

### ISSUE THREAD

**Issue by Redappleyyds** [WXRIW/Lyricify-App#298]
![image](https://github.com/WXRIW/Lyricify-App/assets/134820858/925e2c89-a6f3-4d31-bd97-c31ac3289e82)
桌面歌词的调色板太难使了
还不支持hsl

**Comment by WXRIW** [comment]
Lyricify 调用的是系统的 ColorPicker，由 Windows 提供，无法修改其功能。
为了实现你想要的功能，只能自己做一个 ColorPicker。由于这是一个鲜有人用的需求，为此单独做一个不值得。

**Comment by WXRIW** [comment]
目前的 ColorPicker 的可用性是有的，且没有功能缺失，所以不考虑修改。

调用的颜色是通过 RGB 存储的，所以单独提供 HSL 没有什么意义，如需要 HSL 可自行转换并输入。

**Comment by mcuTiger** [comment]
可以尝试使用微软的 [PowerToys](https://github.com/microsoft/PowerToys)
