### ISSUE TITLE
Lyricify Mobile的Android端能否显示全面屏手势条

### ISSUE THREAD

**Issue by chuwza** [WXRIW/Lyricify-App#299]
大佬好，如图，现在全面屏手势条是隐藏的，在Lyricify Mobile和Spotify间切换不太方便，需要先唤出手势条，再切换应用或者回到桌面。

![Screenshot_20240325-191925_Lyricify](https://github.com/WXRIW/Lyricify-App/assets/30049891/e7d2c0ee-05a2-48e4-9dc9-3a84e8b63fc0)
能否让手势条默认显示呢？

**Comment by WXRIW** [comment]
旧版本是有的。1.2.0-beta 起是隐藏的。

之前有用户反馈小白条的区域比较难看，所以我才去掉了。

**Comment by chuwza** [comment]
> 旧版本是有的。1.2.0-beta 起是隐藏的。
> 
> 之前有用户反馈小白条的区域比较难看，所以我才去掉了。

那能否加一个开关呢？🥺用Lyricify Mobile的时候，有时需要频繁在Spotify和Lyricify Mobile间切换。每次需要先唤出小白条真的太麻烦了😭

**Comment by WXRIW** [comment]
其实跟系统也有一定关系，有些系统就没这个问题，可以直接切。

后期可能可以考虑你这个功能请求。Issue 暂不关闭。若后期不再考虑本功能，将作关闭处理。

**Comment by chuwza** [comment]
> 其实跟系统也有一定关系，有些系统就没这个问题，可以直接切。
> 
> 后期可能可以考虑你这个功能请求。Issue 暂不关闭。若后期不再考虑本功能，将作关闭处理。

是的，确实和系统有关，国产定制大多能直接切，我用的是类原生，就不行。

好的，感谢😄

**Comment by WXRIW** [comment]
考虑到启用导航栏后，下方区域会比较难看，且实现导航栏沉浸比较麻烦，经研究综合考虑，不再实现本 Issue 提出的请求，敬请谅解。

**Comment by WXRIW** [comment]
此坑已填。

![Screenshot_2024-11-20-16-27-59-520_com.wxriw.lyricifymobile.jpg](https://github.com/user-attachments/assets/220cd140-b712-474b-9827-478668908510)

**Comment by chuwza** [comment]
> 此坑已填。
> 
> ![Screenshot_2024-11-20-16-27-59-520_com.wxriw.lyricifymobile.jpg](https://private-user-images.githubusercontent.com/62491584/388008798-220cd140-b712-474b-9827-478668908510.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwOTE3OTcsIm5iZiI6MTczMjA5MTQ5NywicGF0aCI6Ii82MjQ5MTU4NC8zODgwMDg3OTgtMjIwY2QxNDAtYjcxMi00NzRiLTk4MjctNDc4NjY4OTA4NTEwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDA4MzEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyNDYxYWRhMjYxZmVmNzE1MmJkNjY0OWFmNDI3Y2E5YzYzODg0OGRiOGJkYjgwZTZmMTJiNGVhMGZlZWIyZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.21DP2V9s34Ls-E5WN0QAJPPqE8mD7XENHyxjSyUXzJA)

非常感谢大佬👍
