### ISSUE TITLE
请问可以修改快捷键吗？

### ISSUE THREAD

**Issue by hyskr** [WXRIW/Lyricify-App#3]
请问可以修改快捷键吗？有时候在终端按下 `ctrl + shfit + c`进行复制时，就把它改为纯音乐了。

**Comment by WXRIW** [comment]
没考虑到这个情况，我争取下版本修复。

P.S. `Ctrl + Shift + C`是标记为正确，`Ctrl + Shift + V`是标记为纯音乐。

**Comment by hyskr** [comment]
哦，抱歉，记错了，谢谢哈！软件真的非常优秀，体验也很好。

**Comment by WXRIW** [comment]
感谢支持！
误标记的歌词可以在 [https://github.com/WXRIW/Lyricify-App/issues/4](url) 反馈

**Comment by WXRIW** [comment]
v3.5.0已更新，支持快捷键修改。具体方法见Lyricify使用说明！

**Comment by hyskr** [comment]
谢谢作者！
