### ISSUE TITLE
歌词报错

### ISSUE THREAD

**Issue by hyh504** [WXRIW/Lyricify-App#30]
**歌曲:** Brand New Day
**专辑:** Rei Yasuda
**曲目编号:** 3
**ID:** 1GxfpUfpBPzioCFHbQkh2J
**ISRC:** JPU901301345
**专辑 ID:** 1w7GnPNuJNTlhQc4saNJ8k
**详情:** 这首歌不是纯音乐

**Comment by WXRIW** [comment]
@hyh504 已作删除处理
错误歌词上报请不要新开 Issue，谢谢
