### ISSUE TITLE
[建议] 增加spotify的歌词导入

### ISSUE THREAD

**Issue by Yiikea** [WXRIW/Lyricify-App#303]
非常好的软件！

在使用的时候我发现有些歌曲（例如非英语歌曲的名称在国内音乐平台和国外不同）可能在spotify上有歌词，但在Q音/网易云没有。在选取歌词来源的选项中，能否新增一个直接从spotify导入呢？

不知这个功能是否麻烦，感谢~~

**Comment by WXRIW** [comment]
如果 QQ 音乐或网易云音乐上有这首歌的歌词（没搜到需要手动去 QQ 音乐 **和** 网易云音乐手动搜索确认），则可以手动上传 Spotify 歌词，在[这里](https://github.com/WXRIW/Lyricify-App/blob/main/docs/Lyricify%204/README.md#lyricify-%E6%AD%8C%E8%AF%8D%E5%BA%93)有详细教程。

**Comment by Yiikea** [comment]
> 如果 QQ 音乐或网易云音乐上有这首歌的歌词（没搜到需要手动去 QQ 音乐 **和** 网易云音乐手动搜索确认），则可以手动上传 Spotify 歌词，在[这里](https://github.com/WXRIW/Lyricify-App/blob/main/docs/Lyricify%204/README.md#lyricify-%E6%AD%8C%E8%AF%8D%E5%BA%93)有详细教程。

好的，刚才我也找到了，感谢！
