### ISSUE TITLE
Where is the Android APK file?

### ISSUE THREAD

**Issue by okgamr** [WXRIW/Lyricify-App#304]
I can't find the APK for Lyricify Mobile. Couldn't find either the iOS profile. You could also give more info about this in the file dedicated to mobile downloads (the last link from the table in readme)

**Comment by WXRIW** [comment]
It is in readme, as well as GitHub Releases. 

https://github.com/WXRIW/Lyricify-App/releases/tag/mobile-v1.4.2

**Comment by pdimu** [comment]
Oh, sorry, didn't see it bcs it wasn't as latest (aka lyricify 4 which had just windows and macos).

**Comment by WXRIW** [comment]
Lyricify 4 does not support macOS natively. It only supports Windows.

**Comment by okgamr** [comment]
> Lyricify 4 does not support macOS natively. It only supports Windows. 

Said by mind, aka didn't know this just thought

**Comment by okgamr** [comment]
I'm struggling now to get the refresh token for the login, but can't find it anywhere. Found [this](https://getyourspotifyrefreshtoken.herokuapp.com/callback) but it gives me invalid uri

**Comment by okgamr** [comment]
Still same - even if I complete it or not

**Comment by WXRIW** [comment]
Provide the screenshot, or screen recording would be better.

**Comment by okgamr** [comment]
Restarted the process, but now found a guide in the repo:
> Fill Create app page with these:
> App name: Lyricify
> App description: Lyricify Custom API Client
> Website: (Leave it empty)
> Redirect URI:http://localhost:766/callback
But now, even though the uri is now ok, the app cancels the operation. I'll send a screen record soon

**Comment by okgamr** [comment]
https://github.com/WXRIW/Lyricify-App/assets/128509556/07c7d914-e231-432f-927b-d8e6d3f40b01

**Comment by WXRIW** [comment]
Since you are using a VPN service, please turn it off and try again.
Also, you don't need to paste that url into the token textbox.

**Comment by okgamr** [comment]
k will try
