### ISSUE TITLE
建议：时间轴矫正时不要播放出声音。

### ISSUE THREAD

**Issue by woodsdalang** [WXRIW/Lyricify-App#305]
诚然，为了使用体验，时间轴矫正是必需的。
但卡顿回退的1s，确实是很烦人。
若可以在时间轴矫正时不播放出声音，使用体验想必会得到很大的提升。
不知设想可否实现？

**Comment by WXRIW** [comment]
绝大多数歌曲在进行时间轴优化时不会出现异常声音。只有极少数曲目会出现异常声音。
“时间轴优化”作为一个可以关闭的选项，就是为了方便用户在放弃部分体验的情况下，不产生异常声音。
时间轴校正的时长是极短的，如果通过 Spotify API 来控制 Spotify 的音量，还没等到音量调整，声音就已经发出了。如果通过调节系统音量来实现，则过于 Hacker，且可行性不高。
所以这是一个无法解决的问题，目前“时间轴优化”功能是能给出的最优解。

**Comment by woodsdalang** [comment]
了然，谢谢您的解答
