### ISSUE TITLE
Lyricify 灵动词岛的“全屏隐藏”与 Wallpaper Engine 冲突

### ISSUE THREAD

**Issue by Wesley10032** [WXRIW/Lyricify-App#306]
如题，当开启 Wallpaper Engine 时，关闭“全屏隐藏”，效果如下：
![image](https://github.com/WXRIW/Lyricify-App/assets/98805299/93801ae1-7550-4883-9623-1af4700fc25c)
当开启“全屏隐藏”，灵动词岛便会消失不见：
![image](https://github.com/WXRIW/Lyricify-App/assets/98805299/712d8c5b-52f1-4098-a5b7-27452154e311)
希望能加入某些白名单机制，排除掉这类动态壁纸软件。

**Comment by WXRIW** [comment]
对于这个问题，之前的方案是无法避免的，所以在 Lyricify 4 文档中，也写到了这个问题。

我们可以尝试进一步的研究相关方面。由于我的设备不具有 Wallpaper Engine 的使用条件，无法直接测试，故希望可以直接将测试版本发送给你，来进行测试。

可以通过 QQ 群组或 Telegram 群组找到我，方便后续联系和测试。感谢支持。

**Comment by LINKlang** [comment]
cy，等解决方法

**Comment by WXRIW** [comment]
可以用这个版本测试一下，然后在本 Issue 中反馈效果。
https://wxriw.lanzn.com/iDTO11v7b2oh

**Comment by LINKlang** [comment]
> 可以用这个版本测试一下，然后在本 Issue 中反馈效果。 https://wxriw.lanzn.com/iDTO11v7b2oh

没有效果，灵动词岛依然会在回到桌面，无任何前台窗口，且开启Wallpaper Engine的情况下自动消失

**Comment by Wesley10032** [comment]
> 可以用这个版本测试一下，然后在本 Issue 中反馈效果。 https://wxriw.lanzn.com/iDTO11v7b2oh

我用这个版本是OK的

**Comment by Wesley10032** [comment]
> > 可以用这个版本测试一下，然后在本 Issue 中反馈效果。 https://wxriw.lanzn.com/iDTO11v7b2oh
> 
> 没有效果，灵动词岛依然会在回到桌面，无任何前台窗口，且开启Wallpaper Engine的情况下自动消失

一样

**Comment by WXRIW** [comment]
经过与 @Wesley10032 的测试，目前的解决方案无法优化本问题，故 Issue 做关闭处理。
若有任何用户有新的解决思路，可以在本 Issue 中讨论。
本 Issue 的测试代码（Lyricify 同款全屏检测）已经放在了这个仓库：https://github.com/WXRIW/FullScreenHelperTest
