### ISSUE TITLE
问题：Lyricify 强制采用歌词库里没有翻译的歌词，而没采用有翻译的其它来源歌词

### ISSUE THREAD

**Issue by woodsdalang** [WXRIW/Lyricify-App#307]
wiki上说"在 Lyricify 歌词库中有歌词时，会直接使用，不会使用其他来源。"

可是有些歌，Lyricify 歌词库里有歌词但没有翻译，而手动搜索到的qq或网易云来源的歌词有翻译。
这时Lyricify仍采用自己歌词库里的词，看不到翻译，即使设置里歌词来源已选择 “翻译优先且QQ音乐优先”
怎么办？

这种情况有可能是如下情况导致的：
某歌曲当时的qq音乐和网易云音乐均没有歌词与翻译，某热心用户便上传了来自spotify(Musixmatch)或是自己编写的的歌词，导入到了Lyricify 歌词库。
而后来QQ音乐或网易云音乐有了歌词与翻译，后来人即使能搜索到歌词与翻译，Lyricify却不会采用，而是用之前来自spotify的歌词或是那人自己上传的歌词。
这该如何？

如歌曲——
歌曲名: Livin' On A Prayer
歌曲 ID: 37ZJ0p5Jm13JPevGcx4SkF
歌曲 ISRC: USPR38619998
歌曲 URI: spotify:track:37ZJ0p5Jm13JPevGcx4SkF
歌曲时长: 4:09
曲目编号: 3

专辑名: Slippery When Wet
专辑 ID: 0kBfgEilUFCMIQY5IOjG4t
专辑发行日期: 1986-08-16
专辑曲目数: 10

艺人: Bon Jovi
艺人 ID: 58lV9VcRSjABbAbfWS6skp

**Comment by WXRIW** [comment]
遇到 QQ 音乐或网易云音乐有歌词，但 Lyricify 歌词库也有歌词的情况，请及时与 Lyricify 管理组联系，我们会对违规账号做封禁处理。

对于你描述的这种情况，手动删除（普通用户是有删除未锁定的 Lyricify 歌词库歌词权限的）即可。

**Comment by WXRIW** [comment]
Lyricify 歌词库的优先级是最高的，只要 Lyricify 歌词库有歌词，就不会进行任何额外的搜索，减少资源占用，加快歌词加载速度。

**Comment by woodsdalang** [comment]
之前不知道普通用户可以删除未锁定Lyricify 歌词库歌词，现在知道了。
建议把这一条写进wiki

**Comment by WXRIW** [comment]
一般不建议删除别人导入的歌词，尤其是自制歌词，而更建议联系管理员进行处理。

**Comment by woodsdalang** [comment]
明白，若再次遇到，我会联系管理员的。
