### ISSUE TITLE
什么时候把4移植到mobile上就好了，mobile还需要丰富，想要逐字歌词

### ISSUE THREAD

**Issue by Adoretheall007** [WXRIW/Lyricify-App#308]

**Comment by WXRIW** [comment]
## 没有逐字歌词
为啥不显示逐字歌词呢？
### 导致原因
Lyricify Mobile 不支持逐字歌词的显示。也没有加入此功能的计划。
### 解决方案
自行脑补逐字歌词。或使用 Lyricify 4。

## 如何在手机上使用 Lyricify 4
Lyricify 4 好多功能 Lyricify Mobile 都没有啊，啥时候才能有呢。
### 导致原因
Lyricify Mobile 目标就是显示歌词，现在目标已经达成。
### 解决方案
在 Windows 设备上使用 Lyricify 4。您可以给您的手机安装 Windows on ARM。
