### ISSUE TITLE
Lyricify Mobile 提议

### ISSUE THREAD

**Issue by Jyuan-Ip** [WXRIW/Lyricify-App#309]
平板横屏什么时候可以和iPad一样左边封面右边歌词啊？超级馋这个功能

**Comment by WXRIW** [comment]
这个功能一直在计划中，原计划与今年年初开发并发布的，但是由于一些问题，计划得到延期。
目前该功能预计于今年年底或明年发布。但具体发布时间仍然未定，随时可能更改。

鉴于本建议一直在开发计划中，故 Issue 做已完成的关闭处理，可关注后续更新。
目前更推荐使用 Windows 上的 Lyricify 4 以获得最佳体验。
