### ISSUE TITLE
关于本地文件歌词

### ISSUE THREAD

**Issue by hyh504** [WXRIW/Lyricify-App#31]
为什么 没有登陆Lyricify时，可以显示本地歌曲的歌词，为什么 登录以后就无法显示

**Comment by WXRIW** [comment]
@hyh504 这个是因为登录后是通过 ISRC 和 Spotify ID 来获取歌词的，但播放本地歌曲时，这两个参数均为空，这时其实可以通过歌曲名和歌手来获取歌词的，但是由于有用户会点击标记按钮，这时，这首歌的正确歌词将会上传服务器，但也会导致所有用户在播放本地歌曲时都显示这首歌的歌词，所以我在服务器端暂时禁用了登录后本地歌曲歌词的显示。
这个问题将在 4.0 时解决。

**Comment by WXRIW** [comment]
Lyricify 4 中针对此问题进行了优化，此 Issue 关闭
