### ISSUE TITLE
lyricify4 windows端程序，spotify授权后，lyricify个人资料页显示异常，切歌异常

### ISSUE THREAD

**Issue by Reflection404** [WXRIW/Lyricify-App#313]
lyricify4 windows端程序，spotify授权后，lyricify个人资料页显示异常，切歌异常

**Comment by WXRIW** [comment]
已知问题，目前可通过配置自定义 API Client 解决。今天将发布紧急修复更新。

**Comment by WXRIW** [comment]
已发布紧急修复更新，版本号 4.2.24
