### ISSUE TITLE
部分网易云歌词源的歌词显示错误

### ISSUE THREAD

**Issue by 0x00A0** [WXRIW/Lyricify-App#316]
例如Kent-Sverige的歌词:
![image](https://github.com/WXRIW/Lyricify-App/assets/26670072/a6ff3157-c8dd-461c-8ebe-5b5c344ac95c)
而曲目管理中是正常的:
![image](https://github.com/WXRIW/Lyricify-App/assets/26670072/ce07b0a5-90fe-452d-b321-4ddb9b6e213c)
疑似是网易云自己的接口问题(在网易云PC端歌词正常但手机端歌词显示也不正常)
网易云PC端:
![image](https://github.com/WXRIW/Lyricify-App/assets/26670072/6910bd2f-fb4e-4982-92aa-a1c83ee2318c)
网易云手机端(与Lyricify同样的不完整歌词):
![eea0059f262e200dbfa555b5b376881](https://github.com/WXRIW/Lyricify-App/assets/26670072/20d11b7f-a8fc-4666-b156-d81dbe7fd4b1)
而本曲的QQ音乐版歌词则直接显示不出所有äöå等瑞典语字母:
![image](https://github.com/WXRIW/Lyricify-App/assets/26670072/31be9e7a-8270-41aa-b472-846947919324)

**Comment by 0x00A0** [comment]
**补充**: 似乎关闭网易云逐字歌词后bug消失

**Comment by WXRIW** [comment]
是的，你的推断是正确的，确实是网易云音乐的接口提供的数据就有问题。
这是网易云的逐字歌词原文：
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/e7615d12-84bb-40c1-b64b-c88c08d99bc1)
这是网易云的逐行歌词原文：
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/d68cbbcd-6e83-427f-9f1e-77af7313d03d)
这是 QQ 音乐的歌词原文：
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/36a27910-b491-453a-9262-35cdcf5f19b5)

网易云音乐 PC 端使用的是旧的逐行的接口，所以显示就没有问题，而手机版加入了逐字支持，故出现了异常歌词。
这个情况是网易云音乐的问题，Lyricify 这边无法解决。可以尝试与网易云音乐取得联系，以修复异常歌词。Lyricify 会自动跟进最新的逐字歌词。

**Comment by WXRIW** [comment]
P.S. 以后反馈歌词问题，一定要附上 Spotify 分享链接，或 Spotify URI。
