### ISSUE TITLE
[功能请求] Apple music页面的dj切歌

### ISSUE THREAD

**Issue by LINKlang** [WXRIW/Lyricify-App#317]
现在aidj基本全面推送spotify了，但是aidj给到不喜欢的风格时还得切换回spotify主程序有点麻烦，希望可以在顺序播放按钮附近或下拉栏中加入让aidj推不一样的歌按钮（在spotify中的按钮是这个![image](https://github.com/WXRIW/Lyricify-App/assets/116951234/8be341ea-1e1f-45b9-b4be-dc58f2025ad9)）

**Comment by WXRIW** [comment]
因无法实现，故 Issue 关闭。
