### ISSUE TITLE
[BUG] 复制歌曲列表无法正常复制歌曲数量大于100的歌单

### ISSUE THREAD

**Issue by cyo57** [WXRIW/Lyricify-App#319]
多次测试均无法完整复制歌单，最多复制一百首歌曲信息，复制的信息结尾处是

曲目 100
歌曲名: 可惜没如果
歌曲 ID: ******
*********

实际歌单中歌曲数量要大于100

**Comment by WXRIW** [comment]
已修复，请等待更新，感谢反馈。
