### ISSUE TITLE
内存溢出bug

### ISSUE THREAD

**Issue by ZhuHuan521** [WXRIW/Lyricify-App#324]
![image](https://github.com/WXRIW/Lyricify-App/assets/104779750/fbda6b53-3172-4678-8851-9b15d279a81f)
版本v3.8.6

**Comment by WXRIW** [comment]
你在通过 Lyricify 给什么 App 提供歌词？提出 Issue 一定要描述得很清楚，这十分重要。

FYI，Lyricify 3 已停止维护。

**Comment by ZhuHuan521** [comment]
如图 Apple Music

**Comment by WXRIW** [comment]
Apple Music 是通过 SMTC 获取播放状态的，由于代码逻辑较差，当运行时间较长时可能会出现内存占用较高的问题，可通过重启 Lyricify 解决。

**Comment by ZhuHuan521** [comment]
好吧，我自己写一个算了
