### ISSUE TITLE
Lyricify不显示托盘图标，且无法完全退出

### ISSUE THREAD

**Issue by PIndividual** [WXRIW/Lyricify-App#326]
偶然发现任务栏图表中的Lyricify图标消失了，直接关闭主窗口也不能将其完全退出，需要到任务管理器杀进程。
如图：
<img width="369" alt="9e9bf9d82e70ef138fcdc75f02275e34" src="https://github.com/WXRIW/Lyricify-App/assets/62368342/7f16076b-2103-4b8f-b359-cbd2f35acaa8">
考虑到未来相似的情况还可能出现，建议添加另一种完全退出Lyricify的方式，这里我认为可以参考Spotify的策略，直接在高级菜单加一个退出的选项，如图
<img width="285" alt="1961a04c9dde6639d18bfcd9cbe0cd39" src="https://github.com/WXRIW/Lyricify-App/assets/62368342/12176dec-ddcd-45f8-a1ab-72600e90d85c">

**Comment by WXRIW** [comment]
将在后期版本中加入，敬请期待！

**Comment by WXRIW** [comment]
由于 Lyricify 主菜单中没有 File 选项，故无法添加到主菜单中。
目前的方案是，为通知栏的退出选项提供快捷键，以解决这个问题。

**Comment by WXRIW** [comment]
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/08e009a6-915e-4761-a21b-1b1c919bb145)
已添加本功能，将随新版本发布。直接在主窗体按快捷键即可。
