### ISSUE TITLE
windows版桌面歌词能否添加边缘吸附的功能？

### ISSUE THREAD

**Issue by Cairl** [WXRIW/Lyricify-App#327]
希望windows版桌面歌词能添加自动吸附边缘的功能，和QQ音乐桌面歌词那样不需要瞄准像素就能轻易摆在桌面边缘上真的很实用。如果做这样的功能的话，请考虑任务栏也在吸附的对象中。

**Comment by WXRIW** [comment]
@Cairl 这听起来很棒，但是有一些问题需要得到更多讨论。
首先我认为只有顶部和底部有必要对齐这个像素，左右两侧就没有什么必要了。居中反而是更好的选择。其次，顶部的对齐非常容易，只要将桌面歌词拖到顶部，超出部分会自动回到屏内。
任务栏吸附实现起来非常困难，这涉及到诸多方面的问题，如尺寸、间距等等，且不一定能达到预期效果，手动调节往往是更好的方案。
以上是我的初步见解。

**Comment by Cairl** [comment]
> @Cairl 这听起来很棒，但是有一些问题需要得到更多讨论。 首先我认为只有顶部和底部有必要对齐这个像素，左右两侧就没有什么必要了。居中反而是更好的选择。其次，顶部的对齐非常容易，只要将桌面歌词拖到顶部，超出部分会自动回到屏内。 任务栏吸附实现起来非常困难，这涉及到诸多方面的问题，如尺寸、间距等等，且不一定能达到预期效果，手动调节往往是更好的方案。 以上是我的初步见解。

我认为左右对其同样有必要性，有的时候在写文档时，居中会遮挡工作区域。这种时候我都会把桌面歌词的对齐方式调成左对齐，然后拖到左边去。这种时候如果像我一样是双显示器的话，对齐边缘会花上一点时间。
你说的对齐任务栏的困难我可以理解，所以我反而觉得对齐顶部和底部倒没那么重要了，因为顶部的居中有灵动岛了，底部随便摆一摆的话也不会拖到其他显示器上面去。
所以我个人还是认为，如果吸附边缘这个功能可以实现的话，左右边缘吸附还是需要实现的。

**Comment by WXRIW** [comment]
@Cairl 一般来说，使用桌面歌词时，用户会锁定桌面歌词，以防止对其他操作造成影响，锁定后，是否进行了像素级对齐显得不是很重要。然后在多显示器上做这个对齐吸附也是一件比较麻烦的事情。

**Comment by Cairl** [comment]
> @Cairl 一般来说，使用桌面歌词时，用户会锁定桌面歌词，以防止对其他操作造成影响，锁定后，是否进行了像素级对齐显得不是很重要。然后在多显示器上做这个对齐吸附也是一件比较麻烦的事情。

如果是特别麻烦的事这当然就另当别论了。

**Comment by WXRIW** [comment]
能否提供一段 QQ 音乐桌面歌词的吸附效果录屏，我参考后将决定是否实现本 Issue 提议的功能。

**Comment by Cairl** [comment]
https://github.com/WXRIW/Lyricify-App/assets/20336299/c392abac-bdae-4450-acda-b125fef62043

可以看的出来，QQ音乐的桌面歌词有底部边缘吸附效果，但是没有跨显示器边缘吸附功能，不过在非显示器交界处的边缘还是有吸附边缘效果的。

**Comment by WXRIW** [comment]
这样的左右限制非常好做，但是从这段录屏上看，似乎没有办法将桌面歌词拖出显示区域，来到左侧或右侧以外。

**Comment by Cairl** [comment]
> 这样的左右限制非常好做，但是从这段录屏上看，似乎没有办法将桌面歌词拖出显示区域，来到左侧或右侧以外。

是的，我认为限制歌词显示在屏幕范围内就很不错，有的时候玩游戏会出现游戏内分辨率和桌面分辨率不一致的情况，切屏时有可能会让歌词出现在意想不到的位置上。

**Comment by WXRIW** [comment]
经过一段时间的研究，由于实现困难，故目前不打算实现这个功能，Issue 暂作关闭处理。
