### ISSUE TITLE
希望能增加“喜欢”该歌曲的快捷键设置！感谢🙏

### ISSUE THREAD

**Issue by AndyLinyeye** [WXRIW/Lyricify-App#328]

**Comment by WXRIW** [comment]
这个功能实现起来不难，但是全局实现起来有部分困难，所以只会支持局部快捷键。
计划使用 `Alt + F` 作为该功能快捷键，不考虑提供自定义选项。

**Comment by WXRIW** [comment]
预计随下一版本发布。

**Comment by WXRIW** [comment]
该功能将延期，因为目前 Spotify Web API 的已点赞歌曲接口出了问题，待 Spotify 修复该问题后，会继续开发本功能。

**Comment by WXRIW** [comment]
https://community.spotify.com/t5/Spotify-for-Developers/Check-User-s-Saved-Tracks-is-returning-the-wrong-value/m-p/6048431
这是我在 Spotify Developer 论坛中的反馈。
