### ISSUE TITLE
无法正确保存上传 TTML 歌词

### ISSUE THREAD

**Issue by sygiegiehs** [WXRIW/Lyricify-App#329]
### TTML 歌词上传异常
在 Lyricify 歌词库导入 Apple Syllable (TTML 格式) 歌词，能够在主窗口中预览，也能点击保存上传至服务器，也有绿色提示显示“成功上传”，然而再次点击“刷新服务器信息”后却发现歌词并未正确上传。

### 为什么我要导入 TTML 格式歌词呢？
TTML 格式更为强大，主要是为了歌词能在 Lyricify Mobile 上优雅地显示。
譬如，一句歌词后有一处背景人声，使用其他格式不可避免地要将背景人声歌词单独成行，在 Lyricify Mobile 上的观感不佳，特别是当背景人声的时长很短时，动画会跳得太快。但如果使用 TTML 格式，则可以将该歌词和背景人声合为一行，在 Lyricify Mobile 显示时观感指数级提升。

**Comment by WXRIW** [comment]
@sygiegiehs Apple Music 歌词的导入目前是需要管理员权限的，所以可以通过转换为 Lyricify Syllable 来正常导入，建议在头部顺便加上
[from:AppleSyllable]
[id:am的曲目id]
然后跟上 Lyricify Syllable 原文即可。

**Comment by sygiegiehs** [comment]
@WXRIW 但是正如前面所说，Lyricify Syllable 想要实现背景人声就必须单独成行，及其影响着 Mobile 的歌词观感，使用 TTML 则没有这个问题，因为可以合为一行显示，观感自然。
TTML 也是一个很棒不赖的格式，建议对普通用户也开放 TTML 歌词的导入权限！谢谢

**Comment by WXRIW** [comment]
@sygiegiehs Lyricify 目前不支持 TTML 格式的歌词，仅支持 Apple Music提供的 JSON 原始文件，里面包含了 TTML 歌词内容，这会让用户无法编辑，所以导入没有实际意义。
至于你提到的 Lyricify Mobile 的问题，需要明确的一点是，Lyricify Mobile 目前没有背景人声这一概念，所以任何形式的展示方式都是正确的，我个人更喜欢 Lyricify Syllable 目前的表达，他能更好的展现背景人声的起始和结束。这也是为什么在导入 Apple Music 歌词的时候，会自动显示 Lyricify Syllable 的原因。
事实上这两种格式的歌词 Lyricify Mobile 都是不支持读取的，所以都是由服务器转换成 Lyricify Lines 格式的歌词以供 Lyricify Mobile 读取。转换过程中的操作由服务器决定。这在以后都可能会发生变化。

**Comment by WXRIW** [comment]
@sygiegiehs 在支持逐字之前是没有这个计划的，在支持逐字后这是一定会加入的功能。

**Comment by sygiegiehs** [comment]
> @sygiegiehs 在支持逐字之前是没有这个计划的，在支持逐字后这是一定会加入的功能。

但是 Lyricify Mobile 不是不可能支持逐字吗？ 
https://github.com/WXRIW/Lyricify-App/issues/225#issuecomment-1865426550

**Comment by WXRIW** [comment]
@sygiegiehs 目前的方案确实是无法实现逐字的，所以在未来 Lyricify Mobile 可能会经历重构，在对应平台寻找更合适的解决方案，为逐字提供支持。不过这些都还是理论层面，至于何时能够落实，是完全没有预计的。

**Comment by sygiegiehs** [comment]
好的，感谢您的耐心，大佬早点休息吧！
