### ISSUE TITLE
[bug]本软件的spotify全屏模式进入后切歌会闪退

### ISSUE THREAD

**Issue by Tim-Saijun** [WXRIW/Lyricify-App#33]
按下spotify全屏（F11），过段时间软件就闪退
win11，分辨率1080p竖屏

**Comment by WXRIW** [comment]
@Tim-Saijun 请提供版本号

**Comment by Tim-Saijun** [comment]
> @Tim-Saijun 请提供版本号
3.6.0

**Comment by WXRIW** [comment]
@Tim-Saijun 更换 3.6.0.3-beta，此版本修复了这个bug
