### ISSUE TITLE
能否增加，Lyricify Fullscreen模式下关闭Lyricify图标的按钮？

### ISSUE THREAD

**Issue by AndyLinyeye** [WXRIW/Lyricify-App#331]
![image](https://github.com/WXRIW/Lyricify-App/assets/128774079/2b4286fd-0ba3-4a75-9f5a-0a64db11205a)

**Comment by WXRIW** [comment]
不考虑，这个区域作为 Lyricify 的标识，只能提供彩色/单色选择，就跟灵动词岛左侧的 Logo 不能去掉，Apple 产品的背面不能去掉 Logo 一个道理。
