### ISSUE TITLE
【曲目管理】原歌词间隔不一致，歌词逐渐快于歌曲，无法采取整体偏移修正

### ISSUE THREAD

**Issue by Huiaei** [WXRIW/Lyricify-App#332]
# 歌曲信息
   - 歌名：没爱你的本事
   - 艺人：洋澜一
   - ISRC：FRX452431155
   - Spotify ID：1qn2tQpAmSXDy8Dm4oZQdF
# 歌词
   - QQ音乐ID：465620401
   - QQ音乐Mid：003ouBvo1rSCmP
# 出现的问题
歌词存在间隔逐渐变大的情况，即一开始，歌词与歌曲进度匹配，但随着播放，歌词与歌曲的进度对位间隔越来越大，具体表现为歌词变快了。只调节offset整体偏移量无法对齐。

ps：未解决的情况下不小心点了保存，上传到了服务器，非常抱歉。

**Comment by WXRIW** [comment]
@Huiaei 这种情况有以下几种解决方案：
1. 在 QQ 音乐和网易云音乐寻找正确的歌词，并导入
2. 若 QQ 音乐和网易云音乐均没有正确歌词，则可以导入其他来源的歌词，或自制歌词并导入 Lyricify 歌词库。

**Comment by Huiaei** [comment]
> @Huiaei 这种情况有以下几种解决方案：
> 
>     1. 在 QQ 音乐和网易云音乐寻找正确的歌词，并导入
> 
>     2. 若 QQ 音乐和网易云音乐均没有正确歌词，则可以导入其他来源的歌词，或自制歌词并导入 Lyricify 歌词库。

歌词是自动从QQ音乐获取到了，出现问题的歌词也是来自QQ音乐。能否在QQ音乐有歌词的情况考虑手动微调歌词后上传到Lyricify 歌词库？

**Comment by WXRIW** [comment]
@Huiaei 可以在 QQ 音乐找找看有没有正确的歌词，自动搜索的不一定是最正确的。

**Comment by Huiaei** [comment]
> @Huiaei 可以在 QQ 音乐找找看有没有正确的歌词，自动搜索的不一定是最正确的。

spotify链接：https://open.spotify.com/track/1Lfw3jVBF2vIBCRIEquRyg?si=068f61c853f94e72
这个是QQ音乐的链接：https://y.qq.com/n/ryqq/songDetail/003ouBvo1rSCmP
指向是正确的，听了下qq，歌词进度是对的上，歌词内容没有错。
发现的唯一区别是QQ音乐市场是4分8秒，spotify是4分34秒。
```
4*60+8=248
4*60+34=274
274/248=1.10483870968
歌词最后一句为 3:41.850
3*60+41=221
221*1.104/60=4.0664≈4分4秒
```
此处通过听的方式验证了最后一句开始时间也为4分4秒左右，与计算能对上。

**Comment by Huiaei** [comment]
哦，抱歉，还真是选择的问题。
搜索的时候直接从搜索框跳转过来的，现在看了一下搜索结果页，确实有4分34秒的版本。
抱歉麻烦了这么久。

**Comment by Huiaei** [comment]
已更新信息保存上传服务器
