### ISSUE TITLE
锁定歌词

### ISSUE THREAD

**Issue by Troyyzw** [WXRIW/Lyricify-App#335]
为啥要锁定歌词呢？不能让用户自己选择吗。。。。这专辑里的翻译错的太离谱了吧
![Uploading 屏幕截图 2024-05-05 101130.png…]()

**Comment by Seayay** [comment]
@Troyyzw 我感觉你的截图貌似并没有成功上传

**Comment by WXRIW** [comment]
@Troyyzw 锁定歌词只是对歌词的保护，防止恶意编辑，完全没有妨碍用户对来源的选择。我们致力于为 Lyricify 用户提供最好的歌词服务。

**Comment by Troyyzw** [comment]
就是Taylorswift的新专辑为什么显示是lyricify歌词库管理员已锁定，就算我在设置里选择qq翻译优先也不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WXRIW/Lyricify-App"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月5日(星期天) 上午10:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WXRIW/Lyricify-App] 锁定歌词 (Issue #335)





 
@Troyyzw 我感觉你的截图貌似并没有成功上传

**Comment by WXRIW** [comment]
@Troyyzw Lyricify 歌词库的优先级最高的，提供的歌词质量也是最高的，不会受到任何设置影响。它们由 Lyricify 管理组成员构建，能为用户提供一流的歌词信息。
有任何错误均可通过 Telegram 或 QQ 群组反馈给歌词管理。

**Comment by fred913** [comment]
@WXRIW 1. 截图未上传，看不到，起码告诉我们是哪些歌吧
2. 翻译错的离谱……？对于歌词库，或者对于歌词的翻译向来都是需要文艺修饰的。歌词的艺术形式和当前曲风决定了翻译的下限，也就意味着直译，此时译者翻译时是必定融入感情和个人理解的，这部分偏差无法消除，我们也只能做到尽可能地客观全面，遵循多数原则。

**Comment by WXRIW** [comment]
由于长时间收到没有任何回复，认为 Issue 已经解决，故做关闭处理。
