### ISSUE TITLE
希望在设置里添加开机自启动

### ISSUE THREAD

**Issue by CNO501** [WXRIW/Lyricify-App#336]
虽然wiki上写了如何实现开机自启动，但还是希望可以直接在设置里面启动开机自启动

**Comment by WXRIW** [comment]
@CNO501 这个功能没有作为一个内嵌设置是因为 Lyricify 4 的设计使得开机并不实用，且存在诸多问题。
我是不太建议用户将 Lyricify 设置为开机自启项的，但是由于部分用户仍然想自行设置开机自启，所以我将这个功能的手动启用方式写在了使用指南中。
Lyricify 4 天生不适合开机自启，所以我们不会提供该设置项。但值得注意的是，Lyricify Lite 将支持原生的开机自启选项，敬请期待。
