### ISSUE TITLE
[BUG]在双屏下软件缩放不统一

### ISSUE THREAD

**Issue by Redappleyyds** [WXRIW/Lyricify-App#339]
如下:
![image](https://github.com/WXRIW/Lyricify-App/assets/134820858/4e0aee94-b6e3-4c64-a778-60f3719d6e86)
![image](https://github.com/WXRIW/Lyricify-App/assets/134820858/d4689b5a-0c6f-49d0-81ef-bed0b7099aa6)
屏幕设置:
![image](https://github.com/WXRIW/Lyricify-App/assets/134820858/f1c8b17b-3c62-4e50-bdf9-5be0578df503)
![image](https://github.com/WXRIW/Lyricify-App/assets/134820858/3244c35e-8bcb-443e-867c-ddcec70da961)

**Comment by WXRIW** [comment]
这个问题我已经发现了很久了，但由于不怎么影响使用就没管。
这个异常是由上游造成的，目前不清楚是 WPF-UI 造成的还是 WPF 造成的。

**Comment by WXRIW** [comment]
已修复，请等待新版更新。
