### ISSUE TITLE
桌面歌词[总在最前]会失效

### ISSUE THREAD

**Issue by Risen-Ji** [WXRIW/Lyricify-App#34]
刚打开桌面歌词,[总在最前]功能是没问题的,过了大概十分钟左右,点击歌词界面下面的界面,歌词就会失去总在最前.
目前除了时间,还没发现其他的原因导致的这个问题,后续会继续观测,发现原因会po上来

**Comment by WXRIW** [comment]
@Risen-Ji 我自己这边目前还没出现过这个问题，等后续排查

**Comment by WXRIW** [comment]
@Risen-Ji 有无锁定桌面歌词

**Comment by Risen-Ji** [comment]
桌面歌词打开就锁定了,这半个小时暂时没有复现此问题,后续我再观测,看能否复现
