### ISSUE TITLE
桌面歌词支持固定字体大小

### ISSUE THREAD

**Issue by Fllly** [WXRIW/Lyricify-App#341]
希望桌面歌词可以支持直接调整字体大小，边框依据歌词字数进行自适应（为了避免特殊情况无法选中，可以预设一个最小值）。这也是主流播放器都在使用的歌词样式调整方式。

* 避免单句长词受边框限制而造成字体缩放
* 启用【透明隐藏】功能时，可直观感知触发范围

**Comment by WXRIW** [comment]
这个功能其实在 Lyricify 刚开发的时候我是有打算这样做的，但是现在再加上这个功能，则需要修改换行动画，与旧版本的动画有一定冲突。所以短期内没有相关计划，可能会在未来的 4.3，4.4 这样的大更新中提供这样的支持。
你还提到了透明隐藏功能的问题，这个问题制作起来也是比较困难的，在这个功能的开发初期，我确实是打算按照你这个想法来做，但是遇到了不少问题，比如涉及到尺寸计算，位置判断等等，而歌词还在不断变化，这对位置信息的及时更新都产生了不小的挑战，于是这个功能就搁置了，只完成了现在这样的效果。
你所提及的这两个问题都有可能会在未来版本得到改善，也可能不会得到改善，这取决于后期的时间与安排，感谢支持！

**Comment by WXRIW** [comment]
由于这个问题暂时没有解决计划，故做关闭处理，后续如有进展，将会重新开启。
