### ISSUE TITLE
[功能请求] 桌面歌词右键菜单扩展

### ISSUE THREAD

**Issue by Seayay** [WXRIW/Lyricify-App#342]
目前桌面歌词右键只有一个**水平居中**，希望可以在这个菜单中调整**歌词对齐方向**、**歌词单双行**设置

**Comment by WXRIW** [comment]
很不错的建议，将在新版本加入。

**Comment by WXRIW** [comment]
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/e702f870-2e59-4a98-85ce-1efb86612bdf)
已添加，将随新版发布。
