### ISSUE TITLE
Apple Music歌词模式忽然无法显示专辑封面，播放界面一片黑，重装软件重启电脑依然无法解决

### ISSUE THREAD

**Issue by LambortSSS** [WXRIW/Lyricify-App#343]
![Uploading Desktop Screenshot 2024.05.17 - 21.13.43.29.png…]()
![Uploading Desktop Screenshot 2024.05.17 - 21.13.52.13.png…]()

**Comment by WXRIW** [comment]
你的图片没有上传成功

**Comment by LambortSSS** [comment]
![1](https://github.com/WXRIW/Lyricify-App/assets/87907617/edddbe9c-f8f5-40d0-b366-c46c595348b1)
![2](https://github.com/WXRIW/Lyricify-App/assets/87907617/941726b6-7958-4bdd-a813-47b2bdd831d2)
不知道这样图片算不算上传成功了，Applemusic歌词的模式现在是时好时坏（刚刚好了一阵子，然后又黑了）

**Comment by WXRIW** [comment]
这种加载不出来基本是因为网不好，主界面的图加载出来了，因为那是一个分辨率较低的版本，对网络要求低。Apple Music 界面使用的是最高质量的图，对网络要求较高。
在使用指南里也写到了这个问题，要仔细阅读。

**Comment by LambortSSS** [comment]
好的，谢谢大佬
