### ISSUE TITLE
[BUG]桌面歌词能放大

### ISSUE THREAD

**Issue by Redappleyyds** [WXRIW/Lyricify-App#344]
打开桌面歌词
![image](https://github.com/WXRIW/Lyricify-App/assets/134820858/39a62398-ab8e-4d7f-945e-ee54d2d43b03)
拖到右边屏幕边缘
![image](https://github.com/WXRIW/Lyricify-App/assets/134820858/5d49a603-2a92-4f8c-bef7-dfca3d6bb08f)
最后
![image](https://github.com/WXRIW/Lyricify-App/assets/134820858/5055cd47-4a75-403a-ba4d-3b56920bb95f)

**Comment by WXRIW** [comment]
这个是正常情况，因为桌面歌词窗口的尺寸是可以改变的，所以就会出现 Snap。
