### ISSUE TITLE
Lyricify和Spotify的封面不同

### ISSUE THREAD

**Issue by ZhangJinyuJerry** [WXRIW/Lyricify-App#345]
![屏幕截图 2024-05-19 115158](https://github.com/WXRIW/Lyricify-App/assets/158539001/f5fceb9f-ab2c-486e-b3bd-41cd698b5de4)
此图上方为_Lyricify_，下方为_Spotify_

**Comment by WXRIW** [comment]
Lyricify 显示的是你播放曲目的图片，Spotify 显示的是你实际播放曲目的图片。如果想要他们一致，你需要在设置中开启使用重定向后的专辑图片。

**Comment by ZhangJinyuJerry** [comment]
> Lyricify 显示的是你播放曲目的图片，Spotify 显示的是你实际播放曲目的图片。如果想要他们一致，你需要在设置中开启使用重定向后的专辑图片。

好的，我来试试！

**Comment by ZhangJinyuJerry** [comment]
> Lyricify 显示的是你播放曲目的图片，Spotify 显示的是你实际播放曲目的图片。如果想要他们一致，你需要在设置中开启使用重定向后的专辑图片。

![image](https://github.com/WXRIW/Lyricify-App/assets/158539001/4532aecb-6175-436b-98c1-0096bbb83d78)
是这一项设置吗

**Comment by ZhangJinyuJerry** [comment]
> > Lyricify 显示的是你播放曲目的图片，Spotify 显示的是你实际播放曲目的图片。如果想要他们一致，你需要在设置中开启使用重定向后的专辑图片。
> 
> ![image](https://private-user-images.githubusercontent.com/158539001/331847011-4532aecb-6175-436b-98c1-0096bbb83d78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwOTMwNTIsIm5iZiI6MTcxNjA5Mjc1MiwicGF0aCI6Ii8xNTg1MzkwMDEvMzMxODQ3MDExLTQ1MzJhZWNiLTYxNzUtNDM2Yi05OGMxLTAwOTZiYmI4M2Q3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQwNDI1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmFiOTFiZDRhNmVkYWIwNmIxMDE4ZjliMjc1Y2Y3MTczZDlmYTkyMTQ4Zjk3MGI0MzU3NzA1YWZlYjgzYTYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CD2KHaqQJk_QjWD3zmE5ppuCLHvNX4fRX4nm2QYnvy8)是这一项设置吗

![image](https://github.com/WXRIW/Lyricify-App/assets/158539001/c63dcad4-b9f3-4799-9d94-5f4e5606e191)

**Comment by ZhangJinyuJerry** [comment]
> Lyricify 显示的是你播放曲目的图片，Spotify 显示的是你实际播放曲目的图片。如果想要他们一致，你需要在设置中开启使用重定向后的专辑图片。

![image](https://github.com/WXRIW/Lyricify-App/assets/158539001/919c3c5a-e7a4-4904-b138-e0fbff278296)
是这一项设置吗？

**Comment by ZhangJinyuJerry** [comment]
> Lyricify 显示的是你播放曲目的图片，Spotify 显示的是你实际播放曲目的图片。如果想要他们一致，你需要在设置中开启使用重定向后的专辑图片。

已经成功同步！
