### ISSUE TITLE
支持改变界面上的所有字体

### ISSUE THREAD

**Issue by ZhangJinyuJerry** [WXRIW/Lyricify-App#346]
**如果能实施一定会和朋友推荐！（超大声**
@WXRIW

**Comment by WXRIW** [comment]
@ZhangJinyuJerry 目前主歌词界面，Lyricify 全屏，桌面歌词均提供了自定义字体支持。其他界面短期内不会考虑开放字体自定义。

**Comment by ZhangJinyuJerry** [comment]
> @ZhangJinyuJerry 目前主歌词界面，Lyricify 全屏，桌面歌词均提供了自定义字体支持。其他界面短期内不会考虑开放字体自定义。

好吧）还是支持一下，加油做下去
