### ISSUE TITLE
BUG: Too great to use

### ISSUE THREAD

**Issue by tsavpyn** [WXRIW/Lyricify-App#347]
Dear Wang XY,

My name is Li Hua, and I am writing to report a serious bug founded a long time ago. 

This bug is found since the release of Lyricify 4

The only problem is it is too great to use and cannot even stop staring at it at work))

It may cause an employee fired as a result

Please fix this issue asap. Recommendation: Lock framerates to 30fps. 

Sincerely,

Li Hua

**Comment by Seayay** [comment]
@tsavpyn 假如你是李华……

**Comment by tsavpyn** [comment]
Absolutely! Amazing idea, Wang! You brought me a fresh morning shock! I would really appreciate it if it is possible to add this amazing new feature😊🙏

**Comment by WXRIW** [comment]
🙏Yes, with the amazing power Lyricify 4 delivers, we can make this limit happen!

**Comment by tsavpyn** [comment]
Great! I would be glad go see it appears at the bottom of the settings menu and made to be default😊👏

**Comment by WXRIW** [comment]
🙏So creative! Our team will do our best to accomplish this feat! Let's take a look at the new Lyricify!

**Comment by WXRIW** [comment]
Wow! Let's close this issue and see the amazing works done by Lyricify team.
🙏
