### ISSUE TITLE
Feature request: Apple Lyrics - Lyrics only view.

### ISSUE THREAD

**Issue by oldschoolvirgo** [WXRIW/Lyricify-App#348]
Would it be possible to have Apple Music type lyrics (syllable-synced, karaoke, sing, etc) in a full screen like below? Or an option to toggle the album cover art on/off in the Apple Music type lyrics. Thank you!

Screenshot of Apple Music lyrics: Would like to show/hide the album cover to make the lyrics fill screen.
![2024-05-22 16_52_43-](https://github.com/WXRIW/Lyricify-App/assets/126725107/55a9c961-321c-40a7-9f70-50d733c2d463)

Screenshot of full screen lyrics. Example of feature request: Album cover art is smaller and lyrics have more screen focus. 
![2024-05-22 16_54_43-Lyricify for Spotify](https://github.com/WXRIW/Lyricify-App/assets/126725107/b3bcf595-4157-4bca-910c-750f4383bd88)

**Comment by WXRIW** [comment]
It's just not possible. When the album cover is hiddened, the lyrics has to be centered, but in Apple Music Lyrics mode, the lyrics have to be left or right aligned, and cannot be centered. Also duet view will be lost. In Apple Music Lyrics mode, we just do what Apple does.

**Comment by oldschoolvirgo** [comment]
thank you for the explanation. fantastic work on this project. i will definitely be donating to the team.

**Comment by WXRIW** [comment]
Thanks for your understanding and support!
