### ISSUE TITLE
Linux 版本的相关计划

### ISSUE THREAD

**Issue by kerwin-zz** [WXRIW/Lyricify-App#35]
大佬何时能做个Linux版

**Comment by WXRIW** [comment]
@lz397548123 Linux 暂时没有计划，等 4.0 出来之后可能会找其他人来做，或者我自己学，但目前一年内没有这个计划，此 Issue 暂不关闭

**Comment by WXRIW** [comment]
暂不考虑 Linux，目前可以用 Wine 运行，此 Issue 关闭
