### ISSUE TITLE
视频（动态）封面？

### ISSUE THREAD

**Issue by YQCNM** [WXRIW/Lyricify-App#350]
提个建议 增加像AM一样的动态封面？
然后我在关闭的issue里看了看 #155 里面有一句 ”**视频比较占用服务器资源**“
那可不可以让用户自己下载动态封面，存在本地，然后导入到Lyricify内？
这样就不占用服务器资源了，然后不喜欢动态封面的用户也可以选择不导入

_然后我发现am的动态封面挺好下载的，用am网页端打开专辑页面，下载器就能嗅探到mp4_

**Comment by WXRIW** [comment]
目前不考虑提供，一是因为本地方案确实很麻烦，二是目前只想做成彩蛋形式，只给特定歌手提供。
