### ISSUE TITLE
關於Romaji的問題

### ISSUE THREAD

**Issue by NeKoOuO** [WXRIW/Lyricify-App#353]
想問現在靠的是機器翻譯嗎？ 如果是能否先用musix的romaji

例如 呪い 這個詞有兩種念法 noroi majinai
呪い在現代日語中較常被讀作 noroi「詛咒」；
但當加上前綴お時，お呪い一定讀做おまじない(omajinai)。
因此，majinai 更常用假名書寫。
可是機器翻譯的話就會有機率翻成majinai 導致看歌詞的時候就會有卡到的問題 因為唱的跟看的不一樣

**Comment by WXRIW** [comment]
现在使用的是 [Kawazu](https://github.com/Cutano/Kawazu) 转换。

**Comment by NeKoOuO** [comment]
瞭解,那請問有辦法調整優先級嗎？

**Comment by WXRIW** [comment]
没有优先级，所以罗马音均来自 Kawazu 的自动转换。

**Comment by NeKoOuO** [comment]
能增加 musixmatch的詞源嗎？

**Comment by WXRIW** [comment]
现在已经支持 Musixmatch 词库，但是所有词库的罗马音均来自自动转换，这是无法改变的。

**Comment by WXRIW** [comment]
是的，解决不了。除非能优化自动转换。

**Comment by NeKoOuO** [comment]
話說 他只有一種轉換功能嗎？ 因為我發現它主要是單個轉換
像是 二人（futari） 它的識別方式是分開轉換 二（ni）人（nin）
我想問有沒有用單字識別的模式...?

**Comment by WXRIW** [comment]
这个不是很清楚，我是直接把整句歌词丢进去，他会转换出整句的罗马音出来。

**Comment by NeKoOuO** [comment]
主要是平假名片假名都沒問題 但是漢字單個單個轉換沒看前後文很容易轉錯.... 所以才想說有沒有單詞轉換的模式
