### ISSUE TITLE
在切换 Apple Music 时加入过渡

### ISSUE THREAD

**Issue by ZhangJinyuJerry** [WXRIW/Lyricify-App#355]
如题，在切换时加入渐入渐出的效果

**Comment by WXRIW** [comment]
没看懂。

**Comment by ZhangJinyuJerry** [comment]
emm就是在进入这个apple music歌词的时候加动画

**Comment by WXRIW** [comment]
只能是现在这样，加动画会很卡的。

**Comment by ZhangJinyuJerry** [comment]
![屏幕截图 2024-06-01 131843](https://github.com/WXRIW/Lyricify-App/assets/158539001/e7be6fc8-ada1-4880-9f80-08bdf52ff268)

**Comment by WXRIW** [comment]
现在也已经有动画了，专辑封面有弹出动画。

**Comment by ZhangJinyuJerry** [comment]
👀好吧，但你动效做的也挺好的

**Comment by ZhangJinyuJerry** [comment]
![屏幕截图 2024-06-01 132058](https://github.com/WXRIW/Lyricify-App/assets/158539001/778910f1-8fa6-479a-9540-cf26f5e7b5b8)
话说这是啥问题）

**Comment by WXRIW** [comment]
卡了吧，你重开一下看看。

**Comment by ZhangJinyuJerry** [comment]
![image](https://github.com/WXRIW/Lyricify-App/assets/158539001/4b7c0999-2789-4ad5-89f9-1beb3553b520)
然后文字就到一起了

**Comment by WXRIW** [comment]
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/ebb9e6b1-4dcc-4f35-8576-e68dbd302098)
我这是好的。你什么配置

**Comment by ZhangJinyuJerry** [comment]
确实是卡了）

**Comment by ZhangJinyuJerry** [comment]
把能把这个的右键菜单ui
![屏幕截图 2024-06-01 132520](https://github.com/WXRIW/Lyricify-App/assets/158539001/f8a6d19b-8d3e-4582-994c-62cd544da654)
改成这个吗）））→←
![屏幕截图 2024-06-01 132527](https://github.com/WXRIW/Lyricify-App/assets/158539001/1034c548-0bc6-4872-9442-246240d60ff3)

**Comment by ZhangJinyuJerry** [comment]
👀

**Comment by ZhangJinyuJerry** [comment]
抱歉给你带来了不便，感谢回答🎉😃

**Comment by WXRIW** [comment]
图标不好看，而且加上透明度会比较丑，所以就没改了。然后这里的菜单跟主界面的歌词右键是一致的。
