### ISSUE TITLE
优化 Ctrl+滚轮 放大\缩小 Apple Music 歌词

### ISSUE THREAD

**Issue by ZhangJinyuJerry** [WXRIW/Lyricify-App#356]
在使用 Ctrl+滚轮 放大\缩小 Apple Music 歌词 时会被强制拉至歌词处，这样就会变得（如图1）：
![图1](https://github.com/WXRIW/Lyricify-App/assets/158539001/2ea4c127-4f8c-4853-ba4d-baa391c55806)
所以看着感觉很不好，希望能优化一下

**Comment by WXRIW** [comment]
这里设计的是调整大小时，会自动回到当前播放行。

**Comment by ZhangJinyuJerry** [comment]
但是因为使用滚轮会移动歌词，所以看起来很卡的样子

**Comment by WXRIW** [comment]
没有看懂你的诉求。可否描述的更具体些

**Comment by WXRIW** [comment]
由于没有进一步的描述，无法做出回应，Issue 做关闭处理。

**Comment by ZhangJinyuJerry** [comment]
emm

**Comment by ZhangJinyuJerry** [comment]
那边应该有个图片的，可以看一下）

**Comment by WXRIW** [comment]
图片中我没看出什么问题，我自己测试也没有发现什么问题。
