### ISSUE TITLE
“配置自定义 API Client”窗口标题栏颜色出现问题

### ISSUE THREAD

**Issue by ZhangJinyuJerry** [WXRIW/Lyricify-App#359]
![image](https://github.com/WXRIW/Lyricify-App/assets/158539001/5f3b149c-902e-4193-ab54-e90b63614446)

**Comment by ZhangJinyuJerry** [comment]
学校的电脑）
![image](https://github.com/WXRIW/Lyricify-App/assets/158539001/62b69f01-1b09-4052-97a0-1e138be1b36b)

**Comment by WXRIW** [comment]
系统问题，与 Lyricify 无关。
