### ISSUE TITLE
当 Spotify 播放广告时将 灵动岛词 暂时隐藏，播放结束后再次显示

### ISSUE THREAD

**Issue by ZhangJinyuJerry** [WXRIW/Lyricify-App#360]
现在的效果：
![屏幕截图 2024-06-08 131220](https://github.com/WXRIW/Lyricify-App/assets/158539001/90a4a5dc-d5a8-47de-81d8-3aee970118b7)

**Comment by WXRIW** [comment]
@ZhangJinyuJerry 广告不是歌曲，Lyricify 会自动丢弃这类信息，自然后就停留在上一首。
启动的时候也提示了，订阅 Spotify Premium 以获取最佳体验。故订阅即可。

**Comment by ZhangJinyuJerry** [comment]
okok
