### ISSUE TITLE
在播放下一首歌时，会在开头自动播放两次

### ISSUE THREAD

**Issue by Leonardo-Vito** [WXRIW/Lyricify-App#361]
人在澳洲，没有使用代理，每次在用Spotify的时候播放下一首的时候会重复播放开头两次。
例如：My enemy....(上一首）-> 苍茫的  |   苍茫的天涯是我的爱.....
如何修复这一问题？

**Comment by WXRIW** [comment]
参考 #305

**Comment by Leonardo-Vito** [comment]
> 参考 #305

感谢秒回，已经了解了
