### ISSUE TITLE
在本地更改歌词翻译的内容

### ISSUE THREAD

**Issue by nerine0** [WXRIW/Lyricify-App#362]
QQ和网易云上自动抓取的某些歌词翻译质量很差，想要反复听同一首歌的时候经常会被这些糟糕的翻译败坏心情。请问是否有可能出一个擦除服务器提供的翻译，应用用户自己的歌词翻译的功能？

**Comment by WXRIW** [comment]
这个功能非常小众，实现起来比较困难，且不符合 Lyricify 的歌词共享策略。目前歌词仅支持管理员进行删除操作，且歌词来源全部来源于 Lyricify 服务器或 QQ 音乐和网易云音乐服务器。

**Comment by WXRIW** [comment]
长时间没有回复，故做关闭处理。有任何问题可继续提问。
