### ISSUE TITLE
上传缺失歌词被告知上传请求被拒绝

### ISSUE THREAD

**Issue by IslandScientistKojima** [WXRIW/Lyricify-App#363]
碰到一首歌没有提供歌词，导入网易云歌曲id之后查询到应用于主屏幕之后歌词可以显示在主面板上，但是上传并储存的时候总是显示请求被拒绝，不知道为什么。
![屏幕截图 2024-06-13 015125](https://github.com/WXRIW/Lyricify-App/assets/116494122/03bdc2d3-922f-47b1-8596-a9bc6f0baa4e)

**Comment by WXRIW** [comment]
@IslandScientistKojima 请阅读 Lyricify 4 使用指南。

**Comment by IslandScientistKojima** [comment]
按照使用指南中的步骤进行了一遍仍然显示“上传请求被拒绝”。

**Comment by WXRIW** [comment]
@IslandScientistKojima https://github.com/WXRIW/Lyricify-App/blob/main/docs/Lyricify%204/README.md#%E6%97%A0%E6%B3%95%E5%9C%A8-%E6%9B%B2%E7%9B%AE%E7%AE%A1%E7%90%86-%E4%B8%AD%E4%B8%8A%E4%BC%A0%E6%AD%8C%E8%AF%8D

**Comment by IslandScientistKojima** [comment]
看来是新用户必须等一天后再上传歌词的意思对嘛
![Uploading 屏幕截图 2024-06-13 020824.png…]()

**Comment by WXRIW** [comment]
是的。所以说有一切问题，请先阅读使用指南。

**Comment by IslandScientistKojima** [comment]
初次使用lyricify望见谅，软件很实用，歌词很全，很喜欢。
