### ISSUE TITLE
Lyricify Mobile: Possible to move synced line down to middle of screen.

### ISSUE THREAD

**Issue by oldschoolvirgo** [WXRIW/Lyricify-App#365]
On Lyricify mobile, the synced line is almost to the top of the screen and making it difficult to see previous lines. 

Is it possible to move the line lower to see one or two previous lines?

Example screenshots are below:

Screenshot showing current version. Synced line is at the top of the screen.
![image](https://github.com/WXRIW/Lyricify-App/assets/126725107/6664d249-10de-47d7-b55c-a6b09e7e880c)

Screenshot showing feature request. Synced line is lower on the screen and previous lines are visible.
![image](https://github.com/WXRIW/Lyricify-App/assets/126725107/aa69a5f8-194a-471e-bfa3-9d46efd20241)

**Comment by WXRIW** [comment]
We are not planning to put the current playing line on the center of the screen. Lyricify Mobile follows the design of Apple Music, which means we just copy what Apple does on Apple Music.
