### ISSUE TITLE
非premium用户点击专辑播放/歌曲播放等需要premium支持才生效功能时,跳转Spotify

### ISSUE THREAD

**Issue by systemoutprintlnhelloworld** [WXRIW/Lyricify-App#366]
![image](https://github.com/WXRIW/Lyricify-App/assets/62531937/fc6cc3ca-ac6a-4a2b-b4ae-cfd503449593)
如图,在使用中由于spotify和lyrify同时需要打开,经常分不清哪个是哪个<s>或者心存侥幸想试试非会员能不能点</s>,直到产生下方红色提示才意识到不能点,并且右键菜单形式跳转很麻烦,相信点击播放直接弹出spotify能减少这个糟心过程消耗的时间

- 当然这个功能并不是所有人都需要的,可以作为一个选项供人打开

**Comment by WXRIW** [comment]
不考虑制作这个功能，除非你能够提供一个能够说服我且合理的理由。
因为 Lyricify 内部提供这个功能的本意是通过 Lyricify 显示更多信息，比如在艺人页可以更换区域查看，等等。
此外，你的逻辑是有问题的，点击就是应该打开对应页面，只有点击播放按钮时才是播放，也只有点击播放按钮时才会提示需要 Premium，而点击播放按钮并不具备跳转功能，所以你想要的功能在操作逻辑上有问题。

**Comment by WXRIW** [comment]
对于你的这个问题，我的建议是订阅 Spotify Premium。在 Lyricify 的右上角菜单里有“获取 Spotify Premium”的选项，可以通过这个选项的跳转地址购买会员。

**Comment by systemoutprintlnhelloworld** [comment]
> 此外，你的逻辑是有问题的，点击就是应该打开对应页面，只有点击播放按钮时才是播放，也只有点击播放按钮时才会提示需要 Premium，而点击播放按钮并不具备跳转功能，所以你想要的功能在操作逻辑上有问题。
![image](https://github.com/WXRIW/Lyricify-App/assets/62531937/4f02b135-f298-48de-b397-4d632164e2f2)
这里我指正一下,我指的是播放列表界面的和主界面的播放按钮
另外我的需求主要是

1. spotify和Lyricify两个软件我会选择其一放在任务栏,而往往我只会打开Lyricify

2. 点击触发失败后提示Premium并不是非Premium的我最期望的结果:  由于没有Premium是一个长期状态,点击播放提示需要Premium会让我很困惑,尽管第一次点时这确实起到了提示作用,但是之后我的期望是这个行为结果让我能打开spotify,而多点一下右键菜单-寻找到这个功能再打开这个过程就显得麻烦了,此外点击后打开spotify也是一种防呆设计,这样既不会让我点播放按钮成为无用功,也能提示我打开的并非是spotify

这是我的理由,如果不能说服你,就close了吧

**Comment by WXRIW** [comment]
## 经过慎重的考虑，我们做出以下回复

感谢您提交的建议以及对 Lyricify 的支持。

我们非常重视用户的反馈，并仔细阅读了您提出的需求。对于您所建议的功能，我们理解其重要性，但遗憾的是，现阶段我们无法在当前版本中实现。该功能涉及到一些技术限制，而这些限制在现有的框架下难以克服。

**不过，对于您提到的“经常分不清”的问题，我们可以考虑通过将 Free 用户的播放按钮变灰的方式来改进用户体验，这样可以在一定程度上缓解该问题。**

此外，您遇到的问题其实可以通过开通 Spotify Premium 轻松解决。Spotify Premium 用户不仅可以享受更高质量的音乐，还能无广告打扰地听歌。更重要的是，Lyricify 为 Premium 用户提供了最佳的歌词同步体验，能够更好地满足您的需求。

您可以通过 Lyricify 内的链接将您的 Spotify 升级为 Spotify Premium 订阅，这样不仅能支持 Spotify 和音乐创作者，还能享受到更多高级功能。

感谢您的理解与支持！期待您的继续使用和反馈。

祝好，
Lyricify 开发团队
