### ISSUE TITLE
Lyricify用户注册失败，尝试多次任没效果

### ISSUE THREAD

**Issue by ZhangJinyuJerry** [WXRIW/Lyricify-App#367]
https://github.com/WXRIW/Lyricify-App/assets/158539001/ca97a559-baaa-4152-a9b6-e1163d734f4e

**Comment by WXRIW** [comment]
加群看群公告。

**Comment by WXRIW** [comment]
Lyricify 服务器被攻击，Lyricify 服务目前不可用，恢复时间未知，最快 1 天后恢复。
现阶段，启动 Lyricify 4 时若提示无法找到账户是正常行为，在服务器正常工作后将恢复。
Lyricify server is under attack, Lyricify services are currently not available. The recovery time is unknown, and at least 1 day is needed for the recovery.
