### ISSUE TITLE
Hide tray icon

### ISSUE THREAD

**Issue by azhe403** [WXRIW/Lyricify-App#369]
When able hide tray icon, making **Lyricify** become more clean.

**Comment by WXRIW** [comment]
I don't think this is necessary, since Windows hides the tray icon by default in the taskbar. If you don't want to see the tray icon, just don't open the hidden tray icons area.

**Comment by WXRIW** [comment]
Lyricify's tray icon provides a lot of functions and needs to be integrated into the tray icon.

**Comment by WXRIW** [comment]
The issue is being closed since there's no reply for a long time, feel free to reopen this issue.
