### ISSUE TITLE
本地歌词无法标记

### ISSUE THREAD

**Issue by wrong5210** [WXRIW/Lyricify-App#37]
对于没有正确歌词的歌采用导入本地歌词的方法后，标记为正确的歌词，但是每次听歌词还是错误的，需要重新导入本地歌词，且不再出现标记按钮

**Comment by wrong5210** [comment]
另外循环播放一首歌曲，只有第一次会同步显示歌词

**Comment by WXRIW** [comment]
@wrong5210 仅登录 Spotify 后，或使用 iTunes, YesPlayMusic，才支持同步时间轴

**Comment by wrong5210** [comment]
> @wrong5210 仅登录 Spotify 后，或使用 iTunes, YesPlayMusic，才支持同步时间轴

谢谢，登陆之后上面两个问题都解决了，之前误以为是需要注册lyricify的账号所以一直没尝试过登陆

**Comment by wrong5210** [comment]
弄错了，第一个问题“对于没有正确歌词的歌采用导入本地歌词的方法后，标记为正确的歌词，但是每次听歌词还是错误的，需要重新导入本地歌词，且不再出现标记按钮”还是没有解决

**Comment by WXRIW** [comment]
本地歌词上传目前是关闭状态，这是因为本地歌词是不受信任的，所以目前只会接收 QQ 音乐或网易云音乐的歌词。
如果需要导入本地歌词，可以把歌词和歌曲信息（包括 id 和 isrc）发给我，我来上传服务器

**Comment by wrong5210** [comment]
> 本地歌词上传目前是关闭状态，这是因为本地歌词是不受信任的，所以目前只会接收 QQ 音乐或网易云音乐的歌词。 如果需要导入本地歌词，可以把歌词和歌曲信息（包括 id 和 isrc）发给我，我来上传服务器

**歌曲:** Lose Control
**专辑:** JJ Lin
**曲目编号:** 7
**ID:** 1Mut1YA6ZxKZ7F6MKsMSQu
**ISRC:** USUM72112429
**专辑 ID:** 2kAqjStKcwlDD59H0llhGC

歌词 https://raw.githubusercontent.com/wrong5210/Lyric/main/JJ%20Lin%20-%20Lose%20Control.lrc

**Comment by Prepanpan** [comment]
@wrong5210 歌曲: 我睡不著
专辑: 守夜人
曲目编号: 7 
ID: 1J707Wskr4x6JO9QwhiCm4
ISRC: TWCH51900001
专辑 ID: 6ZJk7O5Jf40ldannnGtYiO
详情：这首歌不是纯音乐

**Comment by WXRIW** [comment]
> @wrong5210 歌曲: 我睡不著 专辑: 守夜人 曲目编号: 7 ID: 1J707Wskr4x6JO9QwhiCm4 ISRC: TWCH51900001 专辑 ID: 6ZJk7O5Jf40ldannnGtYiO 详情：这首歌不是纯音乐

已作删除处理
