### ISSUE TITLE
灵动词岛影响某些游戏的HDR呈现

### ISSUE THREAD

**Issue by vcgms** [WXRIW/Lyricify-App#375]
当灵动词语岛为开启状态时（即使没有音乐播放，且全屏隐藏已打开），某些游戏（如：艾尔登法环）开启HDR后，仍会以SDR显示，颜色异常灰白。手动关闭灵动词岛开关，或者退出LyricifyApp后，切换回游戏恢复正常。

看着感觉像是在HDR游戏的界面上层，套了一层全屏的SDR叠加层。

**Comment by WXRIW** [comment]
@vcgms 我没有 HDR 屏幕来测试。我觉得这应该是 Windows 的问题。

**Comment by fred913** [comment]
@vcgms 能否尝试将游戏修改为无边框全屏，而非独占全屏后再试一下HDR是否正常

（个人理解 不一定可用 仅供参考）

**Comment by vcgms** [comment]
> @vcgms 我没有 HDR 屏幕来测试。我觉得这应该是 Windows 的问题。

估计也是，这个游戏不支持窗口化时开启HDR，但我也玩过有窗口化下支持HDR的游戏，估计是游戏没去支持

至少现在玩的时候不需要看歌词，快捷键关掉就好了
