### ISSUE TITLE
Lyricify V3.8.8 標記為正確歌詞程序閃退

### ISSUE THREAD

**Issue by whaleboss** [WXRIW/Lyricify-App#376]
播放音樂顯示的歌詞
有時候不是正確的歌詞
需要手動切換下一首
此時勾選"標記為正確歌詞"程序就會閃退跳出
變成每次播這首歌
都需要手動切換到正確歌詞
不確定是不是程序bug
請修復感謝

**Comment by whaleboss** [comment]
> @whaleboss Lyricify 3 的标记歌词功能已经关闭，所以是无法上传标记的。

比較好奇的是歌詞+1s, +0.1s, -1s, -0.1s的功能卻是正常的
不知道作法上差別在哪

**Comment by WXRIW** [comment]
@whaleboss 这个是本地的控制 不涉及服务器操作

**Comment by whaleboss** [comment]
> @whaleboss 这个是本地的控制 不涉及服务器操作

我也覺得是本地控制
只是不知道儲存(緩存)在哪裡
以及選取歌詞不知道能不能也改到本地控制

**Comment by WXRIW** [comment]
这个offset调节是不存储的，换歌之后就没了。

**Comment by WXRIW** [comment]
长时间没有回复，故 Issue 关闭。

P.S. Lyricify 3 已经进入 EOL，即生命周期已结束。后期不再进行新功能的开发及软件的维护。欢迎使用 Lyricify 4 以获得极佳歌词体验。
