### ISSUE TITLE
无法安装商店版本

### ISSUE THREAD

**Issue by Skinyi** [WXRIW/Lyricify-App#377]
之前一直用的从github上下的版本，后面支持作者买了商店版但是每次点商店的“安装”按钮都没有任何反应，卸载了直装版也没有解决问题。我使用的Windows是：Windows 11 版本 23h2 （内部版本：22631.3880）。

**Comment by WXRIW** [comment]
感谢你对 Lyricify 的支持。对于你反馈的这个问题，建议咨询 Microsoft，可尝试在 Microsoft 社区寻求帮助，这个是 Microsoft Store 的问题，Lyricify 这边实在无力解决，十分抱歉。
你也可以尝试调整网络相关配置，也许会有帮助。

**Comment by WXRIW** [comment]
鉴于长时间没有收到回复，故 Issue 关闭，如有更多问题，可继续提问。
