### ISSUE TITLE
Add lyrics share feature on lyricify mobile?

### ISSUE THREAD

**Issue by Krindog7337** [WXRIW/Lyricify-App#379]
This feature where user can longpress the lyrics and it selects the lyrics. Like in Spotify itself. Share it as picture, or directly send to any apps, with the link to Spotify songs. This feature shouldn't need premium account i guess.

**Comment by WXRIW** [comment]
This feature is only available on Lyricify 3 and Lyricify 4. And we are not planning to add this feature in Lyricify Mobile version 1. But on Lyricify Mobile version 2 (called Lyricify for Apple, the next generation of Lyricify on iOS and macOS), we will add this feature.

**Comment by Krindog7337** [comment]
Will lyricify mobile 2 available on Android?

**Comment by WXRIW** [comment]
No, only Apple platforms will be supported. Android's support will end at Lyricify Mobile 1.
