### ISSUE TITLE
灵动岛歌词中汉字显示需二次渲染

### ISSUE THREAD

**Issue by rakushuu** [WXRIW/Lyricify-App#380]
![01](https://github.com/user-attachments/assets/1f63b9f5-f5d4-40e2-bbb5-90106c9492c9)
![02](https://github.com/user-attachments/assets/cf39d5d0-3c8c-432f-a848-ba45a26ba336)
图一为未渲染汉字、图二为渲染后汉字，在每句中文歌词出现时都会二次渲染。

**Comment by WXRIW** [comment]
在低 DPI 下，这种情况是正常的。因为动画对内容渲染的影响，不是时刻都可以确保像素位置是对应的，所以在动画结束后，即画面停止时，文字会渲染成最清晰的渲染状态。

可以通过以下方法解决这个问题：
1. 将灵动词岛缩放调大，这样的渲染观感更好。
2. 使用更高 DPI 的屏幕配置。
3. 可尝试更换字体，如苹方，这可能会改善体验。

**Comment by WXRIW** [comment]
Issue 已解答，故做关闭处理。如有问题可重新开启。
