### ISSUE TITLE
桌面歌词未遵循罗马音显示设置

### ISSUE THREAD

**Issue by rakuzen25** [WXRIW/Lyricify-App#381]
当罗马音显示模式设置为“翻译优先”时，没有中文翻译的日语歌曲无法在桌面歌词显示罗马音。

![image](https://github.com/user-attachments/assets/15aa231f-5958-4028-856d-81bda7e6775a)

![image](https://github.com/user-attachments/assets/97f23dc0-8bad-4b16-b9a1-bbc6d641e676)

复现步骤：
1. 启用设置中的“中文翻译”，并将“罗马音”设置为“翻译优先”
2. 播放一首没有中文翻译的日语歌曲（例：[Kotone - 今回の騒動につきまして。](https://open.spotify.com/track/1DgpQpu0xqj1nh618nkuvd)）
3. 启用桌面歌词

预期结果：在没有中文翻译的情况下，桌面歌词应该显示罗马音

实际结果：只有一行原文，并没有任何翻译或罗马音

~~顺便要是能出一个三行模式就好了XD~~

**Comment by rakuzen25** [comment]
另外顺便提一句，似乎我的桌面歌词状态（是否启用、位置、大小）在电脑重启后会被重置，反而灵动岛歌词会自动启用，不知道是不是我设置的原因

**Comment by WXRIW** [comment]
@rakuzen25 已修复，微软商店已发布更新，GitHub 版本将于两天后更新。

**Comment by WXRIW** [comment]
> 另外顺便提一句，似乎我的桌面歌词状态（是否启用、位置、大小）在电脑重启后会被重置，反而灵动岛歌词会自动启用，不知道是不是我设置的原因

应该是重启前没有正确关闭 Lyricify 造成的。

**Comment by rakuzen25** [comment]
> > 另外顺便提一句，似乎我的桌面歌词状态（是否启用、位置、大小）在电脑重启后会被重置，反而灵动岛歌词会自动启用，不知道是不是我设置的原因
> 
> 应该是重启前没有正确关闭 Lyricify 造成的。

啊，需要每次重启之前先手动退出 Lyricify 吗？

**Comment by WXRIW** [comment]
@rakuzen25 只有关闭时才会保存这个设置，如果没有正常关闭，比如被 Windows 强行关闭，就会出现这种问题。我会尝试进行优化，但不保证有效。

**Comment by rakuzen25** [comment]
了解了，辛苦。不过如果我正常退出一次等 Lyricify 保存这个设置之后，后面非正常关闭还会被重置吗？

**Comment by WXRIW** [comment]
@rakuzen25 不会被重置，调用的是最后一次保存的信息。

**Comment by WXRIW** [comment]
Issue 已解决，故关闭。

**Comment by WXRIW** [comment]
> 另外顺便提一句，似乎我的桌面歌词状态（是否启用、位置、大小）在电脑重启后会被重置，反而灵动岛歌词会自动启用，不知道是不是我设置的原因

你有没有开启“点击关闭以隐藏”功能

**Comment by WXRIW** [comment]
> 另外顺便提一句，似乎我的桌面歌词状态（是否启用、位置、大小）在电脑重启后会被重置，反而灵动岛歌词会自动启用，不知道是不是我设置的原因

下一版本中将修复这个问题，可在更新后测试一下修复是否成功。
