### ISSUE TITLE
关于主界面（日语）歌词的小建议

### ISSUE THREAD

**Issue by Wesley10032** [WXRIW/Lyricify-App#382]
![image](https://github.com/user-attachments/assets/3b497981-be66-4310-a4c7-42ce2955c4ab)
建议可以在上图所示的歌词界面添加快速切换“罗马音”与“翻译”的按钮。
![image](https://github.com/user-attachments/assets/3834e95c-1a94-4367-a824-f711af8548c7)
例图，这是网易云音乐的歌词界面，右下角的“音”和“译”按钮分别可以显示罗马音和翻译。
而Lyricify可以将原文、翻译、罗马音三行并列，所以我希望出这么一个功能，灵活切换歌词显示方式。

**Comment by WXRIW** [comment]
不打算做这个功能，因为不是所有歌曲都支持音译切换，目前只有日语支持，按钮位置和 UI 设计将是个问题。
其次，可以通过 Alt+C 快速关闭翻译，就可以仅显示原文和罗马音，在设置里关闭罗马音后，也可以做到仅显示原文和翻译。
最后，也是最重要的，我不想添加更多日韩相关功能，所以目前不打算对日语增加更多支持，感谢理解。

**Comment by Wesley10032** [comment]
了解，开发者辛苦了。
