### ISSUE TITLE
win11安装不了

### ISSUE THREAD

**Issue by Jyuan-Ip** [WXRIW/Lyricify-App#384]
下载x64安装版，每次点进去安装都提示下面这个错误，不知道什么原因哇。绿色免安装也打不开，点击没反应。
![9cb0ea25-c92e-465b-8466-49c8514cf323](https://github.com/user-attachments/assets/f319cc38-b0c1-4214-9a3a-d2f52c473412)
![b89d2603-cf19-4aec-b933-f762ac8c7430](https://github.com/user-attachments/assets/6ba75f16-c297-4de9-b898-cbeba0493b11)

**Comment by WXRIW** [comment]
试试商店版

**Comment by WXRIW** [comment]
长时间没有回复，故 issue 关闭。
