### ISSUE TITLE
lyrics is not showing but just this text pops up

### ISSUE THREAD

**Issue by CartickKazama** [WXRIW/Lyricify-App#385]
![Screenshot 2024-08-14 100238](https://github.com/user-attachments/assets/01c4919d-8dc8-445f-a979-d6427ceceef1)

**Comment by WXRIW** [comment]
?

**Comment by WXRIW** [comment]
Here is Lyricify repo, your screenshot is Spotify.

**Comment by CartickKazama** [comment]
yep but the extension is of Lyricify-App and the version is from spicefy not original spotify

**Comment by WXRIW** [comment]
You are not using Lyricify

**Comment by CartickKazama** [comment]
https://github.com/spicetify/cli/tree/main/CustomApps/lyrics-plus

**Comment by WXRIW** [comment]
? this is not lyricify

**Comment by CartickKazama** [comment]
oh

**Comment by CartickKazama** [comment]
thanks for informing by the way

**Comment by WXRIW** [comment]
To use Lyricify, install the Lyricify app.
Get it here
https://apps.microsoft.com/store/detail/9P4WB75RHWCH?launch=true&mode=full
or
https://github.com/WXRIW/Lyricify-App/releases .
