### ISSUE TITLE
How to rebuild with this source code?

### ISSUE THREAD

**Issue by M1nCh3** [WXRIW/Lyricify-App#387]
im curious how to re-build this code? im so much curious how to connect with other then spotify?
please enlight me with the tutorial please
thankyou

**Comment by WXRIW** [comment]
Lyricify app is closed source, so there's no source code available here publicly. 
Lyricify Lyrics Helper is an open source project, you can find the source code under WXRIW/Lyricify-Lyrics-Helper.
