### ISSUE TITLE
移动端 Lyricify 可设置对唱视图

### ISSUE THREAD

**Issue by woshigenm** [WXRIW/Lyricify-App#389]
移动端 Lyricify 默认设置对唱视图，无法关闭导致歌词很奇怪
![4c205a1e2f879a0b82fff17cd77472e](https://github.com/user-attachments/assets/07b3d9d0-e30b-447f-b6a7-5a4a7247240b)

**Comment by WXRIW** [comment]
这个功能在 Mobile 上是没有提供设置项来关闭，且目前不考虑提供这个选项。
下一代 Mobile 应该会提供这个选项，不过因技术和成本原因，只会支持 Apple 设备，敬请期待。

**Comment by WXRIW** [comment]
长时间没有回复，且以提供解答，本 issue 做关闭处理。
