### ISSUE TITLE
双击打开提示服务器无连接

### ISSUE THREAD

**Issue by Risen-Ji** [WXRIW/Lyricify-App#39]
![QQ截图20211118140544](https://user-images.githubusercontent.com/73267635/142361957-fb308c60-1589-48ef-8fa5-3d7606a73a84.png)

**Comment by Risen-Ji** [comment]
电脑做了重启 打开也是依旧

**Comment by Risen-Ji** [comment]
网络无代理无VPN 公网正常

**Comment by Risen-Ji** [comment]
已恢复......

**Comment by Risen-Ji** [comment]
问题又出现 还是一样的提示 有时候能打开但是也是无法搜索到歌词

**Comment by DarkModest** [comment]
同样问题，挂了VPN也没有反应

**Comment by WXRIW** [comment]
服务器紧急故障，需要几天修复，造成不便希望各位能理解，谢谢！

**Comment by Risen-Ji** [comment]
作者开发辛苦了 少年英才 感谢分享

**Comment by WXRIW** [comment]
目前旧版本已恢复，故关闭此 Issue
