### ISSUE TITLE
靈動島問題

### ISSUE THREAD

**Issue by Michaelswift13** [WXRIW/Lyricify-App#392]
已支持創作者版本
靈動島設定了兩行，無法正常顯示
![螢幕擷取畫面 2024-08-25 214647](https://github.com/user-attachments/assets/6d546377-dfb6-4080-8fa2-8627f4f646d3)
另外左邊App icon可以隱藏嗎?

**Comment by WXRIW** [comment]
@Michaelswift13 感谢你对 Lyricify 的支持。
“总是显示两行”指的是在没有翻译的时候，下方会显示下一句歌词。如果有翻译，那么翻译会显示在第二行的位置。
对于左侧的 Lyricify Logo，目前没有移除的计划，它就像 iPhone 背面的 Apple Logo 一样，代表着 Lyricify App。

**Comment by Michaelswift13** [comment]
1h感謝回答，有時候左側圖示會跳成歌手個人照片，另外歌詞出現時間會比唱的快，或是比他晚，另外靈動島怎麼才可以讓它在下一句出來時不會回彈再彈出，這樣會讓我來不及看歌詞

**Comment by WXRIW** [comment]
在 #386 中我有详细讲到关于“灵动词岛”动画的问题。

**Comment by Michaelswift13** [comment]
謝謝，對於靈動詞島的詳細內容更了解了，也明白審美這事情(我也是設計師)，靈動詞島是否能做成上下卡像apple music那樣換字呢?呈現效果像下圖兩行歌詞，但下字換上去時，眼睛注意力不會跑掉(上滑動畫)
![image](https://github.com/user-attachments/assets/ff42f627-672d-46ef-94ab-49428981225b)

**Comment by Michaelswift13** [comment]
依我對apple靈動島的設定，一直都是左滑右滑收進去拉出來，都是長駐顯示的，一直以中心點彈出彈入，反而真的會跟不上歌詞，桌面歌詞跟靈動詞島的美差太多了，非常希望可以多一項切換動畫模式，這是能改善用戶體驗的功能，不影響舊用戶。

**Comment by WXRIW** [comment]
这个提议我之前也想到过，但是考虑到这样会导致含翻译和不含翻译的歌词动画不一致，当有翻译的时候还是需要完全缩放才能调整当前行内容，所有就没有这样做了。
不过我有计划研究更多动画，让背景人声歌词和多行高亮以更优雅的方式显示在灵动词岛中。

**Comment by WXRIW** [comment]
Issue 已提供解答，故做关闭处理。有问题可随时继续提问。
