### ISSUE TITLE
Your upload request has been denied

### ISSUE THREAD

**Issue by omaryomario** [WXRIW/Lyricify-App#396]
when i try uploading lyrics from spotify to lyricify-app it says that, also here: 
![image](https://github.com/user-attachments/assets/1c83877d-cca4-4217-87b4-a4b5b681d5a4)

**Comment by WXRIW** [comment]
For new users, lyrics uploading will be available in 24 hours after the first login.

**Comment by omaryomario** [comment]
> For new users, lyrics uploading will be available in 24 hours after the first login.

Cant i help with lyric-ing the songs in english and translating them possibly? I found the Chinese lyrics sites confusing when translated and so much complex stuff, i would like to know more about how uploading lyrics works.

if there is possibly a way to make me a lyric uploader i would like that!

**Comment by WXRIW** [comment]
Before your importation, Lyricify has noticed you about the rules:

Attention:
Do not manually import lyrics if QQ Music or Netease Cloud Music has the lyrics!
If the corresponding lyrics are not found through the search button on Lyricify, it does not mean that there are none. You need to manually search in the apps of QQ Music and NetEase Cloud Music to ensure that there are no corresponding lyrics before it can be considered as "no lyrics".
Your account might be limited if you violated this rule.

Here is the full version of [Lyricify Lyrics Vault's rules](https://github.com/WXRIW/Lyricify-App/blob/main/docs/Lyricify%204/README.md#lyricify-%E6%AD%8C%E8%AF%8D%E5%BA%93), the documents are in Simplified Chinese, use a translator if needed.
