### ISSUE TITLE
灵动岛歌词的几个建议

### ISSUE THREAD

**Issue by Timothyeee111** [WXRIW/Lyricify-App#398]
真的非常喜欢灵动岛功能，一直在用，但是看久了眼睛有点不舒服，有几个个人想法希望大佬可以参考下🌹
**1.**两行歌词模式下，歌词的替换动画是先向内缩小消失，在向外延伸展开。建议增加一个新的动画，两行歌词向上滚动，不要消失再出现的入场出场动画，那样看久了一闪一闪有点眼睛不舒服。（类似电影片尾的字母滚动，如果可以再dream一个”取消首行字体大，次行字体小”的设置）
**2.**灵动岛的显示区域希望可以给用户自定义固定大小，如遇到一行歌词太长，可以从左到右滚动歌词。（现有的灵动岛会随每行歌词的长度来拉长拉短显示宽度，个人觉得这个看久了眼睛有点痛）
**3.**希望可以给用户自定义选择是否显示灵动岛上的lyricify图标与专辑图标。
**4.**希望在原“鼠标停靠在灵动岛上自动隐藏”的基础上，增加一个设置：“鼠标靠近自动降低透明度”（同时，透明度可以给用户在设置中选择）

**Comment by WXRIW** [comment]
感谢你对 **灵动词岛** 的喜爱，对你提出的问题，回复如下：
1. 这样的动画效果很久之前就已有过构思，但是一直没有去实现，动画实现复杂度较高，所以具体何时能实现是个未知数，但是新的动画效果大概率会有的，且针对背景人声歌词会有优化。（关于两行字号的问题，因为相同字号下的显示比例无法达到我的审美要求，所以不会提供选项。）
2. 这个问题我在之前的 issues 里解答过。
3. 这个问题用户群里也有用户提出过，我的解答是，Lyricify logo 就像 iPhone 背面的 Apple logo 一样，是产品的象征，所以是不能去掉的。但是我会在 Lyricify Lite 发布前后为 Lyricify 4 上的灵动词岛提供单色 Logo 选项，在一定程度上提高美观度。
4. 如果只是提高透明度，我个人感觉作用不大，因为仍然会无法点击到下方内容，只有完全透明时才能实现下方内容的点击。

**Comment by WXRIW** [comment]
已提供回复，且长时间没有进一步反馈，故 issue 关闭，有任何问题可重新开启。
