### ISSUE TITLE
希望加入（非英文）歌词字体更换选项

### ISSUE THREAD

**Issue by SyuueenN** [WXRIW/Lyricify-App#40]
1、缺省回落的中文字体，日韩文汉字的显示会不太理想，出现字形不正确、中文假名形象差等问题。

![图片](https://user-images.githubusercontent.com/42110156/142612883-168289d0-ed76-43a3-a598-478b97d4491a.png)

2、Windows 下低分屏字体渲染至今十分糟糕，默认的「Microsoft YaHei UI」字体质量差，细体假名设计不统一（甚至比常规体粗）。我在电脑上使用了 MacType 插件改善字体渲染，但不会对 Lyricify 中的歌词起效。

![图片](https://user-images.githubusercontent.com/42110156/142612528-d54f4e02-da7c-4946-ad3b-dcc85ddfe1d3.png)

（英文歌词倒是一片岁月静好）

![图片](https://user-images.githubusercontent.com/42110156/142616257-a5cf669d-ab3a-47f2-a634-b42b7bf8f3e9.png)

以上，希望能帮助 Lyricify 更上一层楼，谢谢！

**Comment by WXRIW** [comment]
Windows 默认的日语字体是 Meiryo 吗？

**Comment by WXRIW** [comment]
Circular Sp UI v3 T Book, Segoe UI, Microsoft YaHei UI, Helvetica Neue, helvetica, arial, Microsoft JhengHei, PingFang TC, Lantinghei TC, Hiragino Kaku Gothic Pro, Meiryo, MS Gothic, sans-serif
这样的字体预设应该可以吧

**Comment by SyuueenN** [comment]
> Circular Sp UI v3 T Book, Segoe UI, Microsoft YaHei UI, Helvetica Neue, helvetica, arial, Microsoft JhengHei, PingFang TC, Lantinghei TC, Hiragino Kaku Gothic Pro, Meiryo, MS Gothic, sans-serif 这样的字体预设应该可以吧

请问这是回落列表吗？似乎不能起到选择字体适配多语言的作用欸，雅黑的字符集足够大，有搭载的话几乎所有汉字和假名就被挡在这里了。

如果是多种语言的回落列表拿来切换的话如何？

**Comment by SyuueenN** [comment]
> Windows 默认的日语字体是 Meiryo 吗？

Meiryo 是 Win7 及之前的默认了，Win 8 以后是 Yu Gothic。

**Comment by WXRIW** [comment]
上面的字体除了前三个，后面是和 Spotify 桌面版 css 文件里的字体顺序相同的

**Comment by SyuueenN** [comment]
🤣听起来炸出个大坑来。好的，谢谢费心了。

**Comment by WXRIW** [comment]
不谢，主要是这段时间忙，明年时间多些。
这个 Issue 放在这里，防止我明年忘记了😂

**Comment by WXRIW** [comment]
Lyricify 4.0 中已完成自定义字体的功能，此 Issue 关闭。
