### ISSUE TITLE
灵动词岛播客问题

### ISSUE THREAD

**Issue by Mirissa-Youth** [WXRIW/Lyricify-App#401]
当使用灵动词岛时，我在播放播客的（不播放歌曲）时，灵动词岛不隐藏，并显示上一首播放的歌的歌词，能不能改成显示播客转录

**Comment by WXRIW** [comment]
无法实现，Podcast 转录文本无法被直接获取，因为 QQ 音乐和网易云音乐并没有对应的播客。Spotify 会有一些 Podcast 的转译文本，但是接口不稳定，且文本量大，容易导致 Lyricify 4 处理缓慢或崩溃。所以无法使用。
补充说明：Lyricify 4 的逻辑是直接屏蔽 Podcast，所以在从歌曲转换到 Podcast 后，会停留在上一首歌曲的状态。
