### ISSUE TITLE
Lyricify 3 global shortcut 覆盖了原生文本的shortcut

### ISSUE THREAD

**Issue by jasper4ni** [WXRIW/Lyricify-App#402]
ctrl+right/ctrl+left 覆盖了文本编辑的 _moves the cursor one word to the right/left_ shortcut
在手动(高级)里更改了keybindings 的 `is_disabled: true` 或者把`key`改去别的键也是无法解决

**Comment by WXRIW** [comment]
Lyricify 3 已经进入 EOL，即结束生命周期。不再接受任何反馈，包括新功能请求和问题处理。
目前只有 Lyricify 4、Lyricify Mobile 和 Lyricify Lite 接受反馈，感谢理解。
