### ISSUE TITLE
Add Musixmatch as lyrics source

### ISSUE THREAD

**Issue by daniseis4** [WXRIW/Lyricify-App#403]
Hello I would like to add the [Musixmatch ](https://www.musixmatch.com/) service as optional, this service allows you to get the songs by API, here I leave a tutorial on how to extract the token for this API

https://gist.github.com/TrueMyst/0461aea999e347182486934fd83a4cf9

**Comment by WXRIW** [comment]
Lyricify has already integrated with Musixmatch.
![image](https://github.com/user-attachments/assets/6c286e31-bd09-4523-bc93-405e51592d61)

**Comment by daniseis4** [comment]
Sorry I didn't see that, but it doesn't work properly, could you allow us to add our own token?
other spotify apps allow you to do that and it works fine.

**Comment by WXRIW** [comment]
Lyricify gets Musixmatch tokens automatically. However, Musixmatch API is not stable, so the auto search might not work every time. FYI, Musixmatch is integrated as a backup source, so it has super low priority.

We are not planning to support token manual input, which does not fit with Lyricify's simple design concept.

P.S.
The Musixmatch part of Lyricify is open source in the [Lyricify Lyrics Helper](https://github.com/WXRIW/Lyricify-Lyrics-Helper) library.
https://github.com/WXRIW/Lyricify-Lyrics-Helper/blob/master/Lyricify.Lyrics.Helper/Providers/Web/MusixMatch/Api.cs
https://github.com/WXRIW/Lyricify-Lyrics-Helper/blob/master/Lyricify.Lyrics.Helper/Searchers/MusixmatchSearcher.cs
