### ISSUE TITLE
有计划开发MacOS专用版本吗

### ISSUE THREAD

**Issue by little6neko** [WXRIW/Lyricify-App#404]
类似MediaMate这种效果也挺好，虚拟机跑win版有时候切窗口就没置顶了
<img width="367" alt="sfx4paom 2si" src="https://github.com/user-attachments/assets/66d5be21-84f1-49b5-bbd5-84f4207c1cec">
<img width="741" alt="xm0e3sjx 1q2" src="https://github.com/user-attachments/assets/989bac59-6303-4074-9f33-c385efd0d7e8">

**Comment by WXRIW** [comment]
目前已经有 macOS 版了，Lyricify Mobile for macOS。

**Comment by little6neko** [comment]
> 目前已经有 macOS 版了，Lyricify Mobile for macOS。

Lyricify 4会考虑出吗，感觉灵动岛歌词更好看

**Comment by WXRIW** [comment]
1. Lyricify 数字系列就是给 Windows 用的，是不可能移植到 macOS 上的。
2. Lyricify 没有灵动岛歌词，但是 Lyricify 有灵动词岛。
3. 对于 macOS 版本，目前有长期规划。下一代 Lyricify Mobile 的 iOS 版和 macOS 版将进行重构，针对各平台进行优化。至少一年后才可能进入开发阶段，敬请期待。

**Comment by little6neko** [comment]
感谢作者耐心回复，期待下一代的版本
