### ISSUE TITLE
lyricify on apple silicon

### ISSUE THREAD

**Issue by owen-tariq** [WXRIW/Lyricify-App#405]
is there anyway to run lyricify on apple silicon (any kinda workarounds is fine)? 
except sideloading the ipa file please!!

**Comment by WXRIW** [comment]
Just use Lyricify Mobile for macOS, which is available for Apple silicon Macs.

**Comment by WXRIW** [comment]
Since there's no reply for a long time, this issue is being closed now. Feel free to comment again.
