### ISSUE TITLE
可以加入歌词修正功能吗

### ISSUE THREAD

**Issue by Linx3f** [WXRIW/Lyricify-App#407]
就是在桌面歌词提供±0.5s之类的时间修正，强迫症表示很需要/(ㄒoㄒ)/~~

**Comment by WXRIW** [comment]
@Linx3f 请使用曲目管理的 Offset 进行设置。

**Comment by WXRIW** [comment]
鉴于已经提供了解答，故 Issue 关闭，如有更多问题，欢迎继续提出。
