### ISSUE TITLE
希望在增加在任务栏上显示歌词

### ISSUE THREAD

**Issue by wh296248314** [WXRIW/Lyricify-App#41]
1、希望类似苹果系统中的BarTunes和LyricsX这两款软件
2、这样就可以所有Windows下音乐软件自动用这一个歌词软件
3、最好加一个联动功能，启动音乐播放器的时候，可以自动打开歌词工具
![image](https://user-images.githubusercontent.com/95277599/144013493-eab44a66-d10c-41cd-9293-017a864d5d27.png)

**Comment by WXRIW** [comment]
1. Windows 下几乎没有歌词软件会在任务栏显示歌词，并且在 Windows 11 中，无法在任务栏上添加自定义内容。
3. 可以反向，即打开 Lyricify 时自动打开 Spotify 或其他音乐软件。

**Comment by wh296248314** [comment]
反向也ok，这样就不需要打开两个软件了
