### ISSUE TITLE
自动更新后，点击图标无法启动

### ISSUE THREAD

**Issue by Nyeilim** [WXRIW/Lyricify-App#410]
中午刚下的 Lyricify.for.Spotify.Ver.4.3.16.241020-release.self-contained.x64 版本，我把自动更新关了。然后晚上开程序的时候，程序开始自动更新【是的，我记得我关了】，似乎替换了某些 .dll 文件【看了看似乎就在这几个小时内发布了新的版本？】，我的程序就打不开了。希望修复，并且想知道配置文件在哪？我不想再下新的 Portable 包再配置遍了...

**Comment by WXRIW** [comment]
self-contained 版本是自带运行库的版本，自动更新是不被支持的。（由于没有办法检测是否是 self-contained 的版本，所以会自动更新需要 .NET 运行库的版本，如果你的设备上没有运行库，那就会无法运行）
如果你已经把自动更新关闭，那么 Lyricify 一定不会进行自动更新，除非版本过低，你所使用的 4.3.16 并不是过低的版本，所以不会被强制更新，所以一定是没有关闭自动更新。
另外从你的反馈中猜测，你混淆了 self-contained 包和 Portable 包，他们是不同的。

**Comment by Nyeilim** [comment]
配置文件已迁移，打开配置看了看，“自动更新”确实是我记错了。感谢解答❤️。
