### ISSUE TITLE
歌曲不同步

### ISSUE THREAD

**Issue by systemoutprintlnhelloworld** [WXRIW/Lyricify-App#411]
![image](https://github.com/user-attachments/assets/aa381f45-72f1-4c50-8c87-dea32cd98ec1)
显示media session 未连接,我手机上播的歌能同步,电脑的就是同步不了,切歌,两个应用重启都没用

**Comment by WXRIW** [comment]
请阅读使用指南。

**Comment by systemoutprintlnhelloworld** [comment]
谢谢，已解决



---原始邮件---
发件人: "XY ***@***.***&gt;
发送时间: 2024年11月9日(周六) 晚上7:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WXRIW/Lyricify-App] 歌曲不同步 (Issue #411)




 
请阅读使用指南。
