### ISSUE TITLE
[Feature Request]关于Lyricify Mobile的桌面歌词like的一种实现方案

### ISSUE THREAD

**Issue by PianCat** [WXRIW/Lyricify-App#413]
使用画中画的实现方案，这样就能在安卓和iOS上同时兼容了🤔

如灵动歌词的悬浮窗模式：

![2464d8fb051adf1a13295bb71a8bfcb8](https://github.com/user-attachments/assets/8f33712d-792f-44a8-ab35-a100116a5ee9)

**Comment by WXRIW** [comment]
下一代 Mobile 会提供 PIP，敬请期待。

**Comment by WXRIW** [comment]
@PianCat 下一代 Mobile 会放弃 Android 支持，仅提供 Apple 平台相关版本。
