### ISSUE TITLE
版本升级

### ISSUE THREAD

**Issue by xiaoyugoodboy** [WXRIW/Lyricify-App#414]
打扰一下，作者大大，你好，请问这个插件，后续会不会支持网易，qq音乐这些。因为我使用3.8.8这些低版本，优化太差。最新版本，优化挺好的，就是不支持网易呀，qq音乐这些。请问作者有适配计划嘛。

**Comment by WXRIW** [comment]
在 Lyricify 4 使用指南和 Lyricify 3 使用指南里已经详细写明了不会去适配。即将发布的 Lyricify Lite 已支持 QQ 音乐和网易云音乐 UWP 版。
