### ISSUE TITLE
如何重新标记

### ISSUE THREAD

**Issue by Nyeilim** [WXRIW/Lyricify-App#415]
有些歌词被标记到 QQ 音乐上但是没有歌词，如何重新标记？
QQ 音乐 Mid：002bYknm2LcKr4；标记正确但是没有歌词
网易云音乐 Id：2132326049；标记正确且有歌词
![image](https://github.com/user-attachments/assets/d635c7e1-fa07-4c68-b9a9-73f6a90f5990)

第一次使用 Lyricify 自带的搜索功能进行标记，不太会用。
在这种情况下，如何删除 QQ 音乐的标记，使 Lyricify 使用网易云音乐的歌词？
有考虑做“本地标记”的功能吗，标错后才发现这个“上传”是传到公用服务器，能否在本地进行歌曲歌词的匹配？

**Comment by WXRIW** [comment]
@Nyeilim 先发一下歌曲链接。

**Comment by Nyeilim** [comment]
> @Nyeilim 先发一下歌曲链接。

要哪个链接？
QQ 音乐链接：https://y.qq.com/n/ryqq/songDetail/002bYknm2LcKr4
网易云音乐链接：https://music.163.com/#/song?id=2132326049
Spotify 链接：https://open.spotify.com/track/106aHqZDXhBOsmLpnHg74L

**Comment by WXRIW** [comment]
看了一下，QQ 音乐歌曲正确，有歌词，但歌词错误。这种情况只能联系管理员进行删除操作。所以在进行任何标记和上传前都一定要检查好是否正确，不然会带来很多麻烦。
至于你提到的本地标记，Lyricify 是不考虑的，这会让歌词逻辑更混乱，也违反了 Lyricify 的歌词共享原则。

**Comment by WXRIW** [comment]
目前已删除 QQ 音乐的歌词，本 Issue 关闭。
