### ISSUE TITLE
希望能添加一个启动后自动最小化到通知栏的功能

### ISSUE THREAD

**Issue by DeliciousLiMiao** [WXRIW/Lyricify-App#419]
使用的是Lyricify 4，这样如果只使用桌面歌词或者灵动岛歌词的就更方便了，已标星，希望大佬添加

**Comment by WXRIW** [comment]
这样不方便展示启动状态，如果遇到了启动错误，就不好展示了。且这个功能最大的用处是开机自启时静默启动，但是 Lyricify 4 因网络需求，无法广泛的支持开机自启，所以目前这个功能暂不考虑。
以后有可能会考虑此功能，目前 Lyricify Lite 的逻辑是符合你的需求的，可以去试试看。
另外，你提到的第二个歌词功能叫做**灵动词岛**，详见文档 [Lyricify 名词](https://github.com/WXRIW/Lyricify-App/blob/main/docs/Lyricify%204/README.md#lyricify-%E5%90%8D%E8%AF%8D)。
