### ISSUE TITLE
增加Source選項?

### ISSUE THREAD

**Issue by usaywat** [WXRIW/Lyricify-App#42]
你好，可以增加Source選項嗎? 有些英文和粵語歌曲在選擇Get From Spotify的時候，不是沒有就是錯誤的同名歌詞，或者滾動不同步（就算修正保存了下次還是一樣）。

不太清楚提供什麼可以幫到你，但我平時常用的歌詞源有[Musixmatch](https://www.musixmatch.com/)（和Spotify綁定一起的歌詞網站）、[Genius](https://genius.com/)（號稱自己全網最全）、[魔鏡Mojim](http://mojim.com/)（我用了多年的中文歌詞網）。另外還找了不知道有沒有用的[API名單](https://rapidapi.com/blog/top-free-music-data-apis/)。

**Comment by WXRIW** [comment]
目前 Source 只有 QQ 音乐，网易云需要手动导入，本地歌词默认不支持上传，可以在导入本地歌词之后多按几次标记，这样就会上传到服务器，下次就是正确的了。
应该说 Musixmatch 词库相当大，我也可以做到接入，但是接入 Musixmatch 是需要付费的，不然有每月访问限制，并且只能获取不完整歌词，也获取不到实时歌词（即有时间轴的歌词）。所以目前使用 QQ音乐、网易云音乐的分享链接导入是最推荐的，如果没有可以导入本地歌词文件，并标记，如果无法标记，可以发上来，我直接放在服务器上。
4.0 有几率考虑接 Musixmatch 词库。

**Comment by WXRIW** [comment]
Lyricify 4.0 将提供完善的词库功能，此 Issue 关闭。
