### ISSUE TITLE
這個軟件會導致CS2 出現VAC禁止遊戲 

### ISSUE THREAD

**Issue by Szeto0524** [WXRIW/Lyricify-App#422]
之前玩CS的時候當我下載了這個軟件 會出現vac無法驗證你的工作階段 
我好奇是在window註冊了什麼代碼所以導致呢

**Comment by WXRIW** [comment]
@Szeto0524 我觉得这不是 Lyricify 的问题，我也想不到是什么原因导致的。

**Comment by WXRIW** [comment]
长时间没有回复，故 issue 关闭。如有其他问题，欢迎重新打开。
