### ISSUE TITLE
请求添加息屏歌词和蓝牙歌词

### ISSUE THREAD

**Issue by JayYu998** [WXRIW/Lyricify-App#423]
目前歌词只能在软件内显示，希望可以加入息屏滚动显示和其他蓝牙设备显示，提高软件使用效率

**Comment by WXRIW** [comment]
@JayYu998 你指的哪个软件？

**Comment by JayYu998** [comment]
Lyricify Mobile

**Comment by WXRIW** [comment]
@JayYu998 息屏显示 iOS 做不到，所以不考虑。
蓝牙设备显示，Lyricify 是歌词软件，不是播放器，做不到。

**Comment by JayYu998** [comment]
好吧谢谢
