### ISSUE TITLE
希望可以静默开机自启

### ISSUE THREAD

**Issue by zhuzh3378** [WXRIW/Lyricify-App#425]
Lyricify重度使用者，手动添加开机自启后开机有点占地方，希望可以静默开机自启。感谢！

**Comment by WXRIW** [comment]
Lyricify 4 一直没有添加开机自启功能，是因为启动不一定能成功，不能给用户直观的反馈，这在开机时尤为重要。
教程中提到了手动启用的办法，是因为确实有用户想要开机自启。没有把这个功能直接放进设置里是因为他并不好用。Lyricify Lite 对网络依赖很低，不会出现无法启动的问题，所以官方就支持了开机自启功能。
所以你提到的静默启动也不会考虑，因为 Lyricify 4 并不支持开机自启，也并不知道你设置的启动项是开机自启的还是正常启动。
只有当 Lyricify 4 在开机时启动足够完美，正式加入了内置开机自启功能后，才会提供你想要的静默启动功能，感谢理解！
