### ISSUE TITLE
Lyricify Lite在使用网易云音乐无法正确出现灵动词岛的问题

### ISSUE THREAD

**Issue by Vanilluv** [WXRIW/Lyricify-App#429]
![QQ20241227-151411](https://github.com/user-attachments/assets/7a758a9c-0620-4194-adc6-afa8cc34f4b6)
如上图，网易云音乐已经正确安装BetterNCM以及InfLink，在Lyricify Lite的“调试”页面中，“歌词”页面能正确显示歌词，“会话”页面为空
![image](https://github.com/user-attachments/assets/af9fc283-3b6d-45ff-9e17-b0070b6307ef)
![image](https://github.com/user-attachments/assets/318f7579-02cd-4ea8-93ee-af1968a0f69d)

![image](https://github.com/user-attachments/assets/2ff04c60-31d4-4b66-8a05-17f11ba11c96)
在Lyricify Lite的“逐应用设置”中，也已经正确打开开关

网易云音乐版本：3.1.2 (64位) (Build:203359) Patch:b696f36
BetterNCM版本：1.3.4
Lyricify Lite版本：1.0.1.241225-release (64 位)

**Comment by Vanilluv** [comment]
补充：后续尝试Spotify，在调试窗口“会话”中，能正确识别Spotify的播放，但是仍然不出现灵动词岛
![image](https://github.com/user-attachments/assets/f76993ef-5383-4635-89d3-3c3b516a6795)
![image](https://github.com/user-attachments/assets/a2c1f2e5-4f6c-4754-9bfd-99c5323b9389)
![image](https://github.com/user-attachments/assets/5b9c1a6b-8b9b-4cc3-8bd9-59867e3265d6)

**Comment by WXRIW** [comment]
尝试关闭自动隐藏和全屏隐藏

**Comment by Vanilluv** [comment]
好的，非常感谢，已解决，发现是与NVIDIA Overlay的问题，由于NVIDIA Overlay在开启录制的情况下为全屏，因此导致Lyricify Lite识别有全屏窗口导致隐藏。

**Comment by WXRIW** [comment]
OK，感谢你的反馈！
