### ISSUE TITLE
一直卡在获取信息界面

### ISSUE THREAD

**Issue by rapon233** [WXRIW/Lyricify-App#43]
今天更新到3.7之后出现问题
![image](https://user-images.githubusercontent.com/55471403/148371710-fb132498-70e6-47b7-88d7-9cfe6d63ab39.png)

目前spotify正常播放，Lyricify已登录Spotify 可以拉取听歌分析等信息
之前的3.6版本也可以

环境： Win7
有部署防火墙

**Comment by WXRIW** [comment]
@rapon233 测试下同时打开3.7和3.6

**Comment by rapon233** [comment]
不能同时安装吧，我这里测试3.6正常
3.6.4也不行
其他没有更多测试了

**Comment by WXRIW** [comment]
不能同时安装多版本，可以使用绿色版：
[v3.6.4](https://github.com/WXRIW/Lyricify-App/releases/download/v3.6.0.4/Lyricify.Ver.3.6.0.4-release.zip)
[v3.6.0](https://github.com/WXRIW/Lyricify-App/releases/download/v3.6.0/Lyricify.Ver.3.6.0-release.zip)

**Comment by WXRIW** [comment]
同时打开这三个版本，看是否是都不能获取到

**Comment by rapon233** [comment]
![image](https://user-images.githubusercontent.com/55471403/148491127-e4161f07-8e4a-4f10-8e17-26cb30ba8031.png)
还是只有3.6可以

**Comment by WXRIW** [comment]
@rapon233 奇怪

**Comment by WXRIW** [comment]
@rapon233 试试看这样：先全部关掉，然后打开 3.7.0，然后打开菜单—>设置—>手动（高级），把第一项 is_use_media_session 右边的 true 改为 false，保存之后重新打开 3.7.0 试试看

**Comment by rapon233** [comment]
默认就是false，修改true/false都不行

**Comment by WXRIW** [comment]
@rapon233 试试看网页版播放的时候能不能获取到

**Comment by rapon233** [comment]
网页版和之前的情况一样
3.6正常获取歌词 3.7不行

**Comment by rapon233** [comment]
重登录过几次了，等等看有没有类似情况吧
先用着3.6

**Comment by WXRIW** [comment]
目前已找到问题，预计本周修复

**Comment by WXRIW** [comment]
v3.7.1 中已修复
