### ISSUE TITLE
[功能建议] 歌单内可以进行排序

### ISSUE THREAD

**Issue by PhantomPixel-0418** [WXRIW/Lyricify-App#430]
![image](https://github.com/user-attachments/assets/d32c8fd1-d456-4f09-9856-d2fab7b6b84c)
可以向spotify一样按照歌曲首字母、歌曲专辑首字母、添加时间进行歌单歌曲的排序

**Comment by WXRIW** [comment]
排序后将丢失播放功能，所以目前不考虑。
