### ISSUE TITLE
windows上lyricfy lite灵动岛不显示歌词

### ISSUE THREAD

**Issue by SYuan03** [WXRIW/Lyricify-App#434]
![image](https://github.com/user-attachments/assets/ac831252-dccb-4982-9009-12cd8514b921)
参考了https://github.com/WXRIW/Lyricify-App/issues/429
关闭了全屏隐藏似乎也没用，检测不到正在播放的网易云音乐应用？

**Comment by WXRIW** [comment]
请参考使用指南。

**Comment by SYuan03** [comment]
> 请参考使用指南。

sry，看到了，感谢！
