### ISSUE TITLE
enhancement，不知道是不是bug

### ISSUE THREAD

**Issue by AmorFati-coder** [WXRIW/Lyricify-App#44]
> 关闭Lyricity歌词工具后，apple music 附加组件，仍然运行
然后重新打开Lyricity，就是下图这个样子了
![](https://gitee.com/AmorFati-coder/pictures/raw/master/img/微信截图_20220107094403.png)
![](https://gitee.com/AmorFati-coder/pictures/raw/master/img/微信截图_20220107093902.png)

**Comment by WXRIW** [comment]
本来是打算在关闭主窗体后自动关闭 Apple Music 歌词的，但是后来去除了，允许 Apple Music 独立运行，但是独立运行时如果专辑图片之前没有缓存，则会仍然显示上一张图
