### ISSUE TITLE
如何获取有翻译歌曲的lrc格式文件？

### ISSUE THREAD

**Issue by cyhzm** [WXRIW/Lyricify-App#46]
如题

**Comment by WXRIW** [comment]
翻译暂不支持，只可保存原歌词

**Comment by cyhzm** [comment]
好吧


---原始邮件---
发件人: &quot;XY ***@***.***&gt;
发送时间: 2022年2月6日(周日) 晚上9:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WXRIW/Lyricify-App] 如何获取有翻译歌曲的lrc格式文件？ (Issue #46)




 
翻译暂不支持，只可保存原歌词
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
