### ISSUE TITLE
改进建议：桌面歌词暂停时自动隐藏；鼠标经过时自动隐藏；支持自定义字体；

### ISSUE THREAD

**Issue by CharWong** [WXRIW/Lyricify-App#47]
1. 建议增加桌面歌词在歌曲暂停时自动隐藏功能；
2. 建议增加鼠标经过桌面歌词时可以自动隐藏
3. 希望桌面歌词可以自定义字体。

1和2是希望借鉴Mac平台的同功能软件[LyricsX](https://github.com/ddddxxx/LyricsX)
3则是觉得一直用黑体太丑了（哪怕是微软雅黑

再次为作为高中生的作者点赞！祝高考顺利，未来可期！

**Comment by WXRIW** [comment]
@CharWong 4.0的时候完成

**Comment by WXRIW** [comment]
Lyricify 4.0 中已完成 3，此 Issue 关闭。
1 暂不考虑，2 在桌面歌词中不提供，但在灵动词岛中提供。
