### ISSUE TITLE
[词不对曲] 假如让我说下去-杨千嬅 2002 万紫千红演唱会

### ISSUE THREAD

**Issue by MMMMMileS** [WXRIW/Lyricify-App#48]
**歌曲:** 
**歌手:** 
**曲目编号:** 
**ID:** 
**ISRC:** 
**专辑 ID:** 
**详情:** 词不对曲
且导入正确后重新播放无法默认上次导入的正确歌词

该曲的正确歌词应对照网易云中：
https://music.163.com/#/song?id=317247

在APP端复制后不显示歌曲信息，原因可能是QQ音乐未收录该歌曲

**Comment by WXRIW** [comment]
@MMMMMileS 错误歌词不要新开issue，不受理
