### ISSUE TITLE
对于移动端UI全屏建议

### ISSUE THREAD

**Issue by MJscofield** [WXRIW/Lyricify-App#5]
您好,我对于移动端歌词全屏建议加一个常显的功能?就是现实移动端歌词全屏的时候能不能让电脑屏幕做到一直显示
![image](https://user-images.githubusercontent.com/55172641/109512285-e815c000-7ade-11eb-831b-bab5cc81a641.png)
![Uploading 微信截图_20210301223958.png…]()

**Comment by WXRIW** [comment]
以后会有的！我也是昨天自己在用的时候发现这个问题的，突然黑屏确实有点难受。但是现在电脑在维修，并且学习比较忙，暂时写不了，可能要等一段时间，可能要等到清明节放假才有空写。感谢您对Lyricify的支持！如果有更多意见和建议也欢迎反馈！Lyricify因你们而变得更好！

**Comment by MJscofield** [comment]
非常感谢你及时的回复,同为一个计算机专业的学生,深知独立创作多么不易,希望你能够一直坚持下去!目前我没有收入来源,所以只能捐赠一点小小心意,希望你能够在未来学习路上一切顺利,广阔天地,大有作为! 
![Uploading image.png…]()
![微信图片_20210301232318](https://user-images.githubusercontent.com/55172641/109518403-2d3cf080-7ae5-11eb-9e61-f5d7ec010d1b.jpg)

**Comment by MJscofield** [comment]
非常感谢你及时的回复,同为一个计算机专业的学生,深知独立创作多么不易,希望你能够一直坚持下去!目前我没有收入来源,所以只能捐赠一点小小心意,希望你能够在未来学习路上一切顺利,广阔天地,大有作为![image:
image.png]

XY Wang <notifications@github.com> 于2021年3月1日周一 下午11:06写道：

**Comment by WXRIW** [comment]
感谢您的捐助，Lyricify因你而更好！感谢使用Lyricify。也欢迎您把他推荐给朋友使用！这将给我很大帮助。谢谢！

**Comment by WXRIW** [comment]
此功能我已经写好了，但是还没有测试，过段时间我有空的时候测试完，跟随其他新功能一起发布！感谢支持哦！

**Comment by WXRIW** [comment]
已发布更新，欢迎测试！
