### ISSUE TITLE
AppleMusic歌词背景切换问题

### ISSUE THREAD

**Issue by innld** [WXRIW/Lyricify-App#52]
本人在使用Spotify桌面端，Lyricify中开启Apple Music歌词模式，有的时候切歌歌词切换了但歌词的背景不会自动切换，建议在使用F5键刷新的时候也让背景刷新一下，谢谢大佬

**Comment by WXRIW** [comment]
@innld 是专辑图片还是背景模糊的图

**Comment by innld** [comment]
@WXRIW  背景模糊的图

**Comment by WXRIW** [comment]
@innld 主窗体的图是否正常

**Comment by WXRIW** [comment]
@innld 背景

**Comment by innld** [comment]
主窗体是正常的

**Comment by WXRIW** [comment]
@innld 等待后续修复

**Comment by innld** [comment]
好的 谢谢大佬
