### ISSUE TITLE
Bug反馈以及新功能建议

### ISSUE THREAD

**Issue by abbaccadd0** [WXRIW/Lyricify-App#53]
# Bug反馈

1. 歌词与歌曲完全不匹配

    - 描述：歌词与歌曲完全不匹配，二者的曲名演唱者所属专辑完全不同，如图所示：
![Snipaste_2022-05-10_19-24-38](https://user-images.githubusercontent.com/39579855/167617879-6d1067fa-d799-47ad-8062-88d5c5c4fddf.png)
![Snipaste_2022-05-10_19-26-51](https://user-images.githubusercontent.com/39579855/167618269-b853f978-3712-4a9c-8884-0fdd3435c801.png)
![Snipaste_2022-05-10_19-40-23](https://user-images.githubusercontent.com/39579855/167620317-7fc72c2a-a037-4441-b551-e7d7e8a841ec.png)
 **这个问题十分严重……错误量大的惊人，有可能是……个例？** 

2. 歌曲同名时，无法找到对应作者的歌词

    - 描述：歌曲同名时，无法根据作者找到对应的歌词，如图所示：
![Snipaste_2022-05-10_19-29-15](https://user-images.githubusercontent.com/39579855/167618689-b7c256e3-1fe5-4f2d-8da7-f1ebce1e5d93.png)

3. 当手动切换到下一首歌曲时，有时会显示上一首歌曲的歌词

    - 描述：当手动切换到下一首歌曲时，有时会显示上一首歌曲的歌词，如图所示：
![Snipaste_2022-05-10_19-33-09](https://user-images.githubusercontent.com/39579855/167619507-76446ec7-8195-4112-9a3c-012ff789c0ee.png)
这是上一首曲子
![Snipaste_2022-05-10_19-33-35](https://user-images.githubusercontent.com/39579855/167619555-f2e91d4f-7ad9-4674-9ec4-76b936eb14c5.png)
这是手动切换到下一首曲子时显示的歌词
当然，这两首歌曲的歌词也都是错的，实际上他们都是纯音乐。

4. 当音乐被暂停时，歌词依然在滚动

    - 描述：当歌曲被暂停时，歌词依然在滚动，且无法停止
![Snipaste_2022-05-10_20-12-01](https://user-images.githubusercontent.com/39579855/167625410-8195f8af-7516-41c9-8909-cff7ad1bf178.png)
![Snipaste_2022-05-10_20-12-07](https://user-images.githubusercontent.com/39579855/167625434-9a7a31eb-fa63-41c5-8805-e7eb9dc8fd01.png)
当然，这首歌曲的歌词，也是错的……

5. 点击标记为纯音乐后，什么都没有发生

    - 描述：点击标记为纯音乐后，什么都没有发生，依旧滚动着错误的歌词

# 新功能建议

1. 桌面歌词设置
    - 预览：
![图片1](https://user-images.githubusercontent.com/39579855/167641548-a50d0862-3fb9-47eb-8291-a2a2d542e261.png)
    - 新增功能：调整字体字号，调整显示行数与对齐方式，调整正在播放与下一句歌词的颜色，调整阴影大小、颜色与透明度，自动将桌面歌词对齐到桌面
2. 点击关闭按钮时，自动最小化到任务托盘
3. 歌词搜索新增网易云音乐的歌词
4. 当音乐为纯音乐时，显示为纯音乐，而非“这首歌的歌词暂时无法找到。”

**Comment by WXRIW** [comment]
桌面歌词：目前更改字体可以通过带参数启动来实现（在 GitHub Wiki 里有具体说明）
更改字号可通过纵向拉伸桌面歌词窗口来实现
正在播放永远在最上面，所以暂时不做出调整，等待4.0可能会做出调整
阴影颜色透明度均可以通过右击菜单来调整
关闭按钮最小化到托盘功能4.0会实现，目前仅可通过快捷键
网易云词库可手动导入，4.0会增加网易云的自动搜索，但是不会提供默认网易云的选项

**Comment by WXRIW** [comment]
Lyricify 4.0 中已完成 2, 3 功能，此 Issue 关闭。
但是 4.0 中去除了 iTunes 的支持。
