### ISSUE TITLE
复制歌词 新功能建议

### ISSUE THREAD

**Issue by Gokenu** [WXRIW/Lyricify-App#54]
很棒的软件！
新功能建议：
1. 主页面UI中希望可以加上左键复制当前行或者右键菜单复制当前行的功能，方便分享、搜索歌词
2. 打赏部分希望可以提供其它方式，目前支付宝不支持境外支付，显示对方收款功能只能在境内使用

**Comment by WXRIW** [comment]
Lyricify 4.0 中将提供多种歌词复制选项，此 Issue 关闭。
