### ISSUE TITLE
[Bug] 标记为纯音乐时可能闪退

### ISSUE THREAD

**Issue by Mooos-MoSheng** [WXRIW/Lyricify-App#56]
![GIF 2022-5-15 15-15-31](https://user-images.githubusercontent.com/46639923/168461771-0e7da5d7-9aab-41a9-b9fd-5fb262ef5bfc.gif)
如上图。
环境：Windows10 专业版 19041

**Comment by WXRIW** [comment]
@Mooos-MoSheng 等待修复

**Comment by WXRIW** [comment]
Lyricify 3.8.3 中将修复，此 Issue 关闭。
目前在最后的测试阶段，预计明天发布修复后的版本。
