### ISSUE TITLE
[Bug & Guess] 部分 lrc 具有时间轴但显示没有时间轴

### ISSUE THREAD

**Issue by Mooos-MoSheng** [WXRIW/Lyricify-App#57]
![image](https://user-images.githubusercontent.com/46639923/169635483-f15dfd91-c8f0-4f25-9c69-9496d6606cc4.png)

如上。

Guess：可能是时间轴和歌词之间没有空格的问题。

**Comment by WXRIW** [comment]
附上spotify id和isrc，暑假处理

**Comment by WXRIW** [comment]
请尽快附上 isrc 和 spotify id，此 issue 暂时关闭，可重新开启
