### ISSUE TITLE
第一次打开就报错

### ISSUE THREAD

**Issue by qinfeifan** [WXRIW/Lyricify-App#59]
![image](https://user-images.githubusercontent.com/83999195/171360760-01ec51b9-3c82-4823-aa12-d859d028e9d7.png)

**Comment by WXRIW** [comment]
@qinfeifan 加群看置顶公告

**Comment by Potato009** [comment]
> ![image](https://user-images.githubusercontent.com/83999195/171360760-01ec51b9-3c82-4823-aa12-d859d028e9d7.png)

你没有安装Microsoft Edge Webview2 Runtime，去https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section安装去
