### ISSUE TITLE
希望可以获取spotify或者外网的歌词

### ISSUE THREAD

**Issue by nancheung97** [WXRIW/Lyricify-App#6]
一些在大陆被封禁的歌手，qq音乐无法搜到歌词，比如李志
https://open.spotify.com/playlist/4a5O8yZjPRFoZm2mABOQHY?si=gDBoXgA-S9G2e2G1CoUURA

**Comment by WXRIW** [comment]
在大陆被封禁是有一定原因的，Lyricify遵守国家法律法规，同样也不会允许这些人的歌的歌词出现。
感谢对Lyricify的支持，谢谢。
另外，外网歌词一般不带时间轴，无法使用。
