### ISSUE TITLE
歌词无法找到

### ISSUE THREAD

**Issue by SCPf-166** [WXRIW/Lyricify-App#62]
用了一段时间为什么原来找得到的歌词都没有了，甚至有的歌曲一开始还跳了一下标题和歌手，却还是显示歌词暂时无法被找到
我在B站的视频底下也留了言，求大佬解答

**Comment by SCPf-166** [comment]
都是日语歌曲，原先都有歌词的

**Comment by Potato009** [comment]
@SCPf-166 要不试试搜索网易云和QQ音乐的歌词？

**Comment by SCPf-166** [comment]
> Potato009

搜索过，也有用，但是下次再放同一首歌就又没有了，一次性的

**Comment by Potato009** [comment]
@SCPf-166 有试过左下角按钮标记为正确歌词吗

**Comment by SCPf-166** [comment]
还是不行，而且标记完之后刚从网易云导的歌词反而又消失了，显示无法找到歌词

**Comment by Potato009** [comment]
@SCPf-166 等4.0更新吧，可能到那个时候就好了

**Comment by SCPf-166** [comment]
好吧，还是谢谢你的帮助，我待会再继续试一试看看

**Comment by WXRIW** [comment]
@SCPf-166 日语歌词搜索一直是难以解决的问题，等下一大版本更新我去优化

**Comment by SCPf-166** [comment]
知道了，作者大大加油😉

**Comment by snape2019** [comment]
同样遇到这个问题，所有韩语歌都找不到歌词。希望尽快修复。

**Comment by WXRIW** [comment]
@snape2019 等几个月之后的4.0，3.x我不打算再花什么功夫去弄了

**Comment by WXRIW** [comment]
怀疑是qq音乐服务器端有变化，我过几天忙完之后来检查下

**Comment by WXRIW** [comment]
长时间没有新的反馈，此 Issue 关闭。
