### ISSUE TITLE
热键冲突

### ISSUE THREAD

**Issue by zmsong93** [WXRIW/Lyricify-App#65]
软件启动时候会占用几个热键, 希望支持自定义快捷键. 或者干脆移除快捷键? 到现在不知道这几个快捷键的作用

**Comment by WXRIW** [comment]
@zmsong93 https://github.com/WXRIW/Lyricify-App/wiki/%E5%85%A8%E5%B1%80%E5%BF%AB%E6%8D%B7%E9%94%AE

**Comment by zmsong93** [comment]
thanks it`s working
