### ISSUE TITLE
【功能建议】默认窗口可以自由选择风格

### ISSUE THREAD

**Issue by amarazshi** [WXRIW/Lyricify-App#68]
1.Lyricify是否可以 桌面歌词/Spotify歌词/移动端歌词/Apple Music歌词 等风格化，成为主窗口风格化选项，而不是开一个新窗口？
原因来自于 我更倾向于使用apple music歌词风格，但是每次在选择后仍然保留主窗口，摆两个窗口又多余，再把主窗口关掉的话又需要多操作hhh。
2.有一点排版问题：在使用迷你模式时候，主窗口右下角的第三方歌词来源其实可以隐藏，不然可能会和长歌词重叠，还有图片与文字重叠，迷你模式本身排版也可以再优化一下。
<img width="364" alt="image" src="https://user-images.githubusercontent.com/62531410/185713744-2d6786ff-2ee3-43bf-a14c-96777c7bbc13.png">
3.就第一个提议还可以再发散一下，Lyricify可以开放skin plugin，如cider那样。

**Comment by WXRIW** [comment]
@amarazshi 2，3暂不考虑，新版不会出现2到问题，1新版已经在做了，但是桌面歌词不可能不独立出来

**Comment by WXRIW** [comment]
@amarazshi 1目前可以通过ctrl+h来解决
