### ISSUE TITLE
单曲循环

### ISSUE THREAD

**Issue by Truman-NB** [WXRIW/Lyricify-App#69]
单曲循环不会刷新从头展示歌词 只有第一遍是正常的 之后似乎不能识别就停留在最后一句歌词

**Comment by WXRIW** [comment]
@Truman-NB 使用的是spotify吗，是否登录

**Comment by Truman-NB** [comment]
> @Truman-NB 使用的是spotify吗，是否登录

是Spotify 没登录

**Comment by WXRIW** [comment]
@Truman-NB 登录即可解决

**Comment by Truman-NB** [comment]
确实确实 谢谢解答
