### ISSUE TITLE
部分ip部分时间无法访问QQ音乐官方搜索API

### ISSUE THREAD

**Issue by MJscofield** [WXRIW/Lyricify-App#7]
如题,昨晚还是正常使用,今天每一首歌曲都无法获取到歌词, 是我这边软件出了问题还是服务器那边出现了问题;
还有就是作者是否考虑建立一个vx群或者电报群来用作用户交流群使用.

**Comment by WXRIW** [comment]
已建立tg群：[https://t.me/lyricify](url)
您的问题可以尝试重新打开Lyricify，具体可以在群内发图片

**Comment by WXRIW** [comment]
已在3.5.3修复，大概下月更新。可能会提早放出。

**Comment by WXRIW** [comment]
3.5.3已更新，当官方搜索无法访问时自动切换到备用搜索
