### ISSUE TITLE
在登陆Spotify后，依然保留获取其他软件的音乐歌词的功能

### ISSUE THREAD

**Issue by Andy-Dunne** [WXRIW/Lyricify-App#71]
在Lyricify中登录我的Spotify账户后，图一中获取其他来源音频歌词的功能会消失，如图二：
![图片](https://user-images.githubusercontent.com/69418566/188470147-d5658ff7-a456-485e-beed-0021859538df.png)
【图一】
![图片](https://user-images.githubusercontent.com/69418566/188470186-ed83ea4f-e71e-4a91-b803-39005e85046f.png)
【图二】

然而在不登陆Spotify的状态下，Lyricify无法获得歌曲的专辑封面（这个作者您在登陆界面写有提示，我也了解这不是一个Bug）
个人除了Spotify之外，也会使用其他音乐软件，而且我也希望能在这些软件里使用Lyricify的歌词UI。但是目前的设计让切换不同的音乐软件并在Lyricify中同步显示歌词变得非常麻烦，希望作者大大能修复一下这个问题，谢谢！

**Comment by WXRIW** [comment]
参考 #2 #9

**Comment by Andy-Dunne** [comment]
是我看漏了issue 没看到这个问题已经解决了 不好意思
还是感谢作者大大

另外作者有考虑在后续版本中增加在应用内修改的功能吗

**Comment by WXRIW** [comment]
@Andy-Dunne 4.0将仅支持Spotify，3.x继续维护，用来支持其他版本

**Comment by Andy-Dunne** [comment]
好的 感谢您的耐心回复
