### ISSUE TITLE
【功能建议】希望能添加Windows Media Player支持

### ISSUE THREAD

**Issue by zangliu2077** [WXRIW/Lyricify-App#73]
平时喜欢单独买付费电子的音乐CD专辑，其他播放器好像不是特别支持CD专辑显示正确的名字和歌手信息，试用只看到Windows Media Player支持，如果适配不是太难的话，希望作者之后能添加Windows Media Player的适配，感谢。之前微软应用商店有个软件musixmatch支持这个播放器，但是现在好像已经下架了，就再没有支持WMP的歌词工具了

**Comment by WXRIW** [comment]
这个要等比较长的时间，因为目前4.0的开发已经过半，但4.0设计的是仅支持Spotify，所以是不会添加WMP支持的，只能等后续有时间在3.x基础上添加

**Comment by zangliu2077** [comment]
> 由于目前 4.0 的开发过时，4.0 的设计只是支持 Spotify 的，所以是不会添加支持的，而是等有等基础的时间已经在 3.x 上添加了

没有关系，只要以后有支持的可能，我就心满意足了，谢谢作者大大的回复

**Comment by WXRIW** [comment]
目前决定 Lyricify 3 进入 EOL，所以此 Issue 暂时关闭。
