### ISSUE TITLE
新版灵动岛功能反馈！！！

### ISSUE THREAD

**Issue by Fox-Yuan** [WXRIW/Lyricify-App#74]
希望灵动岛可以设置形状变化固定位置。比如我想最左侧为固定基点，灵动岛缩放是从最左侧往右缩放，或者我也可以设置成最右侧固定，动画从最右侧开始缩放。现在固定点在中间，总感觉动画缩放太晃眼，变化幅度太大了，注意力都被他吸引了。个人的一些小小看法，望作者大大可以改进改进。

**Comment by WXRIW** [comment]
@Fox-Yuan 灵动岛的缩放就是从中间向两侧缩放，而如果是从两侧作为中心点去缩放的话，形状会很奇怪

**Comment by WXRIW** [comment]
@Fox-Yuan 你如果是从左侧或者右侧进行缩放那不是更晃眼吗

**Comment by Fox-Yuan** [comment]
我是希望增加灵动岛更多的设置，可以个性化一些。因为我个人可能想把他放在左下角或者右下角，嘿嘿。或者歌词的弹簧特效幅度再小一点？好像现在灵动岛的大小是随歌词放大缩小的，歌词切换的时候会变小，如果灵动岛在歌词切换的时候不缩小，而是切换完成后再适应歌词大小会不会好一些？总感觉现在动的幅度太大了一些，稍稍有点晃眼

**Comment by WXRIW** [comment]
@Fox-Yuan 3.x的灵动岛可能不会再接着开发了，现在在弄4.0

**Comment by Fox-Yuan** [comment]
好滴，以后有机会再完善吧，希望越来越好！

**Comment by WXRIW** [comment]
@Fox-Yuan 其实灵动岛要的效果不就是晃眼的弹动动画嘛😂😂

**Comment by Fox-Yuan** [comment]
个人人为有一点点过晃，可能就我个人认为，不知道诶。就是一个小小的建议。（作者回信息真快( •̀ ω •́ )✧）

**Comment by WXRIW** [comment]
@Fox-Yuan 😜😜哈哈哈，可能看习惯了就好了，当时特意把弹跳的效果做的很明显的

**Comment by Fox-Yuan** [comment]
嗯嗯😂

**Comment by WXRIW** [comment]
Lyricify 4.0 中已完成灵动词岛的开发，故关闭此 Issue。
