### ISSUE TITLE
歌词问题

### ISSUE THREAD

**Issue by zoeyuezhuo** [WXRIW/Lyricify-App#75]
**歌曲:** 千年之戀
**歌手:** F.I.R.
**曲目编号:** 2
**ID:** 6J3YmODloSi669U6cKbtTH
**ISRC:** TWA530505402
**专辑 ID:** 1qgcGkqyrWQdnrbepB9HEJ
**详情:** 歌词版本选择错误，时间轴错误

**Comment by WXRIW** [comment]
@zoeyuezhuo 看readme，不要新开issue，并且目前不受理此类问题
