### ISSUE TITLE
灵动岛桌面歌词功能反馈

### ISSUE THREAD

**Issue by sevenMZ** [WXRIW/Lyricify-App#76]
请问灵动岛可以不要单独占一个任务栏窗格么？主要的问题是挤占任务栏，歌词占窗口也有点反直觉。（如果4.0还有这个东西的话）

**Comment by WXRIW** [comment]
@sevenMZ 一行代码的事儿，当时为了开发方便就没写了。等4.0吧

**Comment by WXRIW** [comment]
Lyricify 4.0 中已完成此功能，此 Issue 关闭。
