### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Flameisround** [WXRIW/Lyricify-App#78]
希望增加在中日韩歌词的情况下使用竖排文字的选项。

**Comment by WXRIW** [comment]
@Flameisround 此功能无法实现，抱歉

**Comment by Potato009** [comment]
@Flameisround 说句实话竖排没横排漂亮😐

**Comment by Flameisround** [comment]
> @Flameisround 说句实话竖排没横排漂亮😐

审美不同罢了，中日都有竖排的传统，虽然是传统但并不意味着过时，那种特别的韵味总有人会喜欢的。还有一点，竖排更不容易遮挡其他应用的界面，横排有时很碍事。

**Comment by WXRIW** [comment]
@Flameisround 做不了，只能强制转90度

**Comment by WXRIW** [comment]
@Flameisround 阅读的时候还得斜着看
