### ISSUE TITLE
桌面歌词显示问题

### ISSUE THREAD

**Issue by Flameisround** [WXRIW/Lyricify-App#79]
![image](https://user-images.githubusercontent.com/115167348/200369091-7149aa31-af36-4c47-8cf6-dfd700f06b1e.png)
![image](https://user-images.githubusercontent.com/115167348/200369101-3869f620-bf65-439a-a88a-b20adab3172f.png)
放任务栏过一会儿后自动消失

**Comment by WXRIW** [comment]
@Flameisround 不是消失了，是被任务栏遮住了，这是正常的

**Comment by WXRIW** [comment]
@Flameisround 但是4.0中好像修好了这个问题

**Comment by Flameisround** [comment]
> @Flameisround 但是4.0中好像修好了这个问题

即将到来的版本吗，期待😘
