### ISSUE TITLE
多屏（竖屏）下全屏模式无法显示在正确的屏幕（仅部分环境下）

### ISSUE THREAD

**Issue by RebirthEgo** [WXRIW/Lyricify-App#8]
1、字体边缘毛刺感太强影响观感，能否处理得圆滑些；
2、建议加入自订换字体字号；
3、建议加入全屏模式，全屏模式下隐藏下面的所有图标；
4、是否可以加入 喜欢歌曲 下一曲  ，这样就不必听到喜欢的歌曲在切换到播放器上操作。

**Comment by RebirthEgo** [comment]
刚没看到全屏模式，不好意思，但全屏模式在双屏情况下，只能在主屏显示，不能在副屏显示

**Comment by WXRIW** [comment]
1的字体指的是哪部分，整个Lyricify吗？

**Comment by WXRIW** [comment]
全屏模式多屏的话会显示在lyricify所在的屏幕，而不是一直在主屏幕

**Comment by WXRIW** [comment]
字号的话直接ctrl+鼠标滚轮 或 ctrl+‘-’/'+' 或 双指缩放就好了

**Comment by WXRIW** [comment]
喜欢歌曲以前考虑过，以后应该会加入的。
下一曲加入的可能性不大，因为这个功能需要Spotify premium，但我没有会员

**Comment by RebirthEgo** [comment]
> 1的字体指的是哪部分，整个Lyricify吗？

对，毛刺感是Lyricify的主界面，他不能像其它界面一样平滑

**Comment by RebirthEgo** [comment]
> 全屏模式多屏的话会显示在lyricify所在的屏幕，而不是一直在主屏幕

我这里lyricify是在副屏，但一全屏就会跑到主屏去，无法跟随lyricify所在屏幕

**Comment by RebirthEgo** [comment]
> 字号的话直接ctrl +鼠标滚轮或ctrl +'-'/'+'或双指缩放就好了

滚轮缩放是整体都缩放，下面的图标也跟着缩放，会显得很粗糙，如果只缩放歌曲部分就好了

**Comment by RebirthEgo** [comment]
歌词不对时，通过网易ID获取后不能永久保留，在切换时又回到最初

**Comment by RebirthEgo** [comment]
<img width="540" alt="Snipaste_2021-05-15_14-20-37" src="https://user-images.githubusercontent.com/54738173/118350361-ca59e200-b588-11eb-8b64-c97fdb7fbcdb.png">
滚动歌词和移动端歌词，字体渲染比较好，但不能调整字体大小，我是在PC上使用

**Comment by WXRIW** [comment]
> > 1的字体指的是哪部分，整个Lyricify吗？
> 
> 对，毛刺感是Lyricify的主界面，他不能像其它界面一样平滑

能给个截图吗

**Comment by WXRIW** [comment]
> > 全屏模式多屏的话会显示在lyricify所在的屏幕，而不是一直在主屏幕
> 
> 我这里lyricify是在副屏，但一全屏就会跑到主屏去，无法跟随lyricify所在屏幕

这个的话我在自己这边测试是没有问题的，所以也不知道是哪里的问题，暂时没有解决方案。
可以发下屏幕摆放的截图（设置里）我分析下

**Comment by WXRIW** [comment]
> > 字号的话直接ctrl +鼠标滚轮或ctrl +'-'/'+'或双指缩放就好了
> 
> 滚轮缩放是整体都缩放，下面的图标也跟着缩放，会显得很粗糙，如果只缩放歌曲部分就好了

这个功能是从3.5.3才有的，花了我几个小时才搞好，以前是只会缩放歌词区的。
我下版加个设置选项吧

**Comment by WXRIW** [comment]
> 歌词不对时，通过网易ID获取后不能永久保留，在切换时又回到最初

需要标记为正确歌词才可以，并且不能开翻译。开了翻译功能之后就不会从我服务器上搜索，而是直接从qq音乐搜索。
这个问题将在明年7月解决

**Comment by WXRIW** [comment]
> <img alt="Snipaste_2021-05-15_14-20-37" width="540" src="https://user-images.githubusercontent.com/54738173/118350361-ca59e200-b588-11eb-8b64-c97fdb7fbcdb.png">
> 
> 滚动歌词和移动端歌词，字体渲染比较好，但不能调整字体大小，我是在PC上使用

调字体只能通过调整窗口大小，不会改变的，因为要和移动端保持一致

**Comment by RebirthEgo** [comment]
> > > 1的字体指的是哪部分，整个Lyricify吗？
> > 
> > 
> > 对，毛刺感是Lyricify的主界面，他不能像其它界面一样平滑
> 
> 能给个截图吗

<img width="538" alt="Snipaste_2021-05-15_19-08-31" src="https://user-images.githubusercontent.com/54738173/118382217-9aace780-b625-11eb-9665-0e8fe204c84b.png">

同一首歌，下为Musixmatch Lyrics渲染，但它对国内支持不友好

**Comment by RebirthEgo** [comment]
> > > 全屏模式多屏的话会显示在lyricify所在的屏幕，而不是一直在主屏幕
> > 
> > 
> > 我这里lyricify是在副屏，但一全屏就会跑到主屏去，无法跟随lyricify所在屏幕
> 
> 这个的话我在自己这边测试是没有问题的，所以也不知道是哪里的问题，暂时没有解决方案。
> 可以发下屏幕摆放的截图（设置里）我分析下

<img width="2460" alt="Snipaste_2021-05-16_09-02-17" src="https://user-images.githubusercontent.com/54738173/118382251-fa0af780-b625-11eb-860d-c6e356a0959b.png">

左边为主屏，右边为副屏，不管怎么放全屏后都是跑到主屏上

**Comment by RebirthEgo** [comment]
> > > > 全屏模式多屏的话会显示在lyricify所在的屏幕，而不是一直在主屏幕
> > > 
> > > 
> > > 我这里lyricify是在副屏，但一全屏就会跑到主屏去，无法跟随lyricify所在屏幕
> > 
> > 
> > 这个的话我在自己这边测试是没有问题的，所以也不知道是哪里的问题，暂时没有解决方案。
> > 可以发下屏幕摆放的截图（设置里）我分析下
> 
> <img alt="Snipaste_2021-05-16_09-02-17" width="2000" src="https://user-images.githubusercontent.com/54738173/118382251-fa0af780-b625-11eb-860d-c6e356a0959b.png">
> 
> 左边为主屏，右边为副屏，不管怎么放全屏后都是跑到主屏上

显示器的分辨率不一样，一个是4K，一个是1080，不知道这个有影响不

**Comment by RebirthEgo** [comment]
我是平面设计师，如果有需要UI方面可以帮上忙

**Comment by WXRIW** [comment]
> > > > 1的字体指的是哪部分，整个Lyricify吗？
> > > 
> > > 
> > > 对，毛刺感是Lyricify的主界面，他不能像其它界面一样平滑
> > 
> > 
> > 能给个截图吗
> 
> <img alt="Snipaste_2021-05-15_19-08-31" width="538" src="https://user-images.githubusercontent.com/54738173/118382217-9aace780-b625-11eb-9665-0e8fe204c84b.png">
> 
> 同一首歌，下为Musixmatch Lyrics渲染，但它对国内支持不友好

看起来差不多啊，可能是字体问题吧，换成segoe ui之后可能好一点（启动参数 -font segoe）
![image](https://user-images.githubusercontent.com/62491584/118383149-009d6d00-b62e-11eb-85d8-5ea53f9f6122.png)

**Comment by WXRIW** [comment]
> > > > 全屏模式多屏的话会显示在lyricify所在的屏幕，而不是一直在主屏幕
> > > 
> > > 
> > > 我这里lyricify是在副屏，但一全屏就会跑到主屏去，无法跟随lyricify所在屏幕
> > 
> > 
> > 这个的话我在自己这边测试是没有问题的，所以也不知道是哪里的问题，暂时没有解决方案。
> > 可以发下屏幕摆放的截图（设置里）我分析下
> 
> <img alt="Snipaste_2021-05-16_09-02-17" width="2000" src="https://user-images.githubusercontent.com/54738173/118382251-fa0af780-b625-11eb-860d-c6e356a0959b.png">
> 
> 左边为主屏，右边为副屏，不管怎么放全屏后都是跑到主屏上

试试看把lyricify完全拖到副屏，不要在主屏有残留，也不要溢出副屏范围
我下次找机会架个竖屏试试看

**Comment by WXRIW** [comment]
> > 字号的话直接ctrl +鼠标滚轮或ctrl +'-'/'+'或双指缩放就好了
> 
> 滚轮缩放是整体都缩放，下面的图标也跟着缩放，会显得很粗糙，如果只缩放歌曲部分就好了

最新版已支持！
菜单-->设置-->手动（高级）
找到这一行
    `"is_scale_title_and_control": true, //让标题和控制按钮同歌词一起缩放`
把`true`改为`false`即可

**Comment by RebirthEgo** [comment]
> > > 字号的话直接ctrl +鼠标滚轮或ctrl +'-'/'+'或双指缩放就好了
> > 
> > 
> > 滚轮缩放是整体都缩放，下面的图标也跟着缩放，会显得很粗糙，如果只缩放歌曲部分就好了
> 
> 最新版已支持！
> 菜单-->设置-->手动（高级）
> 找到这一行
> `"is_scale_title_and_control": true, //让标题和控制按钮同歌词一起缩放`
> 把`true`改为`false`即可

好的

**Comment by WXRIW** [comment]
> > > > 全屏模式多屏的话会显示在lyricify所在的屏幕，而不是一直在主屏幕
> > > 
> > > 
> > > 我这里lyricify是在副屏，但一全屏就会跑到主屏去，无法跟随lyricify所在屏幕
> > 
> > 
> > 这个的话我在自己这边测试是没有问题的，所以也不知道是哪里的问题，暂时没有解决方案。
> > 可以发下屏幕摆放的截图（设置里）我分析下
> 
> <img alt="Snipaste_2021-05-16_09-02-17" width="2000" src="https://user-images.githubusercontent.com/54738173/118382251-fa0af780-b625-11eb-860d-c6e356a0959b.png">
> 
> 左边为主屏，右边为副屏，不管怎么放全屏后都是跑到主屏上

我今天测试了下，是这样的屏幕配置，但是没有出现如题所述的问题
![image](https://user-images.githubusercontent.com/62491584/120923830-313f6680-c703-11eb-8a58-ff22a829644e.png)
![image](https://user-images.githubusercontent.com/62491584/120923836-356b8400-c703-11eb-9277-62261f2c135e.png)
Lyricify一定要完全移动到副屏上！
你再试试看，如果仍然没有解决我再想想办法。

**Comment by RebirthEgo** [comment]
我也是这样的配置，还是自动跑到主屏上，不知道什么原因，算了我也很少使用这个功能。
有个新问题，当歌词页被放大过后重启不会显示主界面，每次必须要重置窗口后才能正常显示。

**Comment by WXRIW** [comment]
先重置设置（菜单-->设置-->重置所有设置），然后关闭后重新打开Lyricify，再在手动（高级）里重新设置is_scale_title_and_control

**Comment by RebirthEgo** [comment]
> 先重置设置（菜单-->设置-->重置所有设置），然后关闭后重新打开Lyricify，再在手动（高级）里重新设置is_scale_title_and_control

OK，解决了谢谢
