### ISSUE TITLE
新功能什么时候实现？

### ISSUE THREAD

**Issue by Fox-Yuan** [WXRIW/Lyricify-App#80]
封面的功能是么时候实现？想要
![image](https://user-images.githubusercontent.com/87629069/200486452-b9c61112-bc2e-4ca6-8e41-967a3bbe1b90.png)

**Comment by WXRIW** [comment]
@Fox-Yuan 这是4.0，敬请期待

**Comment by WXRIW** [comment]
现在已经默认不是那样了，改成下面这样了
![image](https://user-images.githubusercontent.com/62491584/200487135-ab99361d-2a48-4a24-8adb-4d22a93aac78.png)

**Comment by Fox-Yuan** [comment]
期待！！
