### ISSUE TITLE
macOS版本的需要

### ISSUE THREAD

**Issue by yuanhexie** [WXRIW/Lyricify-App#81]
作者有可能参考
https://spicetify.app
中的拓展插件规则
成为Spicetify 商场中的一个插件吗
https://github.com/spicetify/spicetify-cli/tree/92d2c10eb6ecf7b9e93d3d4f5563ed8346b299f1/CustomApps/lyrics-plus
他们的拓展插件里也有一个类似的歌词插件并且可以组成这样的效果

**Comment by WXRIW** [comment]
不可以，本软件不兼容Spicetify

**Comment by WXRIW** [comment]
Lyricify软件和Spicetify插件的原理完全不同，所以完全无法实现
