### ISSUE TITLE
【功能建议】是否可添加任务栏歌词功能

### ISSUE THREAD

**Issue by shengchenyang** [WXRIW/Lyricify-App#82]
在工作等使用电脑的时候，歌词的显示或交互尽量少的干扰到鼠标操作或尽量避免占用过多的桌面显示。其实灵动岛的歌词显示样式就差不多快解决这种场景，只是在浏览器网页操作标签栏等场景还是有点难受。

所以我才想到任务栏歌词的场景，不知道作者有无更好的方法。

**Comment by Potato009** [comment]
@shengchenyang 4.0的灵动词岛会在鼠标滑过去的时候自动隐藏，等4.0发布吧

**Comment by WXRIW** [comment]
@shengchenyang 桌面歌词可以直接放在任务栏（4.0）

**Comment by shengchenyang** [comment]
ok，明白了，感谢回复。
