### ISSUE TITLE
能否添加记忆之前调整的窗口位置的功能呢？

### ISSUE THREAD

**Issue by zero617** [WXRIW/Lyricify-App#83]

**Comment by WXRIW** [comment]
@zero617 现在不支持吗

**Comment by zero617** [comment]
@WXRIW  apple music、移动端滚动歌词等等二级打开的窗口无法记忆窗口位置

**Comment by WXRIW** [comment]
@zero617 apple music歌词界面在4.0中不再以独立的窗口显示，移动端滚动歌词在4.0中被移除

**Comment by zero617** [comment]
@WXRIW 好的，感谢 顺便问下4.0有内测体验的途径吗？

**Comment by WXRIW** [comment]
@zero617 有预览体验计划，但是有加入条件

**Comment by zero617** [comment]
@WXRIW 我qq私聊了
