### ISSUE TITLE
一些问题与建议

### ISSUE THREAD

**Issue by Xicrosoft** [WXRIW/Lyricify-App#90]
## 问题
1. **未来会支持 macOS 吗**
   > Lyricify 4 有些地方比 Apple Music for mac 好太多
3. **未来 Lyricify 4 会支持 Apple Music / ITunse 平台吗**
4. 未来可以支持登录 Apple ID /添加到资料库/添加到歌单/AM 无损音质/空间音频 等等功能吗
   > 应该不行（bushi
6. 未来会收费吗
7. 未来会开源吗

## 建议
1. 歌词的进度（已播放/未播放）的交界处可以加一些过渡
2. 背景可以根据音乐的节奏跳动（可以参考 Apple Music 原版）
   > 看[宣传视频](https://www.bilibili.com/video/BV1Z14y1g7nS/)里好像没有背景跟随歌曲的节奏跳动和歌词进度交界的过度

**Comment by Xicrosoft** [comment]
期待 Lyricify 4 发布

**Comment by cocgy1108** [comment]
發現一個問題是在繁體中文顯示時會發生亂碼的現象 應該和編碼有關係 
歌詞會以???問號來呈現

**歌曲:** 後來的我們
**歌手:** Mayday
**曲目編號:** 6
**ID:** 13AruKdh8wJhWx6i5dV8X1
**ISRC:** TWK231610206
**專輯 ID:** 4hg4cR8QMbE0xuvoxoA6DX
**詳情:** 繁體中文會亂碼呈現

**Comment by WXRIW** [comment]
@cocgy1108 4中已修复，乱码是系统导致的，可尝试更换英文系统，或等待5天后即将发布的Lyricify 4

**Comment by cocgy1108** [comment]
> @cocgy1108 4中已修复，乱码是系统导致的，可尝试更换英文系统，或等待5天后即将发布的Lyricify 4

了解 感謝解答 期待您發布新版本
