### ISSUE TITLE
Lyricify 4 后续会给 Apple Music 提供支持吗

### ISSUE THREAD

**Issue by SkfyZ** [WXRIW/Lyricify-App#91]
Apple Music在微软商店已经有上架app。Lyricify 4 能否支持 apple music？

**Comment by WXRIW** [comment]
@SkfyZ Lyricify 4 仅支持 Spotify

**Comment by SkfyZ** [comment]
Lyricify 3 的 Apple Music 可以使用吗？

**Comment by WXRIW** [comment]
@SkfyZ 不可以，只可以使用 iTunes。AM Preview 目前没有接入 Media Session，完全获取不到信息

**Comment by SkfyZ** [comment]
好的，谢谢

**Comment by WXRIW** [comment]
🤝
