### ISSUE TITLE
Virus detected by Windows Defender 

### ISSUE THREAD

**Issue by Ashuai-jpg** [WXRIW/Lyricify-App#94]
Lyricify.Setup.Ver.4.0.0.230122-release.exe

**Comment by WXRIW** [comment]
Thanks for letting me know, I'll submit it to Microsoft so it won't be reported as virus later.

**Comment by WXRIW** [comment]
Is the setup exe the only file detected as virus? Or the main program file (Lyricify for Spotify.exe) has also detected as virus?

**Comment by Ashuai-jpg** [comment]
Yes, and now it can install without defender's alert
