### ISSUE TITLE
Profile picture error 头像错误

### ISSUE THREAD

**Issue by itsHenry35** [WXRIW/Lyricify-App#95]
看起来头像貌似被拉伸过了，左边是lyricify的界面，右边是spotify的界面
![image](https://user-images.githubusercontent.com/58730749/213899444-227a91d9-4b5b-443c-99dc-40a451a5c5db.png)

**Comment by WXRIW** [comment]
请自行更换头像，确保头像是正方形的。目前您的头像是长方形，为了显示完整，所以就成了椭圆状了

**Comment by itsHenry35** [comment]
> 请自行更换头像，确保头像是正方形的。目前您的头像是长方形，为了显示完整，所以就成了椭圆状了

感谢，的确可以，但是为何不像spotify这样，只展示头像最中间的部分呢

**Comment by WXRIW** [comment]
因为 Lyricify 想展现完整的图片，来弥补 Spotify 的这个缺陷
