### ISSUE TITLE
Media Session Disconnected 

### ISSUE THREAD

**Issue by Ashuai-jpg** [WXRIW/Lyricify-App#96]
It looks like not playable at all and even with notification of 'Premium Required '

**Comment by WXRIW** [comment]
You need to play music on Spotify, so Lyricify can get lyrics for you.

**Comment by Ashuai-jpg** [comment]
Sorry about my foolish😅. BTW, It works pretty nice with only some render incoherence occasionally.

**Comment by WXRIW** [comment]
Turning off blur effect might help.

**Comment by Ashuai-jpg** [comment]
Thanks for your work and patience, and **_Happy Lunar New Year_**!!!

**Comment by WXRIW** [comment]
Hope you enjoy Lyricify 4, and happy Chinese New Year!!!
