### ISSUE TITLE
Suggestion: provide a choice to let color mode adapt to system's color mode 建议：提供一个选项让颜色模式与系统相同步

### ISSUE THREAD

**Issue by itsHenry35** [WXRIW/Lyricify-App#97]
![image](https://user-images.githubusercontent.com/58730749/213900392-98769eea-e765-4e68-ba22-8453c14be661.png)
目前Color Mode要么浅色要么深色，无法根据系统自动调节

**Comment by WXRIW** [comment]
不提供，因为 Lyricify 的浅色太丑了，如果之后有用户做出来了更好看的浅色配色主题，并且 Lyricify 采用的话，才会考虑加入跟随系统
