### ISSUE TITLE
希望能够加入Musixmatch的歌词源

### ISSUE THREAD

**Issue by SheepYhangCN** [WXRIW/Lyricify-App#98]
有些歌在Musixmatch上是有歌词的
但是QQ音乐和网易云音乐都没有
所以希望能够加上Musixmatch源
就是Spotify目前用的歌词源

**Comment by WXRIW** [comment]
不支持

**Comment by WXRIW** [comment]
没有的歌词可以手动导入，但是不会考虑接入 Musixmatch

**Comment by SheepYhangCN** [comment]
（回复好快 这是一直在盯着issue界面吗

**Comment by WXRIW** [comment]
GitHub 在 Tg 群有同步

**Comment by fucmmmm** [comment]
草我还天天在musicmatch传歌词,术曲基本没歌词

**Comment by am-2333** [comment]
@fucmmmm Musixmatch的api需要付费
有一个曲线救国的方法，可让在musixmatch有管理员账号的认证歌词，就可以在Spotify查看了
