### ISSUE TITLE
有些歌曲在不同地区的歌名是不同语言的 这就会导致国内平台搜索不到歌词

### ISSUE THREAD

**Issue by SheepYhangCN** [WXRIW/Lyricify-App#99]
有些歌曲在不同账号地区的名字是不同的
比如PEPOYO的曲子 在日区是日文 在其它区都是英文
而QQ音乐和网易云音乐上统一收录的都是日文名
这就会导致读取不到歌词
如果可以的话希望能解决一下

**Comment by WXRIW** [comment]
把lyricify调成日语

**Comment by SheepYhangCN** [comment]
![image](https://user-images.githubusercontent.com/44539204/213905198-da26bb5f-bfe3-49db-84c4-911156018f45.png)
并不行

**Comment by WXRIW** [comment]
重启过lyricify了吗

**Comment by WXRIW** [comment]
还是获取不到的话可以手动导入

**Comment by WXRIW** [comment]
（新用户需要等待一天才能导入

**Comment by SheepYhangCN** [comment]
重启了也不行（寄

**Comment by WXRIW** [comment]
那就只能靠手动导入了，自动搜索没办法了

**Comment by SheepYhangCN** [comment]
我记得lyricify3的时候搜歌词不是可以填歌名吗
填日文歌名就能搜索到了
怎么4就没了

**Comment by WXRIW** [comment]
你说的 在日区是日文 在其它区都是英文 我是没有遇到过这种情况，能否提供一下两个区同一张专辑的两个id呢，我来研究一下

**Comment by WXRIW** [comment]
> 

那个功能是搜索歌词，就是搜歌词出来看，而不是跟随音乐用的。很多人都理解错了这个功能

**Comment by SheepYhangCN** [comment]
草了 不同区的歌是分开的 这个作者甚至日文号和英文号都不是同一个
我用我的港区号看她日文号没有曲子 不登录就能看到
那大概是不能做到自动检测了 除非提前设置类似歌名映射之类的功能 那样的话工作量又太大了

**Comment by WXRIW** [comment]
哎，只能手动传了，但是只要传过了就好了，也算是对 Lyricify 词库的贡献吧，一人上传，所有人都可以使用
